/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.certificates.api

import kubescala.certificates.models.APIGroup
import kubescala.certificates.JsonSupport.{*, given}
import kubescala.certificates.FormSerializable
import kubescala.certificates.FormStyleFormat
import kubescala.certificates.HeaderSerializable
import kubescala.certificates.ApiKeyLocation
import kubescala.certificates.PathStyleFormat
import kubescala.certificates.PathSerializable
import kubescala.certificates.CookieSerializable
import kubescala.certificates.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object CertificatesApi:
  def apply(baseUrl: String = "http://localhost"): CertificatesApi[
    kubescala.certificates.Authorization.NoAuthorization.type
  ] = CertificatesApi(
    baseUrl,
    kubescala.certificates.Authorization.NoAuthorization
  )
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): CertificatesApi[kubescala.certificates.Authorization.BasicAuth] =
    CertificatesApi(
      baseUrl,
      kubescala.certificates.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): CertificatesApi[kubescala.certificates.Authorization.ApiKey] =
    CertificatesApi(
      baseUrl,
      kubescala.certificates.Authorization.ApiKey(apiKey)
    )

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): CertificatesApi[kubescala.certificates.Authorization.BearerToken] =
    CertificatesApi(
      baseUrl,
      kubescala.certificates.Authorization.BearerToken(token)
    )

case class CertificatesApi[
    Auth <: kubescala.certificates.Authorization
] private (baseUrl: String, authConfig: kubescala.certificates.Authorization):
  def withBasicAuth(
      username: String,
      password: String
  ): CertificatesApi[kubescala.certificates.Authorization.BasicAuth] =
    copy(authConfig =
      kubescala.certificates.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      apiKey: String
  ): CertificatesApi[kubescala.certificates.Authorization.ApiKey] =
    copy(authConfig = kubescala.certificates.Authorization.ApiKey(apiKey))

  def withNoAuth: CertificatesApi[
    kubescala.certificates.Authorization.NoAuthorization.type
  ] =
    copy(authConfig = kubescala.certificates.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): CertificatesApi[kubescala.certificates.Authorization.BearerToken] =
    copy(authConfig = kubescala.certificates.Authorization.BearerToken(token))

  /** get information of a group
    *
    * Expected answers: code 200 : APIGroup (OK) code 401 : (Unauthorized)
    */
  def getCertificatesAPIGroup
      : sttp.client4.Request[Either[ResponseException[String], APIGroup]] =
    val requestURL =
      uri"$baseUrl/apis/certificates.k8s.io/"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .response(asJson[APIGroup])

end CertificatesApi
