/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.autoscaling.v1

import kubescala.autoscaling.v1.models.*
import java.time.*
import com.github.plokhotnyuk.jsoniter_scala.macros.*
import com.github.plokhotnyuk.jsoniter_scala.core.*
import com.github.plokhotnyuk.jsoniter_scala.circe.JsoniterScalaCodec.*

object JsonSupport extends AdditionalTypeSerializers:
  inline given CodecMakerConfig = CodecMakerConfig.withAllowRecursiveTypes(true)

  inline def deriveJsonCodec[A](using
      inline config: CodecMakerConfig
  ): JsonValueCodec[A] =
    JsonCodecMaker.make(config)

  given statusCodec: JsonValueCodec[Status] = deriveJsonCodec
  given aPIResourceListCodec: JsonValueCodec[APIResourceList] = deriveJsonCodec
  given horizontalPodAutoscalerListCodec
      : JsonValueCodec[HorizontalPodAutoscalerList] = deriveJsonCodec
  given deleteOptionsCodec: JsonValueCodec[DeleteOptions] = deriveJsonCodec
  given watchEventCodec: JsonValueCodec[WatchEvent] = deriveJsonCodec
  given horizontalPodAutoscalerCodec: JsonValueCodec[HorizontalPodAutoscaler] =
    deriveJsonCodec
