/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.networking.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** IngressServiceBackend references a Kubernetes Service as a Backend.
  */
case class IngressServiceBackend(
    /* name is the referenced service. The service must exist in the same namespace as the Ingress object. */
    @named("name") name: String,
    /* port of the referenced service. A port name or port number is required for a IngressServiceBackend. */
    @named("port") port: Option[ServiceBackendPort] = scala.None
)
