/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.networking.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** IngressLoadBalancerStatus represents the status of a load-balancer.
  */
case class IngressLoadBalancerStatus(
    /* ingress is a list containing ingress points for the load-balancer. */
    @named("ingress") ingress: Option[Seq[IngressLoadBalancerIngress]] =
      scala.None
)
