/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.networking.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** IngressStatus describe the current state of the Ingress.
  */
case class IngressStatus(
    /* loadBalancer contains the current status of the load-balancer. */
    @named("loadBalancer") loadBalancer: Option[IngressLoadBalancerStatus] =
      scala.None
)
