/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.networking.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** IngressBackend describes all endpoints for a given service and port.
  */
case class IngressBackend(
    /* resource is an ObjectRef to another Kubernetes resource in the namespace of the Ingress object. If resource is specified, a service.Name and service.Port must not be specified. This is a mutually exclusive setting with \"Service\". */
    @named("resource") resource: Option[TypedLocalObjectReference] = scala.None,
    /* service references a service as a backend. This is a mutually exclusive setting with \"Resource\". */
    @named("service") service: Option[IngressServiceBackend] = scala.None
)
