/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.networking.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** IPAddress represents a single IP of a single IP Family. The object is
  * designed to be used by APIs that operate on IP addresses. The object is used
  * by the Service core API for allocation of IP addresses. An IP address can be
  * represented in different formats, to guarantee the uniqueness of the IP, the
  * name of the object is the IP address in canonical format, four decimal
  * digits separated by dots suppressing leading zeros for IPv4 and the
  * representation defined by RFC 5952 for IPv6. Valid: 192.168.1.5 or
  * 2001:db8::1 or 2001:db8:aaaa:bbbb:cccc:dddd:eeee:1 Invalid: 10.01.2.3 or
  * 2001:db8:0:0:0::1
  */
case class IPAddress(
    /* APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
    @named("apiVersion") apiVersion: Option[String] = scala.None,
    /* Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    @named("kind") kind: Option[String] = scala.None,
    /* Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata */
    @named("metadata") metadata: Option[ObjectMeta] = scala.None,
    /* spec is the desired state of the IPAddress. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status */
    @named("spec") spec: Option[IPAddressSpec] = scala.None
)
