/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.networking.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** IPBlock describes a particular CIDR (Ex.
  * \"192.168.1.0/24\",\"2001:db8::/64\") that is allowed to the pods matched by
  * a NetworkPolicySpec's podSelector. The except entry describes CIDRs that
  * should not be included within this rule.
  */
case class IPBlock(
    /* cidr is a string representing the IPBlock Valid examples are \"192.168.1.0/24\" or \"2001:db8::/64\" */
    @named("cidr") cidr: String,
    /* except is a slice of CIDRs that should not be included within an IPBlock Valid examples are \"192.168.1.0/24\" or \"2001:db8::/64\" Except values will be rejected if they are outside the cidr range */
    @named("except") except: Option[Seq[String]] = scala.None
)
