/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.networking.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** NetworkPolicyPeer describes a peer to allow traffic to/from. Only certain
  * combinations of fields are allowed
  */
case class NetworkPolicyPeer(
    /* ipBlock defines policy on a particular IPBlock. If this field is set then neither of the other fields can be. */
    @named("ipBlock") ipBlock: Option[IPBlock] = scala.None,
    /* namespaceSelector selects namespaces using cluster-scoped labels. This field follows standard label selector semantics; if present but empty, it selects all namespaces.  If podSelector is also set, then the NetworkPolicyPeer as a whole selects the pods matching podSelector in the namespaces selected by namespaceSelector. Otherwise it selects all pods in the namespaces selected by namespaceSelector. */
    @named("namespaceSelector") namespaceSelector: Option[LabelSelector] =
      scala.None,
    /* podSelector is a label selector which selects pods. This field follows standard label selector semantics; if present but empty, it selects all pods.  If namespaceSelector is also set, then the NetworkPolicyPeer as a whole selects the pods matching podSelector in the Namespaces selected by NamespaceSelector. Otherwise it selects the pods matching podSelector in the policy's own namespace. */
    @named("podSelector") podSelector: Option[LabelSelector] = scala.None
)
