/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.networking.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** ServiceBackendPort is the service port being referenced.
  */
case class ServiceBackendPort(
    /* name is the name of the port on the Service. This is a mutually exclusive setting with \"Number\". */
    @named("name") name: Option[String] = scala.None,
    /* number is the numerical port number (e.g. 80) on the Service. This is a mutually exclusive setting with \"Name\". */
    @named("number") number: Option[Int] = scala.None
)
