/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.storage.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** AzureDisk represents an Azure Data Disk mount on the host and bind mount to
  * the pod.
  */
case class AzureDiskVolumeSource(
    /* diskName is the Name of the data disk in the blob storage */
    @named("diskName") diskName: String,
    /* diskURI is the URI of data disk in the blob storage */
    @named("diskURI") diskURI: String,
    /* cachingMode is the Host Caching mode: None, Read Only, Read Write.  Possible enum values:  - `\"None\"`  - `\"ReadOnly\"`  - `\"ReadWrite\"` */
    @named("cachingMode") cachingMode: Option[
      AzureDiskVolumeSourceEnums.CachingMode
    ] = scala.None,
    /* fsType is Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified. */
    @named("fsType") fsType: Option[String] = scala.None,
    /* kind expected values are Shared: multiple blob disks per storage account  Dedicated: single blob disk per storage account  Managed: azure managed data disk (only in managed availability set). defaults to shared  Possible enum values:  - `\"Dedicated\"`  - `\"Managed\"`  - `\"Shared\"` */
    @named("kind") kind: Option[AzureDiskVolumeSourceEnums.Kind] = scala.None,
    /* readOnly Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts. */
    @named("readOnly") readOnly: Option[Boolean] = scala.None
)

object AzureDiskVolumeSourceEnums:
  enum CachingMode:
    case `None`
    case `ReadOnly`
    case `ReadWrite`

  object CachingMode:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given cachingModeCodec: JsonValueCodec[CachingMode] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "None"      => "None"
            case "ReadOnly"  => "ReadOnly"
            case "ReadWrite" => "ReadWrite"
        }
        .withDiscriminatorFieldName(scala.None)
    }
  enum Kind:
    case `Dedicated`
    case `Managed`
    case `Shared`

  object Kind:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given kindCodec: JsonValueCodec[Kind] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "Dedicated" => "Dedicated"
            case "Managed"   => "Managed"
            case "Shared"    => "Shared"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end AzureDiskVolumeSourceEnums
