/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.storage.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** AzureFile represents an Azure File Service mount on the host and bind mount
  * to the pod.
  */
case class AzureFilePersistentVolumeSource(
    /* secretName is the name of secret that contains Azure Storage Account Name and Key */
    @named("secretName") secretName: String,
    /* shareName is the azure Share Name */
    @named("shareName") shareName: String,
    /* readOnly defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts. */
    @named("readOnly") readOnly: Option[Boolean] = scala.None,
    /* secretNamespace is the namespace of the secret that contains Azure Storage Account Name and Key default is the same as the Pod */
    @named("secretNamespace") secretNamespace: Option[String] = scala.None
)
