/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.storage.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Represents a Ceph Filesystem mount that lasts the lifetime of a pod Cephfs
  * volumes do not support ownership management or SELinux relabeling.
  */
case class CephFSPersistentVolumeSource(
    /* monitors is Required: Monitors is a collection of Ceph monitors More info: https://examples.k8s.io/volumes/cephfs/README.md#how-to-use-it */
    @named("monitors") monitors: Seq[String],
    /* path is Optional: Used as the mounted root, rather than the full Ceph tree, default is / */
    @named("path") path: Option[String] = scala.None,
    /* readOnly is Optional: Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts. More info: https://examples.k8s.io/volumes/cephfs/README.md#how-to-use-it */
    @named("readOnly") readOnly: Option[Boolean] = scala.None,
    /* secretFile is Optional: SecretFile is the path to key ring for User, default is /etc/ceph/user.secret More info: https://examples.k8s.io/volumes/cephfs/README.md#how-to-use-it */
    @named("secretFile") secretFile: Option[String] = scala.None,
    /* secretRef is Optional: SecretRef is reference to the authentication secret for User, default is empty. More info: https://examples.k8s.io/volumes/cephfs/README.md#how-to-use-it */
    @named("secretRef") secretRef: Option[SecretReference] = scala.None,
    /* user is Optional: User is the rados user name, default is admin More info: https://examples.k8s.io/volumes/cephfs/README.md#how-to-use-it */
    @named("user") user: Option[String] = scala.None
)
