/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.storage.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Represents a cinder volume resource in Openstack. A Cinder volume must exist
  * before mounting to a container. The volume must also be in the same region
  * as the kubelet. Cinder volumes support ownership management and SELinux
  * relabeling.
  */
case class CinderPersistentVolumeSource(
    /* volumeID used to identify the volume in cinder. More info: https://examples.k8s.io/mysql-cinder-pd/README.md */
    @named("volumeID") volumeID: String,
    /* fsType Filesystem type to mount. Must be a filesystem type supported by the host operating system. Examples: \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified. More info: https://examples.k8s.io/mysql-cinder-pd/README.md */
    @named("fsType") fsType: Option[String] = scala.None,
    /* readOnly is Optional: Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts. More info: https://examples.k8s.io/mysql-cinder-pd/README.md */
    @named("readOnly") readOnly: Option[Boolean] = scala.None,
    /* secretRef is Optional: points to a secret object containing parameters used to connect to OpenStack. */
    @named("secretRef") secretRef: Option[SecretReference] = scala.None
)
