/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.storage.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** CSINode holds information about all CSI drivers installed on a node. CSI
  * drivers do not need to create the CSINode object directly. As long as they
  * use the node-driver-registrar sidecar container, the kubelet will
  * automatically populate the CSINode object for the CSI driver as part of
  * kubelet plugin registration. CSINode has the same name as a node. If the
  * object is missing, it means either there are no CSI Drivers available on the
  * node, or the Kubelet version is low enough that it doesn't create this
  * object. CSINode has an OwnerReference that points to the corresponding node
  * object.
  */
case class CSINode(
    /* spec is the specification of CSINode */
    @named("spec") spec: CSINodeSpec,
    /* APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
    @named("apiVersion") apiVersion: Option[String] = scala.None,
    /* Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    @named("kind") kind: Option[String] = scala.None,
    /* Standard object's metadata. metadata.name must be the Kubernetes node name. */
    @named("metadata") metadata: Option[ObjectMeta] = scala.None
)
