/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.storage.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Represents storage that is managed by an external CSI volume driver
  */
case class CSIPersistentVolumeSource(
    /* driver is the name of the driver to use for this volume. Required. */
    @named("driver") driver: String,
    /* volumeHandle is the unique volume name returned by the CSI volume plugin’s CreateVolume to refer to the volume on all subsequent calls. Required. */
    @named("volumeHandle") volumeHandle: String,
    /* controllerExpandSecretRef is a reference to the secret object containing sensitive information to pass to the CSI driver to complete the CSI ControllerExpandVolume call. This field is optional, and may be empty if no secret is required. If the secret object contains more than one secret, all secrets are passed. */
    @named("controllerExpandSecretRef") controllerExpandSecretRef: Option[
      SecretReference
    ] = scala.None,
    /* controllerPublishSecretRef is a reference to the secret object containing sensitive information to pass to the CSI driver to complete the CSI ControllerPublishVolume and ControllerUnpublishVolume calls. This field is optional, and may be empty if no secret is required. If the secret object contains more than one secret, all secrets are passed. */
    @named("controllerPublishSecretRef") controllerPublishSecretRef: Option[
      SecretReference
    ] = scala.None,
    /* fsType to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". */
    @named("fsType") fsType: Option[String] = scala.None,
    /* nodeExpandSecretRef is a reference to the secret object containing sensitive information to pass to the CSI driver to complete the CSI NodeExpandVolume call. This field is optional, may be omitted if no secret is required. If the secret object contains more than one secret, all secrets are passed. */
    @named("nodeExpandSecretRef") nodeExpandSecretRef: Option[SecretReference] =
      scala.None,
    /* nodePublishSecretRef is a reference to the secret object containing sensitive information to pass to the CSI driver to complete the CSI NodePublishVolume and NodeUnpublishVolume calls. This field is optional, and may be empty if no secret is required. If the secret object contains more than one secret, all secrets are passed. */
    @named("nodePublishSecretRef") nodePublishSecretRef: Option[
      SecretReference
    ] = scala.None,
    /* nodeStageSecretRef is a reference to the secret object containing sensitive information to pass to the CSI driver to complete the CSI NodeStageVolume and NodeStageVolume and NodeUnstageVolume calls. This field is optional, and may be empty if no secret is required. If the secret object contains more than one secret, all secrets are passed. */
    @named("nodeStageSecretRef") nodeStageSecretRef: Option[SecretReference] =
      scala.None,
    /* readOnly value to pass to ControllerPublishVolumeRequest. Defaults to false (read/write). */
    @named("readOnly") readOnly: Option[Boolean] = scala.None,
    /* volumeAttributes of the volume to publish. */
    @named("volumeAttributes") volumeAttributes: Option[Map[String, String]] =
      scala.None
)
