/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.storage.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Represents a host path mapped into a pod. Host path volumes do not support
  * ownership management or SELinux relabeling.
  */
case class HostPathVolumeSource(
    /* path of the directory on the host. If the path is a symlink, it will follow the link to the real path. More info: https://kubernetes.io/docs/concepts/storage/volumes#hostpath */
    @named("path") path: String,
    /* type for HostPath Volume Defaults to \"\" More info: https://kubernetes.io/docs/concepts/storage/volumes#hostpath  Possible enum values:  - `\"\"` For backwards compatible, leave it empty if unset  - `\"BlockDevice\"` A block device must exist at the given path  - `\"CharDevice\"` A character device must exist at the given path  - `\"Directory\"` A directory must exist at the given path  - `\"DirectoryOrCreate\"` If nothing exists at the given path, an empty directory will be created there as needed with file mode 0755, having the same group and ownership with Kubelet.  - `\"File\"` A file must exist at the given path  - `\"FileOrCreate\"` If nothing exists at the given path, an empty file will be created there as needed with file mode 0644, having the same group and ownership with Kubelet.  - `\"Socket\"` A UNIX socket must exist at the given path */
    @named("type") `type`: Option[HostPathVolumeSourceEnums.Type] = scala.None
)

object HostPathVolumeSourceEnums:
  enum Type:
    case NotPresent
    case `BlockDevice`
    case `CharDevice`
    case `Directory`
    case `DirectoryOrCreate`
    case `File`
    case `FileOrCreate`
    case `Socket`

  object Type:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given typeCodec: JsonValueCodec[Type] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "NotPresent"        => ""
            case "BlockDevice"       => "BlockDevice"
            case "CharDevice"        => "CharDevice"
            case "Directory"         => "Directory"
            case "DirectoryOrCreate" => "DirectoryOrCreate"
            case "File"              => "File"
            case "FileOrCreate"      => "FileOrCreate"
            case "Socket"            => "Socket"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end HostPathVolumeSourceEnums
