/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.storage.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** ISCSIPersistentVolumeSource represents an ISCSI disk. ISCSI volumes can only
  * be mounted as read/write once. ISCSI volumes support ownership management
  * and SELinux relabeling.
  */
case class ISCSIPersistentVolumeSource(
    /* iqn is Target iSCSI Qualified Name. */
    @named("iqn") iqn: String,
    /* lun is iSCSI Target Lun number. */
    @named("lun") lun: Int,
    /* targetPortal is iSCSI Target Portal. The Portal is either an IP or ip_addr:port if the port is other than default (typically TCP ports 860 and 3260). */
    @named("targetPortal") targetPortal: String,
    /* chapAuthDiscovery defines whether support iSCSI Discovery CHAP authentication */
    @named("chapAuthDiscovery") chapAuthDiscovery: Option[Boolean] = scala.None,
    /* chapAuthSession defines whether support iSCSI Session CHAP authentication */
    @named("chapAuthSession") chapAuthSession: Option[Boolean] = scala.None,
    /* fsType is the filesystem type of the volume that you want to mount. Tip: Ensure that the filesystem type is supported by the host operating system. Examples: \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified. More info: https://kubernetes.io/docs/concepts/storage/volumes#iscsi */
    @named("fsType") fsType: Option[String] = scala.None,
    /* initiatorName is the custom iSCSI Initiator Name. If initiatorName is specified with iscsiInterface simultaneously, new iSCSI interface <target portal>:<volume name> will be created for the connection. */
    @named("initiatorName") initiatorName: Option[String] = scala.None,
    /* iscsiInterface is the interface Name that uses an iSCSI transport. Defaults to 'default' (tcp). */
    @named("iscsiInterface") iscsiInterface: Option[String] = scala.None,
    /* portals is the iSCSI Target Portal List. The Portal is either an IP or ip_addr:port if the port is other than default (typically TCP ports 860 and 3260). */
    @named("portals") portals: Option[Seq[String]] = scala.None,
    /* readOnly here will force the ReadOnly setting in VolumeMounts. Defaults to false. */
    @named("readOnly") readOnly: Option[Boolean] = scala.None,
    /* secretRef is the CHAP Secret for iSCSI target and initiator authentication */
    @named("secretRef") secretRef: Option[SecretReference] = scala.None
)
