/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.storage.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** A node selector requirement is a selector that contains values, a key, and
  * an operator that relates the key and values.
  */
case class NodeSelectorRequirement(
    /* The label key that the selector applies to. */
    @named("key") key: String,
    /* Represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist. Gt, and Lt.  Possible enum values:  - `\"DoesNotExist\"`  - `\"Exists\"`  - `\"Gt\"`  - `\"In\"`  - `\"Lt\"`  - `\"NotIn\"` */
    @named("operator") operator: NodeSelectorRequirementEnums.Operator,
    /* An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. If the operator is Gt or Lt, the values array must have a single element, which will be interpreted as an integer. This array is replaced during a strategic merge patch. */
    @named("values") values: Option[Seq[String]] = scala.None
)

object NodeSelectorRequirementEnums:
  enum Operator:
    case `DoesNotExist`
    case `Exists`
    case `Gt`
    case `In`
    case `Lt`
    case `NotIn`

  object Operator:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given operatorCodec: JsonValueCodec[Operator] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "DoesNotExist" => "DoesNotExist"
            case "Exists"       => "Exists"
            case "Gt"           => "Gt"
            case "In"           => "In"
            case "Lt"           => "Lt"
            case "NotIn"        => "NotIn"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end NodeSelectorRequirementEnums
