/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.storage.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** PersistentVolumeSpec is the specification of a persistent volume.
  */
case class PersistentVolumeSpec(
    /* accessModes contains all ways the volume can be mounted. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes */
    @named("accessModes") accessModes: Option[
      Seq[PersistentVolumeSpecEnums.AccessModes]
    ] = scala.None,
    /* awsElasticBlockStore represents an AWS Disk resource that is attached to a kubelet's host machine and then exposed to the pod. Deprecated: AWSElasticBlockStore is deprecated. All operations for the in-tree awsElasticBlockStore type are redirected to the ebs.csi.aws.com CSI driver. More info: https://kubernetes.io/docs/concepts/storage/volumes#awselasticblockstore */
    @named("awsElasticBlockStore") awsElasticBlockStore: Option[
      AWSElasticBlockStoreVolumeSource
    ] = scala.None,
    /* azureDisk represents an Azure Data Disk mount on the host and bind mount to the pod. Deprecated: AzureDisk is deprecated. All operations for the in-tree azureDisk type are redirected to the disk.csi.azure.com CSI driver. */
    @named("azureDisk") azureDisk: Option[AzureDiskVolumeSource] = scala.None,
    /* azureFile represents an Azure File Service mount on the host and bind mount to the pod. Deprecated: AzureFile is deprecated. All operations for the in-tree azureFile type are redirected to the file.csi.azure.com CSI driver. */
    @named("azureFile") azureFile: Option[AzureFilePersistentVolumeSource] =
      scala.None,
    /* capacity is the description of the persistent volume's resources and capacity. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#capacity */
    @named("capacity") capacity: Option[Map[String, Quantity]] = scala.None,
    /* cephFS represents a Ceph FS mount on the host that shares a pod's lifetime. Deprecated: CephFS is deprecated and the in-tree cephfs type is no longer supported. */
    @named("cephfs") cephfs: Option[CephFSPersistentVolumeSource] = scala.None,
    /* cinder represents a cinder volume attached and mounted on kubelets host machine. Deprecated: Cinder is deprecated. All operations for the in-tree cinder type are redirected to the cinder.csi.openstack.org CSI driver. More info: https://examples.k8s.io/mysql-cinder-pd/README.md */
    @named("cinder") cinder: Option[CinderPersistentVolumeSource] = scala.None,
    /* claimRef is part of a bi-directional binding between PersistentVolume and PersistentVolumeClaim. Expected to be non-nil when bound. claim.VolumeName is the authoritative bind between PV and PVC. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#binding */
    @named("claimRef") claimRef: Option[ObjectReference] = scala.None,
    /* csi represents storage that is handled by an external CSI driver. */
    @named("csi") csi: Option[CSIPersistentVolumeSource] = scala.None,
    /* fc represents a Fibre Channel resource that is attached to a kubelet's host machine and then exposed to the pod. */
    @named("fc") fc: Option[FCVolumeSource] = scala.None,
    /* flexVolume represents a generic volume resource that is provisioned/attached using an exec based plugin. Deprecated: FlexVolume is deprecated. Consider using a CSIDriver instead. */
    @named("flexVolume") flexVolume: Option[FlexPersistentVolumeSource] =
      scala.None,
    /* flocker represents a Flocker volume attached to a kubelet's host machine and exposed to the pod for its usage. This depends on the Flocker control service being running. Deprecated: Flocker is deprecated and the in-tree flocker type is no longer supported. */
    @named("flocker") flocker: Option[FlockerVolumeSource] = scala.None,
    /* gcePersistentDisk represents a GCE Disk resource that is attached to a kubelet's host machine and then exposed to the pod. Provisioned by an admin. Deprecated: GCEPersistentDisk is deprecated. All operations for the in-tree gcePersistentDisk type are redirected to the pd.csi.storage.gke.io CSI driver. More info: https://kubernetes.io/docs/concepts/storage/volumes#gcepersistentdisk */
    @named("gcePersistentDisk") gcePersistentDisk: Option[
      GCEPersistentDiskVolumeSource
    ] = scala.None,
    /* glusterfs represents a Glusterfs volume that is attached to a host and exposed to the pod. Provisioned by an admin. Deprecated: Glusterfs is deprecated and the in-tree glusterfs type is no longer supported. More info: https://examples.k8s.io/volumes/glusterfs/README.md */
    @named("glusterfs") glusterfs: Option[GlusterfsPersistentVolumeSource] =
      scala.None,
    /* hostPath represents a directory on the host. Provisioned by a developer or tester. This is useful for single-node development and testing only! On-host storage is not supported in any way and WILL NOT WORK in a multi-node cluster. More info: https://kubernetes.io/docs/concepts/storage/volumes#hostpath */
    @named("hostPath") hostPath: Option[HostPathVolumeSource] = scala.None,
    /* iscsi represents an ISCSI Disk resource that is attached to a kubelet's host machine and then exposed to the pod. Provisioned by an admin. */
    @named("iscsi") iscsi: Option[ISCSIPersistentVolumeSource] = scala.None,
    /* local represents directly-attached storage with node affinity */
    @named("local") local: Option[LocalVolumeSource] = scala.None,
    /* mountOptions is the list of mount options, e.g. [\"ro\", \"soft\"]. Not validated - mount will simply fail if one is invalid. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#mount-options */
    @named("mountOptions") mountOptions: Option[Seq[String]] = scala.None,
    /* nfs represents an NFS mount on the host. Provisioned by an admin. More info: https://kubernetes.io/docs/concepts/storage/volumes#nfs */
    @named("nfs") nfs: Option[NFSVolumeSource] = scala.None,
    /* nodeAffinity defines constraints that limit what nodes this volume can be accessed from. This field influences the scheduling of pods that use this volume. */
    @named("nodeAffinity") nodeAffinity: Option[VolumeNodeAffinity] =
      scala.None,
    /* persistentVolumeReclaimPolicy defines what happens to a persistent volume when released from its claim. Valid options are Retain (default for manually created PersistentVolumes), Delete (default for dynamically provisioned PersistentVolumes), and Recycle (deprecated). Recycle must be supported by the volume plugin underlying this PersistentVolume. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#reclaiming  Possible enum values:  - `\"Delete\"` means the volume will be deleted from Kubernetes on release from its claim. The volume plugin must support Deletion.  - `\"Recycle\"` means the volume will be recycled back into the pool of unbound persistent volumes on release from its claim. The volume plugin must support Recycling.  - `\"Retain\"` means the volume will be left in its current phase (Released) for manual reclamation by the administrator. The default policy is Retain. */
    @named(
      "persistentVolumeReclaimPolicy"
    ) persistentVolumeReclaimPolicy: Option[
      PersistentVolumeSpecEnums.PersistentVolumeReclaimPolicy
    ] = scala.None,
    /* photonPersistentDisk represents a PhotonController persistent disk attached and mounted on kubelets host machine. Deprecated: PhotonPersistentDisk is deprecated and the in-tree photonPersistentDisk type is no longer supported. */
    @named("photonPersistentDisk") photonPersistentDisk: Option[
      PhotonPersistentDiskVolumeSource
    ] = scala.None,
    /* portworxVolume represents a portworx volume attached and mounted on kubelets host machine. Deprecated: PortworxVolume is deprecated. All operations for the in-tree portworxVolume type are redirected to the pxd.portworx.com CSI driver when the CSIMigrationPortworx feature-gate is on. */
    @named("portworxVolume") portworxVolume: Option[PortworxVolumeSource] =
      scala.None,
    /* quobyte represents a Quobyte mount on the host that shares a pod's lifetime. Deprecated: Quobyte is deprecated and the in-tree quobyte type is no longer supported. */
    @named("quobyte") quobyte: Option[QuobyteVolumeSource] = scala.None,
    /* rbd represents a Rados Block Device mount on the host that shares a pod's lifetime. Deprecated: RBD is deprecated and the in-tree rbd type is no longer supported. More info: https://examples.k8s.io/volumes/rbd/README.md */
    @named("rbd") rbd: Option[RBDPersistentVolumeSource] = scala.None,
    /* scaleIO represents a ScaleIO persistent volume attached and mounted on Kubernetes nodes. Deprecated: ScaleIO is deprecated and the in-tree scaleIO type is no longer supported. */
    @named("scaleIO") scaleIO: Option[ScaleIOPersistentVolumeSource] =
      scala.None,
    /* storageClassName is the name of StorageClass to which this persistent volume belongs. Empty value means that this volume does not belong to any StorageClass. */
    @named("storageClassName") storageClassName: Option[String] = scala.None,
    /* storageOS represents a StorageOS volume that is attached to the kubelet's host machine and mounted into the pod. Deprecated: StorageOS is deprecated and the in-tree storageos type is no longer supported. More info: https://examples.k8s.io/volumes/storageos/README.md */
    @named("storageos") storageos: Option[StorageOSPersistentVolumeSource] =
      scala.None,
    /* Name of VolumeAttributesClass to which this persistent volume belongs. Empty value is not allowed. When this field is not set, it indicates that this volume does not belong to any VolumeAttributesClass. This field is mutable and can be changed by the CSI driver after a volume has been updated successfully to a new class. For an unbound PersistentVolume, the volumeAttributesClassName will be matched with unbound PersistentVolumeClaims during the binding process. */
    @named("volumeAttributesClassName") volumeAttributesClassName: Option[
      String
    ] = scala.None,
    /* volumeMode defines if a volume is intended to be used with a formatted filesystem or to remain in raw block state. Value of Filesystem is implied when not included in spec.  Possible enum values:  - `\"Block\"` means the volume will not be formatted with a filesystem and will remain a raw block device.  - `\"Filesystem\"` means the volume will be or is formatted with a filesystem. */
    @named("volumeMode") volumeMode: Option[
      PersistentVolumeSpecEnums.VolumeMode
    ] = scala.None,
    /* vsphereVolume represents a vSphere volume attached and mounted on kubelets host machine. Deprecated: VsphereVolume is deprecated. All operations for the in-tree vsphereVolume type are redirected to the csi.vsphere.vmware.com CSI driver. */
    @named("vsphereVolume") vsphereVolume: Option[
      VsphereVirtualDiskVolumeSource
    ] = scala.None
)

object PersistentVolumeSpecEnums:
  enum AccessModes:
    case `ReadOnlyMany`
    case `ReadWriteMany`
    case `ReadWriteOnce`
    case `ReadWriteOncePod`

  object AccessModes:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
  enum PersistentVolumeReclaimPolicy:
    case `Delete`
    case `Recycle`
    case `Retain`

  object PersistentVolumeReclaimPolicy:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given persistentVolumeReclaimPolicyCodec
        : JsonValueCodec[PersistentVolumeReclaimPolicy] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "Delete"  => "Delete"
            case "Recycle" => "Recycle"
            case "Retain"  => "Retain"
        }
        .withDiscriminatorFieldName(scala.None)
    }
  enum VolumeMode:
    case `Block`
    case `Filesystem`

  object VolumeMode:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given volumeModeCodec: JsonValueCodec[VolumeMode] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "Block"      => "Block"
            case "Filesystem" => "Filesystem"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end PersistentVolumeSpecEnums
