/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.storage.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** PortworxVolumeSource represents a Portworx volume resource.
  */
case class PortworxVolumeSource(
    /* volumeID uniquely identifies a Portworx volume */
    @named("volumeID") volumeID: String,
    /* fSType represents the filesystem type to mount Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\". Implicitly inferred to be \"ext4\" if unspecified. */
    @named("fsType") fsType: Option[String] = scala.None,
    /* readOnly defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts. */
    @named("readOnly") readOnly: Option[Boolean] = scala.None
)
