/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.storage.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Represents a Rados Block Device mount that lasts the lifetime of a pod. RBD
  * volumes support ownership management and SELinux relabeling.
  */
case class RBDPersistentVolumeSource(
    /* image is the rados image name. More info: https://examples.k8s.io/volumes/rbd/README.md#how-to-use-it */
    @named("image") image: String,
    /* monitors is a collection of Ceph monitors. More info: https://examples.k8s.io/volumes/rbd/README.md#how-to-use-it */
    @named("monitors") monitors: Seq[String],
    /* fsType is the filesystem type of the volume that you want to mount. Tip: Ensure that the filesystem type is supported by the host operating system. Examples: \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified. More info: https://kubernetes.io/docs/concepts/storage/volumes#rbd */
    @named("fsType") fsType: Option[String] = scala.None,
    /* keyring is the path to key ring for RBDUser. Default is /etc/ceph/keyring. More info: https://examples.k8s.io/volumes/rbd/README.md#how-to-use-it */
    @named("keyring") keyring: Option[String] = scala.None,
    /* pool is the rados pool name. Default is rbd. More info: https://examples.k8s.io/volumes/rbd/README.md#how-to-use-it */
    @named("pool") pool: Option[String] = scala.None,
    /* readOnly here will force the ReadOnly setting in VolumeMounts. Defaults to false. More info: https://examples.k8s.io/volumes/rbd/README.md#how-to-use-it */
    @named("readOnly") readOnly: Option[Boolean] = scala.None,
    /* secretRef is name of the authentication secret for RBDUser. If provided overrides keyring. Default is nil. More info: https://examples.k8s.io/volumes/rbd/README.md#how-to-use-it */
    @named("secretRef") secretRef: Option[SecretReference] = scala.None,
    /* user is the rados user name. Default is admin. More info: https://examples.k8s.io/volumes/rbd/README.md#how-to-use-it */
    @named("user") user: Option[String] = scala.None
)
