/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.storage.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** SecretReference represents a Secret Reference. It has enough information to
  * retrieve secret in any namespace
  */
case class SecretReference(
    /* name is unique within a namespace to reference a secret resource. */
    @named("name") name: Option[String] = scala.None,
    /* namespace defines the space within which the secret name must be unique. */
    @named("namespace") namespace: Option[String] = scala.None
)
