/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.storage.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** StatusDetails is a set of additional properties that MAY be set by the
  * server to provide additional information about a response. The Reason field
  * of a Status object defines what attributes will be set. Clients must ignore
  * fields that do not match the defined type of each attribute, and should
  * assume that any attribute may be empty, invalid, or under defined.
  */
case class StatusDetails(
    /* The Causes array includes more details associated with the StatusReason failure. Not all StatusReasons may provide detailed causes. */
    @named("causes") causes: Option[Seq[StatusCause]] = scala.None,
    /* The group attribute of the resource associated with the status StatusReason. */
    @named("group") group: Option[String] = scala.None,
    /* The kind attribute of the resource associated with the status StatusReason. On some operations may differ from the requested resource Kind. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    @named("kind") kind: Option[String] = scala.None,
    /* The name attribute of the resource associated with the status StatusReason (when there is a single name which can be described). */
    @named("name") name: Option[String] = scala.None,
    /* If specified, the time in seconds before the operation should be retried. Some errors may indicate the client must take an alternate action - for those errors this field may indicate how long to wait before taking the alternate action. */
    @named("retryAfterSeconds") retryAfterSeconds: Option[Int] = scala.None,
    /* UID of the resource. (when there is a single resource which can be described). More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids */
    @named("uid") uid: Option[String] = scala.None
)
