/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.storage.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** StorageClass describes the parameters for a class of storage for which
  * PersistentVolumes can be dynamically provisioned. StorageClasses are
  * non-namespaced; the name of the storage class according to etcd is in
  * ObjectMeta.Name.
  */
case class StorageClass(
    /* provisioner indicates the type of the provisioner. */
    @named("provisioner") provisioner: String,
    /* allowVolumeExpansion shows whether the storage class allow volume expand. */
    @named("allowVolumeExpansion") allowVolumeExpansion: Option[Boolean] =
      scala.None,
    /* allowedTopologies restrict the node topologies where volumes can be dynamically provisioned. Each volume plugin defines its own supported topology specifications. An empty TopologySelectorTerm list means there is no topology restriction. This field is only honored by servers that enable the VolumeScheduling feature. */
    @named("allowedTopologies") allowedTopologies: Option[
      Seq[TopologySelectorTerm]
    ] = scala.None,
    /* APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
    @named("apiVersion") apiVersion: Option[String] = scala.None,
    /* Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    @named("kind") kind: Option[String] = scala.None,
    /* Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata */
    @named("metadata") metadata: Option[ObjectMeta] = scala.None,
    /* mountOptions controls the mountOptions for dynamically provisioned PersistentVolumes of this storage class. e.g. [\"ro\", \"soft\"]. Not validated - mount of the PVs will simply fail if one is invalid. */
    @named("mountOptions") mountOptions: Option[Seq[String]] = scala.None,
    /* parameters holds the parameters for the provisioner that should create volumes of this storage class. */
    @named("parameters") parameters: Option[Map[String, String]] = scala.None,
    /* reclaimPolicy controls the reclaimPolicy for dynamically provisioned PersistentVolumes of this storage class. Defaults to Delete.  Possible enum values:  - `\"Delete\"` means the volume will be deleted from Kubernetes on release from its claim. The volume plugin must support Deletion.  - `\"Recycle\"` means the volume will be recycled back into the pool of unbound persistent volumes on release from its claim. The volume plugin must support Recycling.  - `\"Retain\"` means the volume will be left in its current phase (Released) for manual reclamation by the administrator. The default policy is Retain. */
    @named("reclaimPolicy") reclaimPolicy: Option[
      StorageClassEnums.ReclaimPolicy
    ] = scala.None,
    /* volumeBindingMode indicates how PersistentVolumeClaims should be provisioned and bound.  When unset, VolumeBindingImmediate is used. This field is only honored by servers that enable the VolumeScheduling feature.  Possible enum values:  - `\"Immediate\"` indicates that PersistentVolumeClaims should be immediately provisioned and bound. This is the default mode.  - `\"WaitForFirstConsumer\"` indicates that PersistentVolumeClaims should not be provisioned and bound until the first Pod is created that references the PeristentVolumeClaim. The volume provisioning and binding will occur during Pod scheduing. */
    @named("volumeBindingMode") volumeBindingMode: Option[
      StorageClassEnums.VolumeBindingMode
    ] = scala.None
)

object StorageClassEnums:
  enum ReclaimPolicy:
    case `Delete`
    case `Recycle`
    case `Retain`

  object ReclaimPolicy:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given reclaimPolicyCodec: JsonValueCodec[ReclaimPolicy] =
      JsonCodecMaker.make {
        CodecMakerConfig
          .withAdtLeafClassNameMapper { x =>
            JsonCodecMaker.simpleClassName(x) match
              case "Delete"  => "Delete"
              case "Recycle" => "Recycle"
              case "Retain"  => "Retain"
          }
          .withDiscriminatorFieldName(scala.None)
      }
  enum VolumeBindingMode:
    case `Immediate`
    case `WaitForFirstConsumer`

  object VolumeBindingMode:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given volumeBindingModeCodec: JsonValueCodec[VolumeBindingMode] =
      JsonCodecMaker.make {
        CodecMakerConfig
          .withAdtLeafClassNameMapper { x =>
            JsonCodecMaker.simpleClassName(x) match
              case "Immediate"            => "Immediate"
              case "WaitForFirstConsumer" => "WaitForFirstConsumer"
          }
          .withDiscriminatorFieldName(scala.None)
      }
end StorageClassEnums
