/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.storage.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** TokenRequest contains parameters of a service account token.
  */
case class TokenRequest(
    /* audience is the intended audience of the token in \"TokenRequestSpec\". It will default to the audiences of kube apiserver. */
    @named("audience") audience: String,
    /* expirationSeconds is the duration of validity of the token in \"TokenRequestSpec\". It has the same default value of \"ExpirationSeconds\" in \"TokenRequestSpec\". */
    @named("expirationSeconds") expirationSeconds: Option[Long] = scala.None
)
