/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.storage.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** VolumeNodeAffinity defines constraints that limit what nodes this volume can
  * be accessed from.
  */
case class VolumeNodeAffinity(
    /* required specifies hard node constraints that must be met. */
    @named("required") required: Option[NodeSelector] = scala.None
)
