/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.storage.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Represents a vSphere volume resource.
  */
case class VsphereVirtualDiskVolumeSource(
    /* volumePath is the path that identifies vSphere volume vmdk */
    @named("volumePath") volumePath: String,
    /* fsType is filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified. */
    @named("fsType") fsType: Option[String] = scala.None,
    /* storagePolicyID is the storage Policy Based Management (SPBM) profile ID associated with the StoragePolicyName. */
    @named("storagePolicyID") storagePolicyID: Option[String] = scala.None,
    /* storagePolicyName is the storage Policy Based Management (SPBM) profile name. */
    @named("storagePolicyName") storagePolicyName: Option[String] = scala.None
)
