/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.discovery.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** EndpointConditions represents the current condition of an endpoint.
  */
case class EndpointConditions(
    /* ready indicates that this endpoint is ready to receive traffic, according to whatever system is managing the endpoint. A nil value should be interpreted as \"true\". In general, an endpoint should be marked ready if it is serving and not terminating, though this can be overridden in some cases, such as when the associated Service has set the publishNotReadyAddresses flag. */
    @named("ready") ready: Option[Boolean] = scala.None,
    /* serving indicates that this endpoint is able to receive traffic, according to whatever system is managing the endpoint. For endpoints backed by pods, the EndpointSlice controller will mark the endpoint as serving if the pod's Ready condition is True. A nil value should be interpreted as \"true\". */
    @named("serving") serving: Option[Boolean] = scala.None,
    /* terminating indicates that this endpoint is terminating. A nil value should be interpreted as \"false\". */
    @named("terminating") terminating: Option[Boolean] = scala.None
)
