/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.discovery.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Preconditions must be fulfilled before an operation (update, delete, etc.)
  * is carried out.
  */
case class Preconditions(
    /* Specifies the target ResourceVersion */
    @named("resourceVersion") resourceVersion: Option[String] = scala.None,
    /* Specifies the target UID. */
    @named("uid") uid: Option[String] = scala.None
)
