/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kubescala.api.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * AttachedVolume describes a volume attached to a node
   */
case class AttachedVolume(
  /* DevicePath represents the device path where the volume should be available */
  @named("devicePath") devicePath: String,
  /* Name of the attached volume */
  @named("name") name: String
)

