/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kubescala.api.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * BoundObjectReference is a reference to an object that a token is bound to.
   */
case class BoundObjectReference(
  /* API version of the referent. */
  @named("apiVersion") apiVersion: Option[String] = scala.None,
  /* Kind of the referent. Valid kinds are 'Pod' and 'Secret'. */
  @named("kind") kind: Option[String] = scala.None,
  /* Name of the referent. */
  @named("name") name: Option[String] = scala.None,
  /* UID of the referent. */
  @named("uid") uid: Option[String] = scala.None
)

