/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kubescala.api.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * ContainerStateWaiting is a waiting state of a container.
   */
case class ContainerStateWaiting(
  /* Message regarding why the container is not yet running. */
  @named("message") message: Option[String] = scala.None,
  /* (brief) reason the container is not yet running. */
  @named("reason") reason: Option[String] = scala.None
)

