/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kubescala.api.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * ContainerStatus contains details for the current status of this container.
   */
case class ContainerStatus(
  /* Image is the name of container image that the container is running. The container image may not match the image used in the PodSpec, as it may have been resolved by the runtime. More info: https://kubernetes.io/docs/concepts/containers/images. */
  @named("image") image: String,
  /* ImageID is the image ID of the container's image. The image ID may not match the image ID of the image used in the PodSpec, as it may have been resolved by the runtime. */
  @named("imageID") imageID: String,
  /* Name is a DNS_LABEL representing the unique name of the container. Each container in a pod must have a unique name across all container types. Cannot be updated. */
  @named("name") name: String,
  /* Ready specifies whether the container is currently passing its readiness check. The value will change as readiness probes keep executing. If no readiness probes are specified, this field defaults to true once the container is fully started (see Started field).  The value is typically used to determine whether a container is ready to accept traffic. */
  @named("ready") ready: Boolean,
  /* RestartCount holds the number of times the container has been restarted. Kubelet makes an effort to always increment the value, but there are cases when the state may be lost due to node restarts and then the value may be reset to 0. The value is never negative. */
  @named("restartCount") restartCount: Int,
  /* AllocatedResources represents the compute resources allocated for this container by the node. Kubelet sets this value to Container.Resources.Requests upon successful pod admission and after successfully admitting desired pod resize. */
  @named("allocatedResources") allocatedResources: Option[Map[String, Quantity]] = scala.None,
  /* AllocatedResourcesStatus represents the status of various resources allocated for this Pod. */
  @named("allocatedResourcesStatus") allocatedResourcesStatus: Option[Seq[ResourceStatus]] = scala.None,
  /* ContainerID is the ID of the container in the format '<type>://<container_id>'. Where type is a container runtime identifier, returned from Version call of CRI API (for example \"containerd\"). */
  @named("containerID") containerID: Option[String] = scala.None,
  /* LastTerminationState holds the last termination state of the container to help debug container crashes and restarts. This field is not populated if the container is still running and RestartCount is 0. */
  @named("lastState") lastState: Option[ContainerState] = scala.None,
  /* Resources represents the compute resource requests and limits that have been successfully enacted on the running container after it has been started or has been successfully resized. */
  @named("resources") resources: Option[ResourceRequirements] = scala.None,
  /* Started indicates whether the container has finished its postStart lifecycle hook and passed its startup probe. Initialized as false, becomes true after startupProbe is considered successful. Resets to false when the container is restarted, or if kubelet loses state temporarily. In both cases, startup probes will run again. Is always true when no startupProbe is defined and container is running and has passed the postStart lifecycle hook. The null value must be treated the same as false. */
  @named("started") started: Option[Boolean] = scala.None,
  /* State holds details about the container's current condition. */
  @named("state") state: Option[ContainerState] = scala.None,
  /* StopSignal reports the effective stop signal for this container  Possible enum values:  - `\"SIGABRT\"`  - `\"SIGALRM\"`  - `\"SIGBUS\"`  - `\"SIGCHLD\"`  - `\"SIGCLD\"`  - `\"SIGCONT\"`  - `\"SIGFPE\"`  - `\"SIGHUP\"`  - `\"SIGILL\"`  - `\"SIGINT\"`  - `\"SIGIO\"`  - `\"SIGIOT\"`  - `\"SIGKILL\"`  - `\"SIGPIPE\"`  - `\"SIGPOLL\"`  - `\"SIGPROF\"`  - `\"SIGPWR\"`  - `\"SIGQUIT\"`  - `\"SIGRTMAX\"`  - `\"SIGRTMAX-1\"`  - `\"SIGRTMAX-10\"`  - `\"SIGRTMAX-11\"`  - `\"SIGRTMAX-12\"`  - `\"SIGRTMAX-13\"`  - `\"SIGRTMAX-14\"`  - `\"SIGRTMAX-2\"`  - `\"SIGRTMAX-3\"`  - `\"SIGRTMAX-4\"`  - `\"SIGRTMAX-5\"`  - `\"SIGRTMAX-6\"`  - `\"SIGRTMAX-7\"`  - `\"SIGRTMAX-8\"`  - `\"SIGRTMAX-9\"`  - `\"SIGRTMIN\"`  - `\"SIGRTMIN+1\"`  - `\"SIGRTMIN+10\"`  - `\"SIGRTMIN+11\"`  - `\"SIGRTMIN+12\"`  - `\"SIGRTMIN+13\"`  - `\"SIGRTMIN+14\"`  - `\"SIGRTMIN+15\"`  - `\"SIGRTMIN+2\"`  - `\"SIGRTMIN+3\"`  - `\"SIGRTMIN+4\"`  - `\"SIGRTMIN+5\"`  - `\"SIGRTMIN+6\"`  - `\"SIGRTMIN+7\"`  - `\"SIGRTMIN+8\"`  - `\"SIGRTMIN+9\"`  - `\"SIGSEGV\"`  - `\"SIGSTKFLT\"`  - `\"SIGSTOP\"`  - `\"SIGSYS\"`  - `\"SIGTERM\"`  - `\"SIGTRAP\"`  - `\"SIGTSTP\"`  - `\"SIGTTIN\"`  - `\"SIGTTOU\"`  - `\"SIGURG\"`  - `\"SIGUSR1\"`  - `\"SIGUSR2\"`  - `\"SIGVTALRM\"`  - `\"SIGWINCH\"`  - `\"SIGXCPU\"`  - `\"SIGXFSZ\"` */
  @named("stopSignal") stopSignal: Option[ContainerStatusEnums.StopSignal] = scala.None,
  /* User represents user identity information initially attached to the first process of the container */
  @named("user") user: Option[ContainerUser] = scala.None,
  /* Status of volume mounts. */
  @named("volumeMounts") volumeMounts: Option[Seq[VolumeMountStatus]] = scala.None
)

object ContainerStatusEnums:
  enum StopSignal:
    case `SIGABRT`
    case `SIGALRM`
    case `SIGBUS`
    case `SIGCHLD`
    case `SIGCLD`
    case `SIGCONT`
    case `SIGFPE`
    case `SIGHUP`
    case `SIGILL`
    case `SIGINT`
    case `SIGIO`
    case `SIGIOT`
    case `SIGKILL`
    case `SIGPIPE`
    case `SIGPOLL`
    case `SIGPROF`
    case `SIGPWR`
    case `SIGQUIT`
    case `SIGRTMAX`
    case `SIGRTMAX-1`
    case `SIGRTMAX-10`
    case `SIGRTMAX-11`
    case `SIGRTMAX-12`
    case `SIGRTMAX-13`
    case `SIGRTMAX-14`
    case `SIGRTMAX-2`
    case `SIGRTMAX-3`
    case `SIGRTMAX-4`
    case `SIGRTMAX-5`
    case `SIGRTMAX-6`
    case `SIGRTMAX-7`
    case `SIGRTMAX-8`
    case `SIGRTMAX-9`
    case `SIGRTMIN`
    case `SIGRTMIN+1`
    case `SIGRTMIN+10`
    case `SIGRTMIN+11`
    case `SIGRTMIN+12`
    case `SIGRTMIN+13`
    case `SIGRTMIN+14`
    case `SIGRTMIN+15`
    case `SIGRTMIN+2`
    case `SIGRTMIN+3`
    case `SIGRTMIN+4`
    case `SIGRTMIN+5`
    case `SIGRTMIN+6`
    case `SIGRTMIN+7`
    case `SIGRTMIN+8`
    case `SIGRTMIN+9`
    case `SIGSEGV`
    case `SIGSTKFLT`
    case `SIGSTOP`
    case `SIGSYS`
    case `SIGTERM`
    case `SIGTRAP`
    case `SIGTSTP`
    case `SIGTTIN`
    case `SIGTTOU`
    case `SIGURG`
    case `SIGUSR1`
    case `SIGUSR2`
    case `SIGVTALRM`
    case `SIGWINCH`
    case `SIGXCPU`
    case `SIGXFSZ`

  object StopSignal:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given stopSignalCodec: JsonValueCodec[StopSignal] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "SIGABRT" => "SIGABRT"
            case "SIGALRM" => "SIGALRM"
            case "SIGBUS" => "SIGBUS"
            case "SIGCHLD" => "SIGCHLD"
            case "SIGCLD" => "SIGCLD"
            case "SIGCONT" => "SIGCONT"
            case "SIGFPE" => "SIGFPE"
            case "SIGHUP" => "SIGHUP"
            case "SIGILL" => "SIGILL"
            case "SIGINT" => "SIGINT"
            case "SIGIO" => "SIGIO"
            case "SIGIOT" => "SIGIOT"
            case "SIGKILL" => "SIGKILL"
            case "SIGPIPE" => "SIGPIPE"
            case "SIGPOLL" => "SIGPOLL"
            case "SIGPROF" => "SIGPROF"
            case "SIGPWR" => "SIGPWR"
            case "SIGQUIT" => "SIGQUIT"
            case "SIGRTMAX" => "SIGRTMAX"
            case "SIGRTMAX-1" => "SIGRTMAX-1"
            case "SIGRTMAX-10" => "SIGRTMAX-10"
            case "SIGRTMAX-11" => "SIGRTMAX-11"
            case "SIGRTMAX-12" => "SIGRTMAX-12"
            case "SIGRTMAX-13" => "SIGRTMAX-13"
            case "SIGRTMAX-14" => "SIGRTMAX-14"
            case "SIGRTMAX-2" => "SIGRTMAX-2"
            case "SIGRTMAX-3" => "SIGRTMAX-3"
            case "SIGRTMAX-4" => "SIGRTMAX-4"
            case "SIGRTMAX-5" => "SIGRTMAX-5"
            case "SIGRTMAX-6" => "SIGRTMAX-6"
            case "SIGRTMAX-7" => "SIGRTMAX-7"
            case "SIGRTMAX-8" => "SIGRTMAX-8"
            case "SIGRTMAX-9" => "SIGRTMAX-9"
            case "SIGRTMIN" => "SIGRTMIN"
            case "SIGRTMIN+1" => "SIGRTMIN+1"
            case "SIGRTMIN+10" => "SIGRTMIN+10"
            case "SIGRTMIN+11" => "SIGRTMIN+11"
            case "SIGRTMIN+12" => "SIGRTMIN+12"
            case "SIGRTMIN+13" => "SIGRTMIN+13"
            case "SIGRTMIN+14" => "SIGRTMIN+14"
            case "SIGRTMIN+15" => "SIGRTMIN+15"
            case "SIGRTMIN+2" => "SIGRTMIN+2"
            case "SIGRTMIN+3" => "SIGRTMIN+3"
            case "SIGRTMIN+4" => "SIGRTMIN+4"
            case "SIGRTMIN+5" => "SIGRTMIN+5"
            case "SIGRTMIN+6" => "SIGRTMIN+6"
            case "SIGRTMIN+7" => "SIGRTMIN+7"
            case "SIGRTMIN+8" => "SIGRTMIN+8"
            case "SIGRTMIN+9" => "SIGRTMIN+9"
            case "SIGSEGV" => "SIGSEGV"
            case "SIGSTKFLT" => "SIGSTKFLT"
            case "SIGSTOP" => "SIGSTOP"
            case "SIGSYS" => "SIGSYS"
            case "SIGTERM" => "SIGTERM"
            case "SIGTRAP" => "SIGTRAP"
            case "SIGTSTP" => "SIGTSTP"
            case "SIGTTIN" => "SIGTTIN"
            case "SIGTTOU" => "SIGTTOU"
            case "SIGURG" => "SIGURG"
            case "SIGUSR1" => "SIGUSR1"
            case "SIGUSR2" => "SIGUSR2"
            case "SIGVTALRM" => "SIGVTALRM"
            case "SIGWINCH" => "SIGWINCH"
            case "SIGXCPU" => "SIGXCPU"
            case "SIGXFSZ" => "SIGXFSZ"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end ContainerStatusEnums
