/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kubescala.api.v1.models

import java.time.OffsetDateTime
import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * ContainerStateTerminated is a terminated state of a container.
   */
case class ContainerStateTerminated(
  /* Exit status from the last termination of the container */
  @named("exitCode") exitCode: Int,
  /* Container's ID in the format '<type>://<container_id>' */
  @named("containerID") containerID: Option[String] = scala.None,
  /* Time at which the container last terminated */
  @named("finishedAt") finishedAt: Option[OffsetDateTime] = scala.None,
  /* Message regarding the last termination of the container */
  @named("message") message: Option[String] = scala.None,
  /* (brief) reason from the last termination of the container */
  @named("reason") reason: Option[String] = scala.None,
  /* Signal from the last termination of the container */
  @named("signal") signal: Option[Int] = scala.None,
  /* Time at which previous execution of the container started */
  @named("startedAt") startedAt: Option[OffsetDateTime] = scala.None
)

