/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kubescala.api.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * ContainerExtendedResourceRequest has the mapping of container name, extended resource name to the device request name.
   */
case class ContainerExtendedResourceRequest(
  /* The name of the container requesting resources. */
  @named("containerName") containerName: String,
  /* The name of the request in the special ResourceClaim which corresponds to the extended resource. */
  @named("requestName") requestName: String,
  /* The name of the extended resource in that container which gets backed by DRA. */
  @named("resourceName") resourceName: String
)

