/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kubescala.api.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * ContainerUser represents user identity information
   */
case class ContainerUser(
  /* Linux holds user identity information initially attached to the first process of the containers in Linux. Note that the actual running identity can be changed if the process has enough privilege to do so. */
  @named("linux") linux: Option[LinuxContainerUser] = scala.None
)

