/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kubescala.api.v1.models

import java.time.OffsetDateTime
import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * Event is a report of an event somewhere in the cluster.  Events have a limited retention time and triggers and messages may evolve with time.  Event consumers should not rely on the timing of an event with a given Reason reflecting a consistent underlying trigger, or the continued existence of events with that Reason.  Events should be treated as informative, best-effort, supplemental data.
   */
case class Event(
  /* The object that this event is about. */
  @named("involvedObject") involvedObject: ObjectReference,
  /* Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata */
  @named("metadata") metadata: ObjectMeta,
  /* What action was taken/failed regarding to the Regarding object. */
  @named("action") action: Option[String] = scala.None,
  /* APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
  @named("apiVersion") apiVersion: Option[String] = scala.None,
  /* The number of times this event has occurred. */
  @named("count") count: Option[Int] = scala.None,
  /* Time when this Event was first observed. */
  @named("eventTime") eventTime: Option[OffsetDateTime] = scala.None,
  /* The time at which the event was first recorded. (Time of server receipt is in TypeMeta.) */
  @named("firstTimestamp") firstTimestamp: Option[OffsetDateTime] = scala.None,
  /* Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
  @named("kind") kind: Option[String] = scala.None,
  /* The time at which the most recent occurrence of this event was recorded. */
  @named("lastTimestamp") lastTimestamp: Option[OffsetDateTime] = scala.None,
  /* A human-readable description of the status of this operation. */
  @named("message") message: Option[String] = scala.None,
  /* This should be a short, machine understandable string that gives the reason for the transition into the object's current status. */
  @named("reason") reason: Option[String] = scala.None,
  /* Optional secondary object for more complex actions. */
  @named("related") related: Option[ObjectReference] = scala.None,
  /* Name of the controller that emitted this Event, e.g. `kubernetes.io/kubelet`. */
  @named("reportingComponent") reportingComponent: Option[String] = scala.None,
  /* ID of the controller instance, e.g. `kubelet-xyzf`. */
  @named("reportingInstance") reportingInstance: Option[String] = scala.None,
  /* Data about the Event series this event represents or nil if it's a singleton Event. */
  @named("series") series: Option[EventSeries] = scala.None,
  /* The component reporting this event. Should be a short machine understandable string. */
  @named("source") source: Option[EventSource] = scala.None,
  /* Type of this event (Normal, Warning), new types could be added in the future */
  @named("type") `type`: Option[String] = scala.None
)

