/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kubescala.api.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * LoadBalancerStatus represents the status of a load-balancer.
   */
case class LoadBalancerStatus(
  /* Ingress is a list containing ingress points for the load-balancer. Traffic intended for the service should be sent to these ingress points. */
  @named("ingress") ingress: Option[Seq[LoadBalancerIngress]] = scala.None
)

