/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kubescala.api.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * NodeAddress contains information for the node's address.
   */
case class NodeAddress(
  /* The node address. */
  @named("address") address: String,
  /* Node address type, one of Hostname, ExternalIP or InternalIP. */
  @named("type") `type`: String
)

