/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kubescala.api.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * ResourceQuotaStatus defines the enforced hard limits and observed use.
   */
case class ResourceQuotaStatus(
  /* Hard is the set of enforced hard limits for each named resource. More info: https://kubernetes.io/docs/concepts/policy/resource-quotas/ */
  @named("hard") hard: Option[Map[String, Quantity]] = scala.None,
  /* Used is the current observed total usage of the resource in the namespace. */
  @named("used") used: Option[Map[String, Quantity]] = scala.None
)

