/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kubescala.api.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * ScaleSpec describes the attributes of a scale subresource.
   */
case class ScaleSpec(
  /* replicas is the desired number of instances for the scaled object. */
  @named("replicas") replicas: Option[Int] = scala.None
)

