/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kubescala.api.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * A scope selector represents the AND of the selectors represented by the scoped-resource selector requirements.
   */
case class ScopeSelector(
  /* A list of scope selector requirements by scope of the resources. */
  @named("matchExpressions") matchExpressions: Option[Seq[ScopedResourceSelectorRequirement]] = scala.None
)

