/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kubescala.api.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * ServiceAccount binds together: * a name, understood by users, and perhaps by peripheral systems, for an identity * a principal that can be authenticated and authorized * a set of secrets
   */
case class ServiceAccount(
  /* APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
  @named("apiVersion") apiVersion: Option[String] = scala.None,
  /* AutomountServiceAccountToken indicates whether pods running as this ServiceAccount should have an API token automatically mounted. Can be overridden at the pod level. */
  @named("automountServiceAccountToken") automountServiceAccountToken: Option[Boolean] = scala.None,
  /* ImagePullSecrets is a list of references to secrets in the same namespace to use for pulling any images in pods that reference this ServiceAccount. ImagePullSecrets are distinct from Secrets because Secrets can be mounted in the pod, but ImagePullSecrets are only accessed by the kubelet. More info: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod */
  @named("imagePullSecrets") imagePullSecrets: Option[Seq[LocalObjectReference]] = scala.None,
  /* Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
  @named("kind") kind: Option[String] = scala.None,
  /* Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata */
  @named("metadata") metadata: Option[ObjectMeta] = scala.None,
  /* Secrets is a list of the secrets in the same namespace that pods running using this ServiceAccount are allowed to use. Pods are only limited to this list if this ServiceAccount has a \"kubernetes.io/enforce-mountable-secrets\" annotation set to \"true\". The \"kubernetes.io/enforce-mountable-secrets\" annotation is deprecated since v1.32. Prefer separate namespaces to isolate access to mounted secrets. This field should not be used to find auto-generated ServiceAccount token secrets for use outside of pods. Instead, tokens can be requested directly using the TokenRequest API, or ServiceAccount token secrets can be manually created. More info: https://kubernetes.io/docs/concepts/configuration/secret */
  @named("secrets") secrets: Option[Seq[ObjectReference]] = scala.None
)

