/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kubescala.api.v1.models

import java.time.OffsetDateTime
import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * The node this Taint is attached to has the \"effect\" on any pod that does not tolerate the Taint.
   */
case class Taint(
  /* Required. The effect of the taint on pods that do not tolerate the taint. Valid effects are NoSchedule, PreferNoSchedule and NoExecute.  Possible enum values:  - `\"NoExecute\"` Evict any already-running pods that do not tolerate the taint. Currently enforced by NodeController.  - `\"NoSchedule\"` Do not allow new pods to schedule onto the node unless they tolerate the taint, but allow all pods submitted to Kubelet without going through the scheduler to start, and allow all already-running pods to continue running. Enforced by the scheduler.  - `\"PreferNoSchedule\"` Like TaintEffectNoSchedule, but the scheduler tries not to schedule new pods onto the node, rather than prohibiting new pods from scheduling onto the node entirely. Enforced by the scheduler. */
  @named("effect") effect: TaintEnums.Effect,
  /* Required. The taint key to be applied to a node. */
  @named("key") key: String,
  /* TimeAdded represents the time at which the taint was added. */
  @named("timeAdded") timeAdded: Option[OffsetDateTime] = scala.None,
  /* The taint value corresponding to the taint key. */
  @named("value") value: Option[String] = scala.None
)

object TaintEnums:
  enum Effect:
    case `NoExecute`
    case `NoSchedule`
    case `PreferNoSchedule`

  object Effect:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given effectCodec: JsonValueCodec[Effect] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "NoExecute" => "NoExecute"
            case "NoSchedule" => "NoSchedule"
            case "PreferNoSchedule" => "PreferNoSchedule"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end TaintEnums
