/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kubescala.api.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * VolumeMountStatus shows status of volume mounts.
   */
case class VolumeMountStatus(
  /* MountPath corresponds to the original VolumeMount. */
  @named("mountPath") mountPath: String,
  /* Name corresponds to the name of the original VolumeMount. */
  @named("name") name: String,
  /* ReadOnly corresponds to the original VolumeMount. */
  @named("readOnly") readOnly: Option[Boolean] = scala.None,
  /* RecursiveReadOnly must be set to Disabled, Enabled, or unspecified (for non-readonly mounts). An IfPossible value in the original VolumeMount must be translated to Disabled or Enabled, depending on the mount result. */
  @named("recursiveReadOnly") recursiveReadOnly: Option[String] = scala.None
)

