/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.scheduling.v1.api

import kubescala.scheduling.v1.models.APIResourceList
import kubescala.scheduling.v1.models.DeleteOptions
import kubescala.scheduling.v1.models.PriorityClass
import kubescala.scheduling.v1.models.PriorityClassList
import kubescala.scheduling.v1.models.Status
import kubescala.scheduling.v1.models.WatchEvent
import com.github.plokhotnyuk.jsoniter_scala.circe.JsoniterScalaCodec.*
import kubescala.scheduling.v1.JsonSupport.{*, given}
import kubescala.scheduling.v1.FormSerializable
import kubescala.scheduling.v1.FormStyleFormat
import kubescala.scheduling.v1.HeaderSerializable
import kubescala.scheduling.v1.ApiKeyLocation
import kubescala.scheduling.v1.PathStyleFormat
import kubescala.scheduling.v1.PathSerializable
import kubescala.scheduling.v1.CookieSerializable
import kubescala.scheduling.v1.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object SchedulingV1Api:
  def apply(baseUrl: String = "http://localhost"): SchedulingV1Api[
    kubescala.scheduling.v1.Authorization.NoAuthorization.type
  ] = SchedulingV1Api(
    baseUrl,
    kubescala.scheduling.v1.Authorization.NoAuthorization
  )
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): SchedulingV1Api[kubescala.scheduling.v1.Authorization.BasicAuth] =
    SchedulingV1Api(
      baseUrl,
      kubescala.scheduling.v1.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): SchedulingV1Api[kubescala.scheduling.v1.Authorization.ApiKey] =
    SchedulingV1Api(
      baseUrl,
      kubescala.scheduling.v1.Authorization.ApiKey(apiKey)
    )

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): SchedulingV1Api[kubescala.scheduling.v1.Authorization.BearerToken] =
    SchedulingV1Api(
      baseUrl,
      kubescala.scheduling.v1.Authorization.BearerToken(token)
    )

case class SchedulingV1Api[
    Auth <: kubescala.scheduling.v1.Authorization
] private (baseUrl: String, authConfig: kubescala.scheduling.v1.Authorization):
  def withBasicAuth(
      username: String,
      password: String
  ): SchedulingV1Api[kubescala.scheduling.v1.Authorization.BasicAuth] =
    copy(authConfig =
      kubescala.scheduling.v1.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      apiKey: String
  ): SchedulingV1Api[kubescala.scheduling.v1.Authorization.ApiKey] =
    copy(authConfig = kubescala.scheduling.v1.Authorization.ApiKey(apiKey))

  def withNoAuth: SchedulingV1Api[
    kubescala.scheduling.v1.Authorization.NoAuthorization.type
  ] =
    copy(authConfig = kubescala.scheduling.v1.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): SchedulingV1Api[kubescala.scheduling.v1.Authorization.BearerToken] =
    copy(authConfig = kubescala.scheduling.v1.Authorization.BearerToken(token))

  /** create a PriorityClass
    *
    * Expected answers: code 200 : PriorityClass (OK) code 201 : PriorityClass
    * (Created) code 202 : PriorityClass (Accepted) code 401 : (Unauthorized)
    *
    * @param priorityClass
    * @param pretty
    *   If 'true', then the output is pretty printed. Defaults to 'false' unless
    *   the user-agent indicates a browser or command-line HTTP tool (curl and
    *   wget).
    * @param dryRun
    *   When present, indicates that modifications should not be persisted. An
    *   invalid or unrecognized dryRun directive will result in an error
    *   response and no further processing of the request. Valid values are: -
    *   All: all dry run stages will be processed
    * @param fieldManager
    *   fieldManager is a name associated with the actor or entity that is
    *   making these changes. The value must be less than or 128 characters
    *   long, and only contain printable characters, as defined by
    *   https://golang.org/pkg/unicode/#IsPrint.
    * @param fieldValidation
    *   fieldValidation instructs the server on how to handle objects in the
    *   request (POST/PUT/PATCH) containing unknown or duplicate fields. Valid
    *   values are: - Ignore: This will ignore any unknown fields that are
    *   silently dropped from the object, and will ignore all but the last
    *   duplicate field that the decoder encounters. This is the default
    *   behavior prior to v1.23. - Warn: This will send a warning via the
    *   standard warning response header for each unknown field that is dropped
    *   from the object, and for each duplicate field that is encountered. The
    *   request will still succeed if there are no other errors, and will only
    *   persist the last of any duplicate fields. This is the default in v1.23+ -
    *   Strict: This will fail the request with a BadRequest error if any
    *   unknown fields would be dropped from the object, or if any duplicate
    *   fields are present. The error returned from the server will contain all
    *   unknown and duplicate fields encountered.
    */
  def createSchedulingV1PriorityClass(
      priorityClass: PriorityClass,
      pretty: Option[String] = scala.None,
      dryRun: Option[String] = scala.None,
      fieldManager: Option[String] = scala.None,
      fieldValidation: Option[String] = scala.None
  ): sttp.client4.Request[Either[ResponseException[String], PriorityClass]] =
    val requestURL =
      uri"$baseUrl/apis/scheduling.k8s.io/v1/priorityclasses"
        .addParams(
          FormSerializable
            .serialize("pretty", pretty, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("dryRun", dryRun, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable.serialize(
            "fieldManager",
            fieldManager,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "fieldValidation",
            fieldValidation,
            FormStyleFormat.FORM,
            true
          ): _*
        )

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .body(asJson(priorityClass))
      .response(asJson[PriorityClass])

  /** delete collection of PriorityClass
    *
    * Expected answers: code 200 : Status (OK) code 401 : (Unauthorized)
    *
    * @param pretty
    *   If 'true', then the output is pretty printed. Defaults to 'false' unless
    *   the user-agent indicates a browser or command-line HTTP tool (curl and
    *   wget).
    * @param continue
    *   The continue option should be set when retrieving more results from the
    *   server. Since this value is server defined, clients may only use the
    *   continue value from a previous query result with identical query
    *   parameters (except for the value of continue) and the server may reject
    *   a continue value it does not recognize. If the specified continue value
    *   is no longer valid whether due to expiration (generally five to fifteen
    *   minutes) or a configuration change on the server, the server will
    *   respond with a 410 ResourceExpired error together with a continue token.
    *   If the client needs a consistent list, it must restart their list
    *   without the continue field. Otherwise, the client may send another list
    *   request with the token received with the 410 error, the server will
    *   respond with a list starting from the next key, but from the latest
    *   snapshot, which is inconsistent from the previous list results - objects
    *   that are created, modified, or deleted after the first list request will
    *   be included in the response, as long as their keys are after the \"next
    *   key\". This field is not supported when watch is true. Clients may start
    *   a watch from the last resourceVersion value returned by the server and
    *   not miss any modifications.
    * @param dryRun
    *   When present, indicates that modifications should not be persisted. An
    *   invalid or unrecognized dryRun directive will result in an error
    *   response and no further processing of the request. Valid values are: -
    *   All: all dry run stages will be processed
    * @param fieldSelector
    *   A selector to restrict the list of returned objects by their fields.
    *   Defaults to everything.
    * @param gracePeriodSeconds
    *   The duration in seconds before the object should be deleted. Value must
    *   be non-negative integer. The value zero indicates delete immediately. If
    *   this value is nil, the default grace period for the specified type will
    *   be used. Defaults to a per object value if not specified. zero means
    *   delete immediately.
    * @param ignoreStoreReadErrorWithClusterBreakingPotential
    *   if set to true, it will trigger an unsafe deletion of the resource in
    *   case the normal deletion flow fails with a corrupt object error. A
    *   resource is considered corrupt if it can not be retrieved from the
    *   underlying storage successfully because of a) its data can not be
    *   transformed e.g. decryption failure, or b) it fails to decode into an
    *   object. NOTE: unsafe deletion ignores finalizer constraints, skips
    *   precondition checks, and removes the object from the storage. WARNING:
    *   This may potentially break the cluster if the workload associated with
    *   the resource being unsafe-deleted relies on normal deletion flow. Use
    *   only if you REALLY know what you are doing. The default value is false,
    *   and the user must opt in to enable it
    * @param labelSelector
    *   A selector to restrict the list of returned objects by their labels.
    *   Defaults to everything.
    * @param limit
    *   limit is a maximum number of responses to return for a list call. If
    *   more items exist, the server will set the `continue` field on the list
    *   metadata to a value that can be used with the same initial query to
    *   retrieve the next set of results. Setting a limit may return fewer than
    *   the requested amount of items (up to zero items) in the event all
    *   requested objects are filtered out and clients should only use the
    *   presence of the continue field to determine whether more results are
    *   available. Servers may choose not to support the limit argument and will
    *   return all of the available results. If limit is specified and the
    *   continue field is empty, clients may assume that no more results are
    *   available. This field is not supported if watch is true. The server
    *   guarantees that the objects returned when using continue will be
    *   identical to issuing a single list call without a limit - that is, no
    *   objects created, modified, or deleted after the first request is issued
    *   will be included in any subsequent continued requests. This is sometimes
    *   referred to as a consistent snapshot, and ensures that a client that is
    *   using limit to receive smaller chunks of a very large result can ensure
    *   they see all possible objects. If objects are updated during a chunked
    *   list the version of the object that was present at the time the first
    *   list result was calculated is returned.
    * @param orphanDependents
    *   Deprecated: please use the PropagationPolicy, this field will be
    *   deprecated in 1.7. Should the dependent objects be orphaned. If
    *   true/false, the \"orphan\" finalizer will be added to/removed from the
    *   object's finalizers list. Either this field or PropagationPolicy may be
    *   set, but not both.
    * @param propagationPolicy
    *   Whether and how garbage collection will be performed. Either this field
    *   or OrphanDependents may be set, but not both. The default policy is
    *   decided by the existing finalizer set in the metadata.finalizers and the
    *   resource-specific default policy. Acceptable values are: 'Orphan' -
    *   orphan the dependents; 'Background' - allow the garbage collector to
    *   delete the dependents in the background; 'Foreground' - a cascading
    *   policy that deletes all dependents in the foreground.
    * @param resourceVersion
    *   resourceVersion sets a constraint on what resource versions a request
    *   may be served from. See
    *   https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-versions
    *   for details. Defaults to unset
    * @param resourceVersionMatch
    *   resourceVersionMatch determines how resourceVersion is applied to list
    *   calls. It is highly recommended that resourceVersionMatch be set for
    *   list calls where resourceVersion is set See
    *   https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-versions
    *   for details. Defaults to unset
    * @param sendInitialEvents
    *   `sendInitialEvents=true` may be set together with `watch=true`. In that
    *   case, the watch stream will begin with synthetic events to produce the
    *   current state of objects in the collection. Once all such events have
    *   been sent, a synthetic \"Bookmark\" event will be sent. The bookmark
    *   will report the ResourceVersion (RV) corresponding to the set of
    *   objects, and be marked with `\"k8s.io/initial-events-end\": \"true\"`
    *   annotation. Afterwards, the watch stream will proceed as usual, sending
    *   watch events corresponding to changes (subsequent to the RV) to objects
    *   watched. When `sendInitialEvents` option is set, we require
    *   `resourceVersionMatch` option to also be set. The semantic of the watch
    *   request is as following: - `resourceVersionMatch` = NotOlderThan is
    *   interpreted as \"data at least as new as the provided
    *   `resourceVersion`\" and the bookmark event is send when the state is
    *   synced to a `resourceVersion` at least as fresh as the one provided by
    *   the ListOptions. If `resourceVersion` is unset, this is interpreted as
    *   \"consistent read\" and the bookmark event is send when the state is
    *   synced at least to the moment when request started being processed. -
    *   `resourceVersionMatch` set to any other value or unset Invalid error is
    *   returned. Defaults to true if `resourceVersion=\"\"` or
    *   `resourceVersion=\"0\"` (for backward compatibility reasons) and to
    *   false otherwise.
    * @param timeoutSeconds
    *   Timeout for the list/watch call. This limits the duration of the call,
    *   regardless of any activity or inactivity.
    * @param deleteOptions
    */
  def deleteSchedulingV1CollectionPriorityClass(
      pretty: Option[String] = scala.None,
      continue: Option[String] = scala.None,
      dryRun: Option[String] = scala.None,
      fieldSelector: Option[String] = scala.None,
      gracePeriodSeconds: Option[Int] = scala.None,
      ignoreStoreReadErrorWithClusterBreakingPotential: Option[Boolean] =
        scala.None,
      labelSelector: Option[String] = scala.None,
      limit: Option[Int] = scala.None,
      orphanDependents: Option[Boolean] = scala.None,
      propagationPolicy: Option[String] = scala.None,
      resourceVersion: Option[String] = scala.None,
      resourceVersionMatch: Option[String] = scala.None,
      sendInitialEvents: Option[Boolean] = scala.None,
      timeoutSeconds: Option[Int] = scala.None,
      deleteOptions: Option[DeleteOptions] = scala.None
  ): sttp.client4.Request[Either[ResponseException[String], Status]] =
    val requestURL =
      uri"$baseUrl/apis/scheduling.k8s.io/v1/priorityclasses"
        .addParams(
          FormSerializable.serialize(
            "pretty",
            pretty,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "continue",
            continue,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "dryRun",
            dryRun,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "fieldSelector",
            fieldSelector,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "gracePeriodSeconds",
            gracePeriodSeconds,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "ignoreStoreReadErrorWithClusterBreakingPotential",
            ignoreStoreReadErrorWithClusterBreakingPotential,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "labelSelector",
            labelSelector,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("limit", limit, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable.serialize(
            "orphanDependents",
            orphanDependents,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "propagationPolicy",
            propagationPolicy,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "resourceVersion",
            resourceVersion,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "resourceVersionMatch",
            resourceVersionMatch,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "sendInitialEvents",
            sendInitialEvents,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "timeoutSeconds",
            timeoutSeconds,
            FormStyleFormat.FORM,
            true
          ): _*
        )

    basicRequest
      .method(Method.DELETE, requestURL)
      .contentType("application/json")
      .body(asJson(deleteOptions))
      .response(asJson[Status])

  /** delete a PriorityClass
    *
    * Expected answers: code 200 : Status (OK) code 202 : Status (Accepted) code
    * 401 : (Unauthorized)
    *
    * @param name
    *   name of the PriorityClass
    * @param pretty
    *   If 'true', then the output is pretty printed. Defaults to 'false' unless
    *   the user-agent indicates a browser or command-line HTTP tool (curl and
    *   wget).
    * @param dryRun
    *   When present, indicates that modifications should not be persisted. An
    *   invalid or unrecognized dryRun directive will result in an error
    *   response and no further processing of the request. Valid values are: -
    *   All: all dry run stages will be processed
    * @param gracePeriodSeconds
    *   The duration in seconds before the object should be deleted. Value must
    *   be non-negative integer. The value zero indicates delete immediately. If
    *   this value is nil, the default grace period for the specified type will
    *   be used. Defaults to a per object value if not specified. zero means
    *   delete immediately.
    * @param ignoreStoreReadErrorWithClusterBreakingPotential
    *   if set to true, it will trigger an unsafe deletion of the resource in
    *   case the normal deletion flow fails with a corrupt object error. A
    *   resource is considered corrupt if it can not be retrieved from the
    *   underlying storage successfully because of a) its data can not be
    *   transformed e.g. decryption failure, or b) it fails to decode into an
    *   object. NOTE: unsafe deletion ignores finalizer constraints, skips
    *   precondition checks, and removes the object from the storage. WARNING:
    *   This may potentially break the cluster if the workload associated with
    *   the resource being unsafe-deleted relies on normal deletion flow. Use
    *   only if you REALLY know what you are doing. The default value is false,
    *   and the user must opt in to enable it
    * @param orphanDependents
    *   Deprecated: please use the PropagationPolicy, this field will be
    *   deprecated in 1.7. Should the dependent objects be orphaned. If
    *   true/false, the \"orphan\" finalizer will be added to/removed from the
    *   object's finalizers list. Either this field or PropagationPolicy may be
    *   set, but not both.
    * @param propagationPolicy
    *   Whether and how garbage collection will be performed. Either this field
    *   or OrphanDependents may be set, but not both. The default policy is
    *   decided by the existing finalizer set in the metadata.finalizers and the
    *   resource-specific default policy. Acceptable values are: 'Orphan' -
    *   orphan the dependents; 'Background' - allow the garbage collector to
    *   delete the dependents in the background; 'Foreground' - a cascading
    *   policy that deletes all dependents in the foreground.
    * @param deleteOptions
    */
  def deleteSchedulingV1PriorityClass(
      name: String,
      pretty: Option[String] = scala.None,
      dryRun: Option[String] = scala.None,
      gracePeriodSeconds: Option[Int] = scala.None,
      ignoreStoreReadErrorWithClusterBreakingPotential: Option[Boolean] =
        scala.None,
      orphanDependents: Option[Boolean] = scala.None,
      propagationPolicy: Option[String] = scala.None,
      deleteOptions: Option[DeleteOptions] = scala.None
  ): sttp.client4.Request[Either[ResponseException[String], Status]] =
    val namePathParam =
      PathSerializable.serialize("name", name, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/apis/scheduling.k8s.io/v1/priorityclasses/${namePathParam}"
        .addParams(
          FormSerializable
            .serialize("pretty", pretty, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("dryRun", dryRun, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable.serialize(
            "gracePeriodSeconds",
            gracePeriodSeconds,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "ignoreStoreReadErrorWithClusterBreakingPotential",
            ignoreStoreReadErrorWithClusterBreakingPotential,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "orphanDependents",
            orphanDependents,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "propagationPolicy",
            propagationPolicy,
            FormStyleFormat.FORM,
            true
          ): _*
        )

    basicRequest
      .method(Method.DELETE, requestURL)
      .contentType("application/json")
      .body(asJson(deleteOptions))
      .response(asJson[Status])

  /** get available resources
    *
    * Expected answers: code 200 : APIResourceList (OK) code 401 :
    * (Unauthorized)
    */
  def getSchedulingV1APIResources: sttp.client4.Request[
    Either[ResponseException[String], APIResourceList]
  ] =
    val requestURL =
      uri"$baseUrl/apis/scheduling.k8s.io/v1/"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .response(asJson[APIResourceList])

  /** list or watch objects of kind PriorityClass
    *
    * Expected answers: code 200 : PriorityClassList (OK) code 401 :
    * (Unauthorized)
    *
    * @param pretty
    *   If 'true', then the output is pretty printed. Defaults to 'false' unless
    *   the user-agent indicates a browser or command-line HTTP tool (curl and
    *   wget).
    * @param allowWatchBookmarks
    *   allowWatchBookmarks requests watch events with type \"BOOKMARK\".
    *   Servers that do not implement bookmarks may ignore this flag and
    *   bookmarks are sent at the server's discretion. Clients should not assume
    *   bookmarks are returned at any specific interval, nor may they assume the
    *   server will send any BOOKMARK event during a session. If this is not a
    *   watch, this field is ignored.
    * @param continue
    *   The continue option should be set when retrieving more results from the
    *   server. Since this value is server defined, clients may only use the
    *   continue value from a previous query result with identical query
    *   parameters (except for the value of continue) and the server may reject
    *   a continue value it does not recognize. If the specified continue value
    *   is no longer valid whether due to expiration (generally five to fifteen
    *   minutes) or a configuration change on the server, the server will
    *   respond with a 410 ResourceExpired error together with a continue token.
    *   If the client needs a consistent list, it must restart their list
    *   without the continue field. Otherwise, the client may send another list
    *   request with the token received with the 410 error, the server will
    *   respond with a list starting from the next key, but from the latest
    *   snapshot, which is inconsistent from the previous list results - objects
    *   that are created, modified, or deleted after the first list request will
    *   be included in the response, as long as their keys are after the \"next
    *   key\". This field is not supported when watch is true. Clients may start
    *   a watch from the last resourceVersion value returned by the server and
    *   not miss any modifications.
    * @param fieldSelector
    *   A selector to restrict the list of returned objects by their fields.
    *   Defaults to everything.
    * @param labelSelector
    *   A selector to restrict the list of returned objects by their labels.
    *   Defaults to everything.
    * @param limit
    *   limit is a maximum number of responses to return for a list call. If
    *   more items exist, the server will set the `continue` field on the list
    *   metadata to a value that can be used with the same initial query to
    *   retrieve the next set of results. Setting a limit may return fewer than
    *   the requested amount of items (up to zero items) in the event all
    *   requested objects are filtered out and clients should only use the
    *   presence of the continue field to determine whether more results are
    *   available. Servers may choose not to support the limit argument and will
    *   return all of the available results. If limit is specified and the
    *   continue field is empty, clients may assume that no more results are
    *   available. This field is not supported if watch is true. The server
    *   guarantees that the objects returned when using continue will be
    *   identical to issuing a single list call without a limit - that is, no
    *   objects created, modified, or deleted after the first request is issued
    *   will be included in any subsequent continued requests. This is sometimes
    *   referred to as a consistent snapshot, and ensures that a client that is
    *   using limit to receive smaller chunks of a very large result can ensure
    *   they see all possible objects. If objects are updated during a chunked
    *   list the version of the object that was present at the time the first
    *   list result was calculated is returned.
    * @param resourceVersion
    *   resourceVersion sets a constraint on what resource versions a request
    *   may be served from. See
    *   https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-versions
    *   for details. Defaults to unset
    * @param resourceVersionMatch
    *   resourceVersionMatch determines how resourceVersion is applied to list
    *   calls. It is highly recommended that resourceVersionMatch be set for
    *   list calls where resourceVersion is set See
    *   https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-versions
    *   for details. Defaults to unset
    * @param sendInitialEvents
    *   `sendInitialEvents=true` may be set together with `watch=true`. In that
    *   case, the watch stream will begin with synthetic events to produce the
    *   current state of objects in the collection. Once all such events have
    *   been sent, a synthetic \"Bookmark\" event will be sent. The bookmark
    *   will report the ResourceVersion (RV) corresponding to the set of
    *   objects, and be marked with `\"k8s.io/initial-events-end\": \"true\"`
    *   annotation. Afterwards, the watch stream will proceed as usual, sending
    *   watch events corresponding to changes (subsequent to the RV) to objects
    *   watched. When `sendInitialEvents` option is set, we require
    *   `resourceVersionMatch` option to also be set. The semantic of the watch
    *   request is as following: - `resourceVersionMatch` = NotOlderThan is
    *   interpreted as \"data at least as new as the provided
    *   `resourceVersion`\" and the bookmark event is send when the state is
    *   synced to a `resourceVersion` at least as fresh as the one provided by
    *   the ListOptions. If `resourceVersion` is unset, this is interpreted as
    *   \"consistent read\" and the bookmark event is send when the state is
    *   synced at least to the moment when request started being processed. -
    *   `resourceVersionMatch` set to any other value or unset Invalid error is
    *   returned. Defaults to true if `resourceVersion=\"\"` or
    *   `resourceVersion=\"0\"` (for backward compatibility reasons) and to
    *   false otherwise.
    * @param timeoutSeconds
    *   Timeout for the list/watch call. This limits the duration of the call,
    *   regardless of any activity or inactivity.
    * @param watch
    *   Watch for changes to the described resources and return them as a stream
    *   of add, update, and remove notifications. Specify resourceVersion.
    */
  def listSchedulingV1PriorityClass(
      pretty: Option[String] = scala.None,
      allowWatchBookmarks: Option[Boolean] = scala.None,
      continue: Option[String] = scala.None,
      fieldSelector: Option[String] = scala.None,
      labelSelector: Option[String] = scala.None,
      limit: Option[Int] = scala.None,
      resourceVersion: Option[String] = scala.None,
      resourceVersionMatch: Option[String] = scala.None,
      sendInitialEvents: Option[Boolean] = scala.None,
      timeoutSeconds: Option[Int] = scala.None,
      watch: Option[Boolean] = scala.None
  ): sttp.client4.Request[
    Either[ResponseException[String], PriorityClassList]
  ] =
    val requestURL =
      uri"$baseUrl/apis/scheduling.k8s.io/v1/priorityclasses"
        .addParams(
          FormSerializable.serialize(
            "pretty",
            pretty,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "allowWatchBookmarks",
            allowWatchBookmarks,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("continue", continue, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable.serialize(
            "fieldSelector",
            fieldSelector,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "labelSelector",
            labelSelector,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("limit", limit, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable.serialize(
            "resourceVersion",
            resourceVersion,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "resourceVersionMatch",
            resourceVersionMatch,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "sendInitialEvents",
            sendInitialEvents,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "timeoutSeconds",
            timeoutSeconds,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("watch", watch, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .response(asJson[PriorityClassList])

  /** partially update the specified PriorityClass
    *
    * Expected answers: code 200 : PriorityClass (OK) code 201 : PriorityClass
    * (Created) code 401 : (Unauthorized)
    *
    * @param name
    *   name of the PriorityClass
    * @param body
    * @param pretty
    *   If 'true', then the output is pretty printed. Defaults to 'false' unless
    *   the user-agent indicates a browser or command-line HTTP tool (curl and
    *   wget).
    * @param dryRun
    *   When present, indicates that modifications should not be persisted. An
    *   invalid or unrecognized dryRun directive will result in an error
    *   response and no further processing of the request. Valid values are: -
    *   All: all dry run stages will be processed
    * @param fieldManager
    *   fieldManager is a name associated with the actor or entity that is
    *   making these changes. The value must be less than or 128 characters
    *   long, and only contain printable characters, as defined by
    *   https://golang.org/pkg/unicode/#IsPrint. This field is required for
    *   apply requests (application/apply-patch) but optional for non-apply
    *   patch types (JsonPatch, MergePatch, StrategicMergePatch).
    * @param fieldValidation
    *   fieldValidation instructs the server on how to handle objects in the
    *   request (POST/PUT/PATCH) containing unknown or duplicate fields. Valid
    *   values are: - Ignore: This will ignore any unknown fields that are
    *   silently dropped from the object, and will ignore all but the last
    *   duplicate field that the decoder encounters. This is the default
    *   behavior prior to v1.23. - Warn: This will send a warning via the
    *   standard warning response header for each unknown field that is dropped
    *   from the object, and for each duplicate field that is encountered. The
    *   request will still succeed if there are no other errors, and will only
    *   persist the last of any duplicate fields. This is the default in v1.23+ -
    *   Strict: This will fail the request with a BadRequest error if any
    *   unknown fields would be dropped from the object, or if any duplicate
    *   fields are present. The error returned from the server will contain all
    *   unknown and duplicate fields encountered.
    * @param force
    *   Force is going to \"force\" Apply requests. It means user will
    *   re-acquire conflicting fields owned by other people. Force flag must be
    *   unset for non-apply patch requests.
    */
  def patchSchedulingV1PriorityClass(
      name: String,
      body: io.circe.Json,
      pretty: Option[String] = scala.None,
      dryRun: Option[String] = scala.None,
      fieldManager: Option[String] = scala.None,
      fieldValidation: Option[String] = scala.None,
      force: Option[Boolean] = scala.None
  ): sttp.client4.Request[Either[ResponseException[String], PriorityClass]] =
    val namePathParam =
      PathSerializable.serialize("name", name, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/apis/scheduling.k8s.io/v1/priorityclasses/${namePathParam}"
        .addParams(
          FormSerializable
            .serialize("pretty", pretty, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("dryRun", dryRun, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable.serialize(
            "fieldManager",
            fieldManager,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "fieldValidation",
            fieldValidation,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("force", force, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.PATCH, requestURL)
      .contentType("application/apply-patch+yaml")
      .body(asJson(body))
      .response(asJson[PriorityClass])

  /** read the specified PriorityClass
    *
    * Expected answers: code 200 : PriorityClass (OK) code 401 : (Unauthorized)
    *
    * @param name
    *   name of the PriorityClass
    * @param pretty
    *   If 'true', then the output is pretty printed. Defaults to 'false' unless
    *   the user-agent indicates a browser or command-line HTTP tool (curl and
    *   wget).
    */
  def readSchedulingV1PriorityClass(
      name: String,
      pretty: Option[String] = scala.None
  ): sttp.client4.Request[Either[ResponseException[String], PriorityClass]] =
    val namePathParam =
      PathSerializable.serialize("name", name, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/apis/scheduling.k8s.io/v1/priorityclasses/${namePathParam}"
        .addParams(
          FormSerializable.serialize(
            "pretty",
            pretty,
            FormStyleFormat.FORM,
            true
          ): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .response(asJson[PriorityClass])

  /** replace the specified PriorityClass
    *
    * Expected answers: code 200 : PriorityClass (OK) code 201 : PriorityClass
    * (Created) code 401 : (Unauthorized)
    *
    * @param name
    *   name of the PriorityClass
    * @param priorityClass
    * @param pretty
    *   If 'true', then the output is pretty printed. Defaults to 'false' unless
    *   the user-agent indicates a browser or command-line HTTP tool (curl and
    *   wget).
    * @param dryRun
    *   When present, indicates that modifications should not be persisted. An
    *   invalid or unrecognized dryRun directive will result in an error
    *   response and no further processing of the request. Valid values are: -
    *   All: all dry run stages will be processed
    * @param fieldManager
    *   fieldManager is a name associated with the actor or entity that is
    *   making these changes. The value must be less than or 128 characters
    *   long, and only contain printable characters, as defined by
    *   https://golang.org/pkg/unicode/#IsPrint.
    * @param fieldValidation
    *   fieldValidation instructs the server on how to handle objects in the
    *   request (POST/PUT/PATCH) containing unknown or duplicate fields. Valid
    *   values are: - Ignore: This will ignore any unknown fields that are
    *   silently dropped from the object, and will ignore all but the last
    *   duplicate field that the decoder encounters. This is the default
    *   behavior prior to v1.23. - Warn: This will send a warning via the
    *   standard warning response header for each unknown field that is dropped
    *   from the object, and for each duplicate field that is encountered. The
    *   request will still succeed if there are no other errors, and will only
    *   persist the last of any duplicate fields. This is the default in v1.23+ -
    *   Strict: This will fail the request with a BadRequest error if any
    *   unknown fields would be dropped from the object, or if any duplicate
    *   fields are present. The error returned from the server will contain all
    *   unknown and duplicate fields encountered.
    */
  def replaceSchedulingV1PriorityClass(
      name: String,
      priorityClass: PriorityClass,
      pretty: Option[String] = scala.None,
      dryRun: Option[String] = scala.None,
      fieldManager: Option[String] = scala.None,
      fieldValidation: Option[String] = scala.None
  ): sttp.client4.Request[Either[ResponseException[String], PriorityClass]] =
    val namePathParam =
      PathSerializable.serialize("name", name, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/apis/scheduling.k8s.io/v1/priorityclasses/${namePathParam}"
        .addParams(
          FormSerializable
            .serialize("pretty", pretty, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("dryRun", dryRun, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable.serialize(
            "fieldManager",
            fieldManager,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "fieldValidation",
            fieldValidation,
            FormStyleFormat.FORM,
            true
          ): _*
        )

    basicRequest
      .method(Method.PUT, requestURL)
      .contentType("application/json")
      .body(asJson(priorityClass))
      .response(asJson[PriorityClass])

  /** watch changes to an object of kind PriorityClass. deprecated: use the
    * 'watch' parameter with a list operation instead, filtered to a single item
    * with the 'fieldSelector' parameter.
    *
    * Expected answers: code 200 : WatchEvent (OK) code 401 : (Unauthorized)
    *
    * @param name
    *   name of the PriorityClass
    * @param allowWatchBookmarks
    *   allowWatchBookmarks requests watch events with type \"BOOKMARK\".
    *   Servers that do not implement bookmarks may ignore this flag and
    *   bookmarks are sent at the server's discretion. Clients should not assume
    *   bookmarks are returned at any specific interval, nor may they assume the
    *   server will send any BOOKMARK event during a session. If this is not a
    *   watch, this field is ignored.
    * @param continue
    *   The continue option should be set when retrieving more results from the
    *   server. Since this value is server defined, clients may only use the
    *   continue value from a previous query result with identical query
    *   parameters (except for the value of continue) and the server may reject
    *   a continue value it does not recognize. If the specified continue value
    *   is no longer valid whether due to expiration (generally five to fifteen
    *   minutes) or a configuration change on the server, the server will
    *   respond with a 410 ResourceExpired error together with a continue token.
    *   If the client needs a consistent list, it must restart their list
    *   without the continue field. Otherwise, the client may send another list
    *   request with the token received with the 410 error, the server will
    *   respond with a list starting from the next key, but from the latest
    *   snapshot, which is inconsistent from the previous list results - objects
    *   that are created, modified, or deleted after the first list request will
    *   be included in the response, as long as their keys are after the \"next
    *   key\". This field is not supported when watch is true. Clients may start
    *   a watch from the last resourceVersion value returned by the server and
    *   not miss any modifications.
    * @param fieldSelector
    *   A selector to restrict the list of returned objects by their fields.
    *   Defaults to everything.
    * @param labelSelector
    *   A selector to restrict the list of returned objects by their labels.
    *   Defaults to everything.
    * @param limit
    *   limit is a maximum number of responses to return for a list call. If
    *   more items exist, the server will set the `continue` field on the list
    *   metadata to a value that can be used with the same initial query to
    *   retrieve the next set of results. Setting a limit may return fewer than
    *   the requested amount of items (up to zero items) in the event all
    *   requested objects are filtered out and clients should only use the
    *   presence of the continue field to determine whether more results are
    *   available. Servers may choose not to support the limit argument and will
    *   return all of the available results. If limit is specified and the
    *   continue field is empty, clients may assume that no more results are
    *   available. This field is not supported if watch is true. The server
    *   guarantees that the objects returned when using continue will be
    *   identical to issuing a single list call without a limit - that is, no
    *   objects created, modified, or deleted after the first request is issued
    *   will be included in any subsequent continued requests. This is sometimes
    *   referred to as a consistent snapshot, and ensures that a client that is
    *   using limit to receive smaller chunks of a very large result can ensure
    *   they see all possible objects. If objects are updated during a chunked
    *   list the version of the object that was present at the time the first
    *   list result was calculated is returned.
    * @param pretty
    *   If 'true', then the output is pretty printed. Defaults to 'false' unless
    *   the user-agent indicates a browser or command-line HTTP tool (curl and
    *   wget).
    * @param resourceVersion
    *   resourceVersion sets a constraint on what resource versions a request
    *   may be served from. See
    *   https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-versions
    *   for details. Defaults to unset
    * @param resourceVersionMatch
    *   resourceVersionMatch determines how resourceVersion is applied to list
    *   calls. It is highly recommended that resourceVersionMatch be set for
    *   list calls where resourceVersion is set See
    *   https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-versions
    *   for details. Defaults to unset
    * @param sendInitialEvents
    *   `sendInitialEvents=true` may be set together with `watch=true`. In that
    *   case, the watch stream will begin with synthetic events to produce the
    *   current state of objects in the collection. Once all such events have
    *   been sent, a synthetic \"Bookmark\" event will be sent. The bookmark
    *   will report the ResourceVersion (RV) corresponding to the set of
    *   objects, and be marked with `\"k8s.io/initial-events-end\": \"true\"`
    *   annotation. Afterwards, the watch stream will proceed as usual, sending
    *   watch events corresponding to changes (subsequent to the RV) to objects
    *   watched. When `sendInitialEvents` option is set, we require
    *   `resourceVersionMatch` option to also be set. The semantic of the watch
    *   request is as following: - `resourceVersionMatch` = NotOlderThan is
    *   interpreted as \"data at least as new as the provided
    *   `resourceVersion`\" and the bookmark event is send when the state is
    *   synced to a `resourceVersion` at least as fresh as the one provided by
    *   the ListOptions. If `resourceVersion` is unset, this is interpreted as
    *   \"consistent read\" and the bookmark event is send when the state is
    *   synced at least to the moment when request started being processed. -
    *   `resourceVersionMatch` set to any other value or unset Invalid error is
    *   returned. Defaults to true if `resourceVersion=\"\"` or
    *   `resourceVersion=\"0\"` (for backward compatibility reasons) and to
    *   false otherwise.
    * @param timeoutSeconds
    *   Timeout for the list/watch call. This limits the duration of the call,
    *   regardless of any activity or inactivity.
    * @param watch
    *   Watch for changes to the described resources and return them as a stream
    *   of add, update, and remove notifications. Specify resourceVersion.
    */
  def watchSchedulingV1PriorityClass(
      name: String,
      allowWatchBookmarks: Option[Boolean] = scala.None,
      continue: Option[String] = scala.None,
      fieldSelector: Option[String] = scala.None,
      labelSelector: Option[String] = scala.None,
      limit: Option[Int] = scala.None,
      pretty: Option[String] = scala.None,
      resourceVersion: Option[String] = scala.None,
      resourceVersionMatch: Option[String] = scala.None,
      sendInitialEvents: Option[Boolean] = scala.None,
      timeoutSeconds: Option[Int] = scala.None,
      watch: Option[Boolean] = scala.None
  ): sttp.client4.Request[Either[ResponseException[String], WatchEvent]] =
    val namePathParam =
      PathSerializable.serialize("name", name, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/apis/scheduling.k8s.io/v1/watch/priorityclasses/${namePathParam}"
        .addParams(
          FormSerializable.serialize(
            "allowWatchBookmarks",
            allowWatchBookmarks,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "continue",
            continue,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "fieldSelector",
            fieldSelector,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "labelSelector",
            labelSelector,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("limit", limit, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("pretty", pretty, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable.serialize(
            "resourceVersion",
            resourceVersion,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "resourceVersionMatch",
            resourceVersionMatch,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "sendInitialEvents",
            sendInitialEvents,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "timeoutSeconds",
            timeoutSeconds,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("watch", watch, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .response(asJson[WatchEvent])

  /** watch individual changes to a list of PriorityClass. deprecated: use the
    * 'watch' parameter with a list operation instead.
    *
    * Expected answers: code 200 : WatchEvent (OK) code 401 : (Unauthorized)
    *
    * @param allowWatchBookmarks
    *   allowWatchBookmarks requests watch events with type \"BOOKMARK\".
    *   Servers that do not implement bookmarks may ignore this flag and
    *   bookmarks are sent at the server's discretion. Clients should not assume
    *   bookmarks are returned at any specific interval, nor may they assume the
    *   server will send any BOOKMARK event during a session. If this is not a
    *   watch, this field is ignored.
    * @param continue
    *   The continue option should be set when retrieving more results from the
    *   server. Since this value is server defined, clients may only use the
    *   continue value from a previous query result with identical query
    *   parameters (except for the value of continue) and the server may reject
    *   a continue value it does not recognize. If the specified continue value
    *   is no longer valid whether due to expiration (generally five to fifteen
    *   minutes) or a configuration change on the server, the server will
    *   respond with a 410 ResourceExpired error together with a continue token.
    *   If the client needs a consistent list, it must restart their list
    *   without the continue field. Otherwise, the client may send another list
    *   request with the token received with the 410 error, the server will
    *   respond with a list starting from the next key, but from the latest
    *   snapshot, which is inconsistent from the previous list results - objects
    *   that are created, modified, or deleted after the first list request will
    *   be included in the response, as long as their keys are after the \"next
    *   key\". This field is not supported when watch is true. Clients may start
    *   a watch from the last resourceVersion value returned by the server and
    *   not miss any modifications.
    * @param fieldSelector
    *   A selector to restrict the list of returned objects by their fields.
    *   Defaults to everything.
    * @param labelSelector
    *   A selector to restrict the list of returned objects by their labels.
    *   Defaults to everything.
    * @param limit
    *   limit is a maximum number of responses to return for a list call. If
    *   more items exist, the server will set the `continue` field on the list
    *   metadata to a value that can be used with the same initial query to
    *   retrieve the next set of results. Setting a limit may return fewer than
    *   the requested amount of items (up to zero items) in the event all
    *   requested objects are filtered out and clients should only use the
    *   presence of the continue field to determine whether more results are
    *   available. Servers may choose not to support the limit argument and will
    *   return all of the available results. If limit is specified and the
    *   continue field is empty, clients may assume that no more results are
    *   available. This field is not supported if watch is true. The server
    *   guarantees that the objects returned when using continue will be
    *   identical to issuing a single list call without a limit - that is, no
    *   objects created, modified, or deleted after the first request is issued
    *   will be included in any subsequent continued requests. This is sometimes
    *   referred to as a consistent snapshot, and ensures that a client that is
    *   using limit to receive smaller chunks of a very large result can ensure
    *   they see all possible objects. If objects are updated during a chunked
    *   list the version of the object that was present at the time the first
    *   list result was calculated is returned.
    * @param pretty
    *   If 'true', then the output is pretty printed. Defaults to 'false' unless
    *   the user-agent indicates a browser or command-line HTTP tool (curl and
    *   wget).
    * @param resourceVersion
    *   resourceVersion sets a constraint on what resource versions a request
    *   may be served from. See
    *   https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-versions
    *   for details. Defaults to unset
    * @param resourceVersionMatch
    *   resourceVersionMatch determines how resourceVersion is applied to list
    *   calls. It is highly recommended that resourceVersionMatch be set for
    *   list calls where resourceVersion is set See
    *   https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-versions
    *   for details. Defaults to unset
    * @param sendInitialEvents
    *   `sendInitialEvents=true` may be set together with `watch=true`. In that
    *   case, the watch stream will begin with synthetic events to produce the
    *   current state of objects in the collection. Once all such events have
    *   been sent, a synthetic \"Bookmark\" event will be sent. The bookmark
    *   will report the ResourceVersion (RV) corresponding to the set of
    *   objects, and be marked with `\"k8s.io/initial-events-end\": \"true\"`
    *   annotation. Afterwards, the watch stream will proceed as usual, sending
    *   watch events corresponding to changes (subsequent to the RV) to objects
    *   watched. When `sendInitialEvents` option is set, we require
    *   `resourceVersionMatch` option to also be set. The semantic of the watch
    *   request is as following: - `resourceVersionMatch` = NotOlderThan is
    *   interpreted as \"data at least as new as the provided
    *   `resourceVersion`\" and the bookmark event is send when the state is
    *   synced to a `resourceVersion` at least as fresh as the one provided by
    *   the ListOptions. If `resourceVersion` is unset, this is interpreted as
    *   \"consistent read\" and the bookmark event is send when the state is
    *   synced at least to the moment when request started being processed. -
    *   `resourceVersionMatch` set to any other value or unset Invalid error is
    *   returned. Defaults to true if `resourceVersion=\"\"` or
    *   `resourceVersion=\"0\"` (for backward compatibility reasons) and to
    *   false otherwise.
    * @param timeoutSeconds
    *   Timeout for the list/watch call. This limits the duration of the call,
    *   regardless of any activity or inactivity.
    * @param watch
    *   Watch for changes to the described resources and return them as a stream
    *   of add, update, and remove notifications. Specify resourceVersion.
    */
  def watchSchedulingV1PriorityClassList(
      allowWatchBookmarks: Option[Boolean] = scala.None,
      continue: Option[String] = scala.None,
      fieldSelector: Option[String] = scala.None,
      labelSelector: Option[String] = scala.None,
      limit: Option[Int] = scala.None,
      pretty: Option[String] = scala.None,
      resourceVersion: Option[String] = scala.None,
      resourceVersionMatch: Option[String] = scala.None,
      sendInitialEvents: Option[Boolean] = scala.None,
      timeoutSeconds: Option[Int] = scala.None,
      watch: Option[Boolean] = scala.None
  ): sttp.client4.Request[Either[ResponseException[String], WatchEvent]] =
    val requestURL =
      uri"$baseUrl/apis/scheduling.k8s.io/v1/watch/priorityclasses"
        .addParams(
          FormSerializable.serialize(
            "allowWatchBookmarks",
            allowWatchBookmarks,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "continue",
            continue,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "fieldSelector",
            fieldSelector,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "labelSelector",
            labelSelector,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("limit", limit, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("pretty", pretty, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable.serialize(
            "resourceVersion",
            resourceVersion,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "resourceVersionMatch",
            resourceVersionMatch,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "sendInitialEvents",
            sendInitialEvents,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "timeoutSeconds",
            timeoutSeconds,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("watch", watch, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .response(asJson[WatchEvent])

end SchedulingV1Api
