/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kubescala.apps.v1.models

import java.time.OffsetDateTime
import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * DaemonSetCondition describes the state of a DaemonSet at a certain point.
   */
case class DaemonSetCondition(
  /* Status of the condition, one of True, False, Unknown. */
  @named("status") status: String,
  /* Type of DaemonSet condition. */
  @named("type") `type`: String,
  /* Last time the condition transitioned from one status to another. */
  @named("lastTransitionTime") lastTransitionTime: Option[OffsetDateTime] = scala.None,
  /* A human readable message indicating details about the transition. */
  @named("message") message: Option[String] = scala.None,
  /* The reason for the condition's last transition. */
  @named("reason") reason: Option[String] = scala.None
)

