/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kubescala.apps.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * DaemonSetStatus represents the current status of a daemon set.
   */
case class DaemonSetStatus(
  /* The number of nodes that are running at least 1 daemon pod and are supposed to run the daemon pod. More info: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/ */
  @named("currentNumberScheduled") currentNumberScheduled: Int,
  /* The total number of nodes that should be running the daemon pod (including nodes correctly running the daemon pod). More info: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/ */
  @named("desiredNumberScheduled") desiredNumberScheduled: Int,
  /* The number of nodes that are running the daemon pod, but are not supposed to run the daemon pod. More info: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/ */
  @named("numberMisscheduled") numberMisscheduled: Int,
  /* numberReady is the number of nodes that should be running the daemon pod and have one or more of the daemon pod running with a Ready Condition. */
  @named("numberReady") numberReady: Int,
  /* Count of hash collisions for the DaemonSet. The DaemonSet controller uses this field as a collision avoidance mechanism when it needs to create the name for the newest ControllerRevision. */
  @named("collisionCount") collisionCount: Option[Int] = scala.None,
  /* Represents the latest available observations of a DaemonSet's current state. */
  @named("conditions") conditions: Option[Seq[DaemonSetCondition]] = scala.None,
  /* The number of nodes that should be running the daemon pod and have one or more of the daemon pod running and available (ready for at least spec.minReadySeconds) */
  @named("numberAvailable") numberAvailable: Option[Int] = scala.None,
  /* The number of nodes that should be running the daemon pod and have none of the daemon pod running and available (ready for at least spec.minReadySeconds) */
  @named("numberUnavailable") numberUnavailable: Option[Int] = scala.None,
  /* The most recent generation observed by the daemon set controller. */
  @named("observedGeneration") observedGeneration: Option[Long] = scala.None,
  /* The total number of nodes that are running updated daemon pod */
  @named("updatedNumberScheduled") updatedNumberScheduled: Option[Int] = scala.None
)

