/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kubescala.apps.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * DeploymentSpec is the specification of the desired behavior of the Deployment.
   */
case class DeploymentSpec(
  /* Label selector for pods. Existing ReplicaSets whose pods are selected by this will be the ones affected by this deployment. It must match the pod template's labels. */
  @named("selector") selector: LabelSelector,
  /* Template describes the pods that will be created. The only allowed template.spec.restartPolicy value is \"Always\". */
  @named("template") template: PodTemplateSpec,
  /* Minimum number of seconds for which a newly created pod should be ready without any of its container crashing, for it to be considered available. Defaults to 0 (pod will be considered available as soon as it is ready) */
  @named("minReadySeconds") minReadySeconds: Option[Int] = scala.None,
  /* Indicates that the deployment is paused. */
  @named("paused") paused: Option[Boolean] = scala.None,
  /* The maximum time in seconds for a deployment to make progress before it is considered to be failed. The deployment controller will continue to process failed deployments and a condition with a ProgressDeadlineExceeded reason will be surfaced in the deployment status. Note that progress will not be estimated during the time a deployment is paused. Defaults to 600s. */
  @named("progressDeadlineSeconds") progressDeadlineSeconds: Option[Int] = scala.None,
  /* Number of desired pods. This is a pointer to distinguish between explicit zero and not specified. Defaults to 1. */
  @named("replicas") replicas: Option[Int] = scala.None,
  /* The number of old ReplicaSets to retain to allow rollback. This is a pointer to distinguish between explicit zero and not specified. Defaults to 10. */
  @named("revisionHistoryLimit") revisionHistoryLimit: Option[Int] = scala.None,
  /* The deployment strategy to use to replace existing pods with new ones. */
  @named("strategy") strategy: Option[DeploymentStrategy] = scala.None
)

