/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kubescala.apps.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * DeploymentStrategy describes how to replace existing pods with new ones.
   */
case class DeploymentStrategy(
  /* Rolling update config params. Present only if DeploymentStrategyType = RollingUpdate. */
  @named("rollingUpdate") rollingUpdate: Option[RollingUpdateDeployment] = scala.None,
  /* Type of deployment. Can be \"Recreate\" or \"RollingUpdate\". Default is RollingUpdate.  Possible enum values:  - `\"Recreate\"` Kill all existing pods before creating new ones.  - `\"RollingUpdate\"` Replace the old ReplicaSets by new one using rolling update i.e gradually scale down the old ReplicaSets and scale up the new one. */
  @named("type") `type`: Option[DeploymentStrategyEnums.Type] = scala.None
)

object DeploymentStrategyEnums:
  enum Type:
    case `Recreate`
    case `RollingUpdate`

  object Type:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given typeCodec: JsonValueCodec[Type] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "Recreate" => "Recreate"
            case "RollingUpdate" => "RollingUpdate"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end DeploymentStrategyEnums
