/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kubescala.apps.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * ReplicaSetStatus represents the current status of a ReplicaSet.
   */
case class ReplicaSetStatus(
  /* Replicas is the most recently observed number of non-terminating pods. More info: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset */
  @named("replicas") replicas: Int,
  /* The number of available non-terminating pods (ready for at least minReadySeconds) for this replica set. */
  @named("availableReplicas") availableReplicas: Option[Int] = scala.None,
  /* Represents the latest available observations of a replica set's current state. */
  @named("conditions") conditions: Option[Seq[ReplicaSetCondition]] = scala.None,
  /* The number of non-terminating pods that have labels matching the labels of the pod template of the replicaset. */
  @named("fullyLabeledReplicas") fullyLabeledReplicas: Option[Int] = scala.None,
  /* ObservedGeneration reflects the generation of the most recently observed ReplicaSet. */
  @named("observedGeneration") observedGeneration: Option[Long] = scala.None,
  /* The number of non-terminating pods targeted by this ReplicaSet with a Ready Condition. */
  @named("readyReplicas") readyReplicas: Option[Int] = scala.None,
  /* The number of terminating pods for this replica set. Terminating pods have a non-null .metadata.deletionTimestamp and have not yet reached the Failed or Succeeded .status.phase.  This is an alpha field. Enable DeploymentReplicaSetTerminatingReplicas to be able to use this field. */
  @named("terminatingReplicas") terminatingReplicas: Option[Int] = scala.None
)

