/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kubescala.apps.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * StatefulSetStatus represents the current state of a StatefulSet.
   */
case class StatefulSetStatus(
  /* replicas is the number of Pods created by the StatefulSet controller. */
  @named("replicas") replicas: Int,
  /* Total number of available pods (ready for at least minReadySeconds) targeted by this statefulset. */
  @named("availableReplicas") availableReplicas: Option[Int] = scala.None,
  /* collisionCount is the count of hash collisions for the StatefulSet. The StatefulSet controller uses this field as a collision avoidance mechanism when it needs to create the name for the newest ControllerRevision. */
  @named("collisionCount") collisionCount: Option[Int] = scala.None,
  /* Represents the latest available observations of a statefulset's current state. */
  @named("conditions") conditions: Option[Seq[StatefulSetCondition]] = scala.None,
  /* currentReplicas is the number of Pods created by the StatefulSet controller from the StatefulSet version indicated by currentRevision. */
  @named("currentReplicas") currentReplicas: Option[Int] = scala.None,
  /* currentRevision, if not empty, indicates the version of the StatefulSet used to generate Pods in the sequence [0,currentReplicas). */
  @named("currentRevision") currentRevision: Option[String] = scala.None,
  /* observedGeneration is the most recent generation observed for this StatefulSet. It corresponds to the StatefulSet's generation, which is updated on mutation by the API Server. */
  @named("observedGeneration") observedGeneration: Option[Long] = scala.None,
  /* readyReplicas is the number of pods created for this StatefulSet with a Ready Condition. */
  @named("readyReplicas") readyReplicas: Option[Int] = scala.None,
  /* updateRevision, if not empty, indicates the version of the StatefulSet used to generate Pods in the sequence [replicas-updatedReplicas,replicas) */
  @named("updateRevision") updateRevision: Option[String] = scala.None,
  /* updatedReplicas is the number of Pods created by the StatefulSet controller from the StatefulSet version indicated by updateRevision. */
  @named("updatedReplicas") updatedReplicas: Option[Int] = scala.None
)

