/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kubescala.apps.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * StatefulSetUpdateStrategy indicates the strategy that the StatefulSet controller will use to perform updates. It includes any additional parameters necessary to perform the update for the indicated strategy.
   */
case class StatefulSetUpdateStrategy(
  /* RollingUpdate is used to communicate parameters when Type is RollingUpdateStatefulSetStrategyType. */
  @named("rollingUpdate") rollingUpdate: Option[RollingUpdateStatefulSetStrategy] = scala.None,
  /* Type indicates the type of the StatefulSetUpdateStrategy. Default is RollingUpdate.  Possible enum values:  - `\"OnDelete\"` triggers the legacy behavior. Version tracking and ordered rolling restarts are disabled. Pods are recreated from the StatefulSetSpec when they are manually deleted. When a scale operation is performed with this strategy,specification version indicated by the StatefulSet's currentRevision.  - `\"RollingUpdate\"` indicates that update will be applied to all Pods in the StatefulSet with respect to the StatefulSet ordering constraints. When a scale operation is performed with this strategy, new Pods will be created from the specification version indicated by the StatefulSet's updateRevision. */
  @named("type") `type`: Option[StatefulSetUpdateStrategyEnums.Type] = scala.None
)

object StatefulSetUpdateStrategyEnums:
  enum Type:
    case `OnDelete`
    case `RollingUpdate`

  object Type:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given typeCodec: JsonValueCodec[Type] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "OnDelete" => "OnDelete"
            case "RollingUpdate" => "RollingUpdate"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end StatefulSetUpdateStrategyEnums
