/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.authentication.v1.api

import kubescala.authentication.v1.models.APIResourceList
import kubescala.authentication.v1.models.SelfSubjectReview
import kubescala.authentication.v1.models.TokenReview
import kubescala.authentication.v1.JsonSupport.{*, given}
import kubescala.authentication.v1.FormSerializable
import kubescala.authentication.v1.FormStyleFormat
import kubescala.authentication.v1.HeaderSerializable
import kubescala.authentication.v1.ApiKeyLocation
import kubescala.authentication.v1.PathStyleFormat
import kubescala.authentication.v1.PathSerializable
import kubescala.authentication.v1.CookieSerializable
import kubescala.authentication.v1.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object AuthenticationV1Api:
  def apply(baseUrl: String = "http://localhost"): AuthenticationV1Api[
    kubescala.authentication.v1.Authorization.NoAuthorization.type
  ] = AuthenticationV1Api(
    baseUrl,
    kubescala.authentication.v1.Authorization.NoAuthorization
  )
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): AuthenticationV1Api[kubescala.authentication.v1.Authorization.BasicAuth] =
    AuthenticationV1Api(
      baseUrl,
      kubescala.authentication.v1.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): AuthenticationV1Api[kubescala.authentication.v1.Authorization.ApiKey] =
    AuthenticationV1Api(
      baseUrl,
      kubescala.authentication.v1.Authorization.ApiKey(apiKey)
    )

  def withBearerTokenAuth(baseUrl: String, token: String): AuthenticationV1Api[
    kubescala.authentication.v1.Authorization.BearerToken
  ] =
    AuthenticationV1Api(
      baseUrl,
      kubescala.authentication.v1.Authorization.BearerToken(token)
    )

case class AuthenticationV1Api[
    Auth <: kubescala.authentication.v1.Authorization
] private (
    baseUrl: String,
    authConfig: kubescala.authentication.v1.Authorization
):
  def withBasicAuth(
      username: String,
      password: String
  ): AuthenticationV1Api[kubescala.authentication.v1.Authorization.BasicAuth] =
    copy(authConfig =
      kubescala.authentication.v1.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      apiKey: String
  ): AuthenticationV1Api[kubescala.authentication.v1.Authorization.ApiKey] =
    copy(authConfig = kubescala.authentication.v1.Authorization.ApiKey(apiKey))

  def withNoAuth: AuthenticationV1Api[
    kubescala.authentication.v1.Authorization.NoAuthorization.type
  ] =
    copy(authConfig = kubescala.authentication.v1.Authorization.NoAuthorization)

  def withBearerTokenAuth(token: String): AuthenticationV1Api[
    kubescala.authentication.v1.Authorization.BearerToken
  ] =
    copy(authConfig =
      kubescala.authentication.v1.Authorization.BearerToken(token)
    )

  /** create a SelfSubjectReview
    *
    * Expected answers: code 200 : SelfSubjectReview (OK) code 201 :
    * SelfSubjectReview (Created) code 202 : SelfSubjectReview (Accepted) code
    * 401 : (Unauthorized)
    *
    * @param selfSubjectReview
    * @param dryRun
    *   When present, indicates that modifications should not be persisted. An
    *   invalid or unrecognized dryRun directive will result in an error
    *   response and no further processing of the request. Valid values are: -
    *   All: all dry run stages will be processed
    * @param fieldManager
    *   fieldManager is a name associated with the actor or entity that is
    *   making these changes. The value must be less than or 128 characters
    *   long, and only contain printable characters, as defined by
    *   https://golang.org/pkg/unicode/#IsPrint.
    * @param fieldValidation
    *   fieldValidation instructs the server on how to handle objects in the
    *   request (POST/PUT/PATCH) containing unknown or duplicate fields. Valid
    *   values are: - Ignore: This will ignore any unknown fields that are
    *   silently dropped from the object, and will ignore all but the last
    *   duplicate field that the decoder encounters. This is the default
    *   behavior prior to v1.23. - Warn: This will send a warning via the
    *   standard warning response header for each unknown field that is dropped
    *   from the object, and for each duplicate field that is encountered. The
    *   request will still succeed if there are no other errors, and will only
    *   persist the last of any duplicate fields. This is the default in v1.23+ -
    *   Strict: This will fail the request with a BadRequest error if any
    *   unknown fields would be dropped from the object, or if any duplicate
    *   fields are present. The error returned from the server will contain all
    *   unknown and duplicate fields encountered.
    * @param pretty
    *   If 'true', then the output is pretty printed. Defaults to 'false' unless
    *   the user-agent indicates a browser or command-line HTTP tool (curl and
    *   wget).
    */
  def createAuthenticationV1SelfSubjectReview(
      selfSubjectReview: SelfSubjectReview,
      dryRun: Option[String] = scala.None,
      fieldManager: Option[String] = scala.None,
      fieldValidation: Option[String] = scala.None,
      pretty: Option[String] = scala.None
  ): sttp.client4.Request[
    Either[ResponseException[String], SelfSubjectReview]
  ] =
    val requestURL =
      uri"$baseUrl/apis/authentication.k8s.io/v1/selfsubjectreviews"
        .addParams(
          FormSerializable
            .serialize("dryRun", dryRun, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable.serialize(
            "fieldManager",
            fieldManager,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "fieldValidation",
            fieldValidation,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("pretty", pretty, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .body(asJson(selfSubjectReview))
      .response(asJson[SelfSubjectReview])

  /** create a TokenReview
    *
    * Expected answers: code 200 : TokenReview (OK) code 201 : TokenReview
    * (Created) code 202 : TokenReview (Accepted) code 401 : (Unauthorized)
    *
    * @param tokenReview
    * @param dryRun
    *   When present, indicates that modifications should not be persisted. An
    *   invalid or unrecognized dryRun directive will result in an error
    *   response and no further processing of the request. Valid values are: -
    *   All: all dry run stages will be processed
    * @param fieldManager
    *   fieldManager is a name associated with the actor or entity that is
    *   making these changes. The value must be less than or 128 characters
    *   long, and only contain printable characters, as defined by
    *   https://golang.org/pkg/unicode/#IsPrint.
    * @param fieldValidation
    *   fieldValidation instructs the server on how to handle objects in the
    *   request (POST/PUT/PATCH) containing unknown or duplicate fields. Valid
    *   values are: - Ignore: This will ignore any unknown fields that are
    *   silently dropped from the object, and will ignore all but the last
    *   duplicate field that the decoder encounters. This is the default
    *   behavior prior to v1.23. - Warn: This will send a warning via the
    *   standard warning response header for each unknown field that is dropped
    *   from the object, and for each duplicate field that is encountered. The
    *   request will still succeed if there are no other errors, and will only
    *   persist the last of any duplicate fields. This is the default in v1.23+ -
    *   Strict: This will fail the request with a BadRequest error if any
    *   unknown fields would be dropped from the object, or if any duplicate
    *   fields are present. The error returned from the server will contain all
    *   unknown and duplicate fields encountered.
    * @param pretty
    *   If 'true', then the output is pretty printed. Defaults to 'false' unless
    *   the user-agent indicates a browser or command-line HTTP tool (curl and
    *   wget).
    */
  def createAuthenticationV1TokenReview(
      tokenReview: TokenReview,
      dryRun: Option[String] = scala.None,
      fieldManager: Option[String] = scala.None,
      fieldValidation: Option[String] = scala.None,
      pretty: Option[String] = scala.None
  ): sttp.client4.Request[Either[ResponseException[String], TokenReview]] =
    val requestURL =
      uri"$baseUrl/apis/authentication.k8s.io/v1/tokenreviews"
        .addParams(
          FormSerializable
            .serialize("dryRun", dryRun, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable.serialize(
            "fieldManager",
            fieldManager,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "fieldValidation",
            fieldValidation,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("pretty", pretty, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .body(asJson(tokenReview))
      .response(asJson[TokenReview])

  /** get available resources
    *
    * Expected answers: code 200 : APIResourceList (OK) code 401 :
    * (Unauthorized)
    */
  def getAuthenticationV1APIResources: sttp.client4.Request[
    Either[ResponseException[String], APIResourceList]
  ] =
    val requestURL =
      uri"$baseUrl/apis/authentication.k8s.io/v1/"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .response(asJson[APIResourceList])

end AuthenticationV1Api
