/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.autoscaling.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** CrossVersionObjectReference contains enough information to let you identify
  * the referred resource.
  */
case class CrossVersionObjectReference(
    /* kind is the kind of the referent; More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    @named("kind") kind: String,
    /* name is the name of the referent; More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names */
    @named("name") name: String,
    /* apiVersion is the API version of the referent */
    @named("apiVersion") apiVersion: Option[String] = scala.None
)
