/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.autoscaling.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** specification of a horizontal pod autoscaler.
  */
case class HorizontalPodAutoscalerSpec(
    /* maxReplicas is the upper limit for the number of pods that can be set by the autoscaler; cannot be smaller than MinReplicas. */
    @named("maxReplicas") maxReplicas: Int,
    /* reference to scaled resource; horizontal pod autoscaler will learn the current resource consumption and will set the desired number of pods by using its Scale subresource. */
    @named("scaleTargetRef") scaleTargetRef: CrossVersionObjectReference,
    /* minReplicas is the lower limit for the number of replicas to which the autoscaler can scale down.  It defaults to 1 pod.  minReplicas is allowed to be 0 if the alpha feature gate HPAScaleToZero is enabled and at least one Object or External metric is configured.  Scaling is active as long as at least one metric value is available. */
    @named("minReplicas") minReplicas: Option[Int] = scala.None,
    /* targetCPUUtilizationPercentage is the target average CPU utilization (represented as a percentage of requested CPU) over all the pods; if not specified the default autoscaling policy will be used. */
    @named(
      "targetCPUUtilizationPercentage"
    ) targetCPUUtilizationPercentage: Option[Int] = scala.None
)
