/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.autoscaling.v1.models

import java.time.OffsetDateTime
import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** current status of a horizontal pod autoscaler
  */
case class HorizontalPodAutoscalerStatus(
    /* currentReplicas is the current number of replicas of pods managed by this autoscaler. */
    @named("currentReplicas") currentReplicas: Int,
    /* desiredReplicas is the  desired number of replicas of pods managed by this autoscaler. */
    @named("desiredReplicas") desiredReplicas: Int,
    /* currentCPUUtilizationPercentage is the current average CPU utilization over all pods, represented as a percentage of requested CPU, e.g. 70 means that an average pod is using now 70% of its requested CPU. */
    @named(
      "currentCPUUtilizationPercentage"
    ) currentCPUUtilizationPercentage: Option[Int] = scala.None,
    /* lastScaleTime is the last time the HorizontalPodAutoscaler scaled the number of pods; used by the autoscaler to control how often the number of pods is changed. */
    @named("lastScaleTime") lastScaleTime: Option[OffsetDateTime] = scala.None,
    /* observedGeneration is the most recent generation observed by this autoscaler. */
    @named("observedGeneration") observedGeneration: Option[Long] = scala.None
)
