/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.discovery

import kubescala.discovery.models.*
import java.time.*
import com.github.plokhotnyuk.jsoniter_scala.macros.*
import com.github.plokhotnyuk.jsoniter_scala.core.*
import com.github.plokhotnyuk.jsoniter_scala.circe.JsoniterScalaCodec.*

object JsonSupport extends AdditionalTypeSerializers:
  inline given CodecMakerConfig = CodecMakerConfig.withAllowRecursiveTypes(true)

  inline def deriveJsonCodec[A](using
      inline config: CodecMakerConfig
  ): JsonValueCodec[A] =
    JsonCodecMaker.make(config)

  given aPIGroupCodec: JsonValueCodec[APIGroup] = deriveJsonCodec
