/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.rbac.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** ClusterRole is a cluster level, logical grouping of PolicyRules that can be
  * referenced as a unit by a RoleBinding or ClusterRoleBinding.
  */
case class ClusterRole(
    /* AggregationRule is an optional field that describes how to build the Rules for this ClusterRole. If AggregationRule is set, then the Rules are controller managed and direct changes to Rules will be stomped by the controller. */
    @named("aggregationRule") aggregationRule: Option[AggregationRule] =
      scala.None,
    /* APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
    @named("apiVersion") apiVersion: Option[String] = scala.None,
    /* Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    @named("kind") kind: Option[String] = scala.None,
    /* Standard object's metadata. */
    @named("metadata") metadata: Option[ObjectMeta] = scala.None,
    /* Rules holds all the PolicyRules for this ClusterRole */
    @named("rules") rules: Option[Seq[PolicyRule]] = scala.None
)
