/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.rbac.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** ClusterRoleBinding references a ClusterRole, but not contain it. It can
  * reference a ClusterRole in the global namespace, and adds who information
  * via Subject.
  */
case class ClusterRoleBinding(
    /* RoleRef can only reference a ClusterRole in the global namespace. If the RoleRef cannot be resolved, the Authorizer must return an error. This field is immutable. */
    @named("roleRef") roleRef: RoleRef,
    /* APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
    @named("apiVersion") apiVersion: Option[String] = scala.None,
    /* Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    @named("kind") kind: Option[String] = scala.None,
    /* Standard object's metadata. */
    @named("metadata") metadata: Option[ObjectMeta] = scala.None,
    /* Subjects holds references to the objects the role applies to. */
    @named("subjects") subjects: Option[Seq[Subject]] = scala.None
)
