/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.rbac.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** RoleRef contains information that points to the role being used
  */
case class RoleRef(
    /* APIGroup is the group for the resource being referenced */
    @named("apiGroup") apiGroup: String,
    /* Kind is the type of resource being referenced */
    @named("kind") kind: String,
    /* Name is the name of resource being referenced */
    @named("name") name: String
)
