/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** AppArmorProfile defines a pod or container's AppArmor settings.
  */
case class AppArmorProfile(
    /* type indicates which kind of AppArmor profile will be applied. Valid options are:   Localhost - a profile pre-loaded on the node.   RuntimeDefault - the container runtime's default profile.   Unconfined - no AppArmor enforcement.  Possible enum values:  - `\"Localhost\"` indicates that a profile pre-loaded on the node should be used.  - `\"RuntimeDefault\"` indicates that the container runtime's default AppArmor profile should be used.  - `\"Unconfined\"` indicates that no AppArmor profile should be enforced. */
    @named("type") `type`: AppArmorProfileEnums.Type,
    /* localhostProfile indicates a profile loaded on the node that should be used. The profile must be preconfigured on the node to work. Must match the loaded name of the profile. Must be set if and only if type is \"Localhost\". */
    @named("localhostProfile") localhostProfile: Option[String] = scala.None
)

object AppArmorProfileEnums:
  enum Type:
    case `Localhost`
    case `RuntimeDefault`
    case `Unconfined`

  object Type:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given typeCodec: JsonValueCodec[Type] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "Localhost"      => "Localhost"
            case "RuntimeDefault" => "RuntimeDefault"
            case "Unconfined"     => "Unconfined"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end AppArmorProfileEnums
