/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Adds and removes POSIX capabilities from running containers.
  */
case class Capabilities(
    /* Added capabilities */
    @named("add") add: Option[Seq[String]] = scala.None,
    /* Removed capabilities */
    @named("drop") drop: Option[Seq[String]] = scala.None
)
