/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Selects a key from a ConfigMap.
  */
case class ConfigMapKeySelector(
    /* The key to select. */
    @named("key") key: String,
    /* Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names */
    @named("name") name: Option[String] = scala.None,
    /* Specify whether the ConfigMap or its key must be defined */
    @named("optional") optional: Option[Boolean] = scala.None
)
