/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Adapts a ConfigMap into a projected volume. The contents of the target
  * ConfigMap's Data field will be presented in a projected volume as files
  * using the keys in the Data field as the file names, unless the items element
  * is populated with specific mappings of keys to paths. Note that this is
  * identical to a configmap volume source without the default mode.
  */
case class ConfigMapProjection(
    /* items if unspecified, each key-value pair in the Data field of the referenced ConfigMap will be projected into the volume as a file whose name is the key and content is the value. If specified, the listed keys will be projected into the specified paths, and unlisted keys will not be present. If a key is specified which is not present in the ConfigMap, the volume setup will error unless it is marked optional. Paths must be relative and may not contain the '..' path or start with '..'. */
    @named("items") items: Option[Seq[KeyToPath]] = scala.None,
    /* Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names */
    @named("name") name: Option[String] = scala.None,
    /* optional specify whether the ConfigMap or its keys must be defined */
    @named("optional") optional: Option[Boolean] = scala.None
)
