/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** ContainerResizePolicy represents resource resize policy for the container.
  */
case class ContainerResizePolicy(
    /* Name of the resource to which this resource resize policy applies. Supported values: cpu, memory. */
    @named("resourceName") resourceName: String,
    /* Restart policy to apply when specified resource is resized. If not specified, it defaults to NotRequired. */
    @named("restartPolicy") restartPolicy: String
)
