/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** CronJobSpec describes how the job execution will look like and when it will
  * actually run.
  */
case class CronJobSpec(
    /* Specifies the job that will be created when executing a CronJob. */
    @named("jobTemplate") jobTemplate: JobTemplateSpec,
    /* The schedule in Cron format, see https://en.wikipedia.org/wiki/Cron. */
    @named("schedule") schedule: String,
    /* Specifies how to treat concurrent executions of a Job. Valid values are:  - \"Allow\" (default): allows CronJobs to run concurrently; - \"Forbid\": forbids concurrent runs, skipping next run if previous run hasn't finished yet; - \"Replace\": cancels currently running job and replaces it with a new one  Possible enum values:  - `\"Allow\"` allows CronJobs to run concurrently.  - `\"Forbid\"` forbids concurrent runs, skipping next run if previous hasn't finished yet.  - `\"Replace\"` cancels currently running job and replaces it with a new one. */
    @named("concurrencyPolicy") concurrencyPolicy: Option[
      CronJobSpecEnums.ConcurrencyPolicy
    ] = scala.None,
    /* The number of failed finished jobs to retain. Value must be non-negative integer. Defaults to 1. */
    @named("failedJobsHistoryLimit") failedJobsHistoryLimit: Option[Int] =
      scala.None,
    /* Optional deadline in seconds for starting the job if it misses scheduled time for any reason.  Missed jobs executions will be counted as failed ones. */
    @named("startingDeadlineSeconds") startingDeadlineSeconds: Option[Long] =
      scala.None,
    /* The number of successful finished jobs to retain. Value must be non-negative integer. Defaults to 3. */
    @named("successfulJobsHistoryLimit") successfulJobsHistoryLimit: Option[
      Int
    ] = scala.None,
    /* This flag tells the controller to suspend subsequent executions, it does not apply to already started executions.  Defaults to false. */
    @named("suspend") suspend: Option[Boolean] = scala.None,
    /* The time zone name for the given schedule, see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones. If not specified, this will default to the time zone of the kube-controller-manager process. The set of valid time zone names and the time zone offset is loaded from the system-wide time zone database by the API server during CronJob validation and the controller manager during execution. If no system-wide time zone database can be found a bundled version of the database is used instead. If the time zone name becomes invalid during the lifetime of a CronJob or due to a change in host configuration, the controller will stop creating new new Jobs and will create a system event with the reason UnknownTimeZone. More information can be found in https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#time-zones */
    @named("timeZone") timeZone: Option[String] = scala.None
)

object CronJobSpecEnums:
  enum ConcurrencyPolicy:
    case `Allow`
    case `Forbid`
    case `Replace`

  object ConcurrencyPolicy:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given concurrencyPolicyCodec: JsonValueCodec[ConcurrencyPolicy] =
      JsonCodecMaker.make {
        CodecMakerConfig
          .withAdtLeafClassNameMapper { x =>
            JsonCodecMaker.simpleClassName(x) match
              case "Allow"   => "Allow"
              case "Forbid"  => "Forbid"
              case "Replace" => "Replace"
          }
          .withDiscriminatorFieldName(scala.None)
      }
end CronJobSpecEnums
