/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import java.time.OffsetDateTime
import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** CronJobStatus represents the current state of a cron job.
  */
case class CronJobStatus(
    /* A list of pointers to currently running jobs. */
    @named("active") active: Option[Seq[ObjectReference]] = scala.None,
    /* Information when was the last time the job was successfully scheduled. */
    @named("lastScheduleTime") lastScheduleTime: Option[OffsetDateTime] =
      scala.None,
    /* Information when was the last time the job successfully completed. */
    @named("lastSuccessfulTime") lastSuccessfulTime: Option[OffsetDateTime] =
      scala.None
)
