/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Represents downward API info for projecting into a projected volume. Note
  * that this is identical to a downwardAPI volume source without the default
  * mode.
  */
case class DownwardAPIProjection(
    /* Items is a list of DownwardAPIVolume file */
    @named("items") items: Option[Seq[DownwardAPIVolumeFile]] = scala.None
)
