/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** DownwardAPIVolumeSource represents a volume containing downward API info.
  * Downward API volumes support ownership management and SELinux relabeling.
  */
case class DownwardAPIVolumeSource(
    /* Optional: mode bits to use on created files by default. Must be a Optional: mode bits used to set permissions on created files by default. Must be an octal value between 0000 and 0777 or a decimal value between 0 and 511. YAML accepts both octal and decimal values, JSON requires decimal values for mode bits. Defaults to 0644. Directories within the path are not affected by this setting. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set. */
    @named("defaultMode") defaultMode: Option[Int] = scala.None,
    /* Items is a list of downward API volume file */
    @named("items") items: Option[Seq[DownwardAPIVolumeFile]] = scala.None
)
