/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** EnvFromSource represents the source of a set of ConfigMaps or Secrets
  */
case class EnvFromSource(
    /* The ConfigMap to select from */
    @named("configMapRef") configMapRef: Option[ConfigMapEnvSource] =
      scala.None,
    /* Optional text to prepend to the name of each environment variable. May consist of any printable ASCII characters except '='. */
    @named("prefix") prefix: Option[String] = scala.None,
    /* The Secret to select from */
    @named("secretRef") secretRef: Option[SecretEnvSource] = scala.None
)
