/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** EnvVar represents an environment variable present in a Container.
  */
case class EnvVar(
    /* Name of the environment variable. May consist of any printable ASCII characters except '='. */
    @named("name") name: String,
    /* Variable references $(VAR_NAME) are expanded using the previously defined environment variables in the container and any service environment variables. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. \"$$(VAR_NAME)\" will produce the string literal \"$(VAR_NAME)\". Escaped references will never be expanded, regardless of whether the variable exists or not. Defaults to \"\". */
    @named("value") value: Option[String] = scala.None,
    /* Source for the environment variable's value. Cannot be used if value is not empty. */
    @named("valueFrom") valueFrom: Option[EnvVarSource] = scala.None
)
