/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** EnvVarSource represents a source for the value of an EnvVar.
  */
case class EnvVarSource(
    /* Selects a key of a ConfigMap. */
    @named("configMapKeyRef") configMapKeyRef: Option[ConfigMapKeySelector] =
      scala.None,
    /* Selects a field of the pod: supports metadata.name, metadata.namespace, `metadata.labels['<KEY>']`, `metadata.annotations['<KEY>']`, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs. */
    @named("fieldRef") fieldRef: Option[ObjectFieldSelector] = scala.None,
    /* FileKeyRef selects a key of the env file. Requires the EnvFiles feature gate to be enabled. */
    @named("fileKeyRef") fileKeyRef: Option[FileKeySelector] = scala.None,
    /* Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported. */
    @named("resourceFieldRef") resourceFieldRef: Option[ResourceFieldSelector] =
      scala.None,
    /* Selects a key of a secret in the pod's namespace */
    @named("secretKeyRef") secretKeyRef: Option[SecretKeySelector] = scala.None
)
