/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** FileKeySelector selects a key of the env file.
  */
case class FileKeySelector(
    /* The key within the env file. An invalid key will prevent the pod from starting. The keys defined within a source may consist of any printable ASCII characters except '='. During Alpha stage of the EnvFiles feature gate, the key size is limited to 128 characters. */
    @named("key") key: String,
    /* The path within the volume from which to select the file. Must be relative and may not contain the '..' path or start with '..'. */
    @named("path") path: String,
    /* The name of the volume mount containing the env file. */
    @named("volumeName") volumeName: String,
    /* Specify whether the file or its key must be defined. If the file or key does not exist, then the env var is not published. If optional is set to true and the specified key does not exist, the environment variable will not be set in the Pod's containers.  If optional is set to false and the specified key does not exist, an error will be returned during Pod creation. */
    @named("optional") optional: Option[Boolean] = scala.None
)
