/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** HostAlias holds the mapping between IP and hostnames that will be injected
  * as an entry in the pod's hosts file.
  */
case class HostAlias(
    /* IP address of the host file entry. */
    @named("ip") ip: String,
    /* Hostnames for the above IP address. */
    @named("hostnames") hostnames: Option[Seq[String]] = scala.None
)
