/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import java.time.OffsetDateTime
import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** JobCondition describes current state of a job.
  */
case class JobCondition(
    /* Status of the condition, one of True, False, Unknown. */
    @named("status") status: String,
    /* Type of job condition, Complete or Failed. */
    @named("type") `type`: String,
    /* Last time the condition was checked. */
    @named("lastProbeTime") lastProbeTime: Option[OffsetDateTime] = scala.None,
    /* Last time the condition transit from one status to another. */
    @named("lastTransitionTime") lastTransitionTime: Option[OffsetDateTime] =
      scala.None,
    /* Human readable message indicating details about last transition. */
    @named("message") message: Option[String] = scala.None,
    /* (brief) reason for the condition's last transition. */
    @named("reason") reason: Option[String] = scala.None
)
