/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Lifecycle describes actions that the management system should take in
  * response to container lifecycle events. For the PostStart and PreStop
  * lifecycle handlers, management of the container blocks until the action is
  * complete, unless the container process fails, in which case the handler is
  * aborted.
  */
case class Lifecycle(
    /* PostStart is called immediately after a container is created. If the handler fails, the container is terminated and restarted according to its restart policy. Other management of the container blocks until the hook completes. More info: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks */
    @named("postStart") postStart: Option[LifecycleHandler] = scala.None,
    /* PreStop is called immediately before a container is terminated due to an API request or management event such as liveness/startup probe failure, preemption, resource contention, etc. The handler is not called if the container crashes or exits. The Pod's termination grace period countdown begins before the PreStop hook is executed. Regardless of the outcome of the handler, the container will eventually terminate within the Pod's termination grace period (unless delayed by finalizers). Other management of the container blocks until the hook completes or until the termination grace period is reached. More info: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks */
    @named("preStop") preStop: Option[LifecycleHandler] = scala.None,
    /* StopSignal defines which signal will be sent to a container when it is being stopped. If not specified, the default is defined by the container runtime in use. StopSignal can only be set for Pods with a non-empty .spec.os.name  Possible enum values:  - `\"SIGABRT\"`  - `\"SIGALRM\"`  - `\"SIGBUS\"`  - `\"SIGCHLD\"`  - `\"SIGCLD\"`  - `\"SIGCONT\"`  - `\"SIGFPE\"`  - `\"SIGHUP\"`  - `\"SIGILL\"`  - `\"SIGINT\"`  - `\"SIGIO\"`  - `\"SIGIOT\"`  - `\"SIGKILL\"`  - `\"SIGPIPE\"`  - `\"SIGPOLL\"`  - `\"SIGPROF\"`  - `\"SIGPWR\"`  - `\"SIGQUIT\"`  - `\"SIGRTMAX\"`  - `\"SIGRTMAX-1\"`  - `\"SIGRTMAX-10\"`  - `\"SIGRTMAX-11\"`  - `\"SIGRTMAX-12\"`  - `\"SIGRTMAX-13\"`  - `\"SIGRTMAX-14\"`  - `\"SIGRTMAX-2\"`  - `\"SIGRTMAX-3\"`  - `\"SIGRTMAX-4\"`  - `\"SIGRTMAX-5\"`  - `\"SIGRTMAX-6\"`  - `\"SIGRTMAX-7\"`  - `\"SIGRTMAX-8\"`  - `\"SIGRTMAX-9\"`  - `\"SIGRTMIN\"`  - `\"SIGRTMIN+1\"`  - `\"SIGRTMIN+10\"`  - `\"SIGRTMIN+11\"`  - `\"SIGRTMIN+12\"`  - `\"SIGRTMIN+13\"`  - `\"SIGRTMIN+14\"`  - `\"SIGRTMIN+15\"`  - `\"SIGRTMIN+2\"`  - `\"SIGRTMIN+3\"`  - `\"SIGRTMIN+4\"`  - `\"SIGRTMIN+5\"`  - `\"SIGRTMIN+6\"`  - `\"SIGRTMIN+7\"`  - `\"SIGRTMIN+8\"`  - `\"SIGRTMIN+9\"`  - `\"SIGSEGV\"`  - `\"SIGSTKFLT\"`  - `\"SIGSTOP\"`  - `\"SIGSYS\"`  - `\"SIGTERM\"`  - `\"SIGTRAP\"`  - `\"SIGTSTP\"`  - `\"SIGTTIN\"`  - `\"SIGTTOU\"`  - `\"SIGURG\"`  - `\"SIGUSR1\"`  - `\"SIGUSR2\"`  - `\"SIGVTALRM\"`  - `\"SIGWINCH\"`  - `\"SIGXCPU\"`  - `\"SIGXFSZ\"` */
    @named("stopSignal") stopSignal: Option[LifecycleEnums.StopSignal] =
      scala.None
)

object LifecycleEnums:
  enum StopSignal:
    case `SIGABRT`
    case `SIGALRM`
    case `SIGBUS`
    case `SIGCHLD`
    case `SIGCLD`
    case `SIGCONT`
    case `SIGFPE`
    case `SIGHUP`
    case `SIGILL`
    case `SIGINT`
    case `SIGIO`
    case `SIGIOT`
    case `SIGKILL`
    case `SIGPIPE`
    case `SIGPOLL`
    case `SIGPROF`
    case `SIGPWR`
    case `SIGQUIT`
    case `SIGRTMAX`
    case `SIGRTMAX-1`
    case `SIGRTMAX-10`
    case `SIGRTMAX-11`
    case `SIGRTMAX-12`
    case `SIGRTMAX-13`
    case `SIGRTMAX-14`
    case `SIGRTMAX-2`
    case `SIGRTMAX-3`
    case `SIGRTMAX-4`
    case `SIGRTMAX-5`
    case `SIGRTMAX-6`
    case `SIGRTMAX-7`
    case `SIGRTMAX-8`
    case `SIGRTMAX-9`
    case `SIGRTMIN`
    case `SIGRTMIN+1`
    case `SIGRTMIN+10`
    case `SIGRTMIN+11`
    case `SIGRTMIN+12`
    case `SIGRTMIN+13`
    case `SIGRTMIN+14`
    case `SIGRTMIN+15`
    case `SIGRTMIN+2`
    case `SIGRTMIN+3`
    case `SIGRTMIN+4`
    case `SIGRTMIN+5`
    case `SIGRTMIN+6`
    case `SIGRTMIN+7`
    case `SIGRTMIN+8`
    case `SIGRTMIN+9`
    case `SIGSEGV`
    case `SIGSTKFLT`
    case `SIGSTOP`
    case `SIGSYS`
    case `SIGTERM`
    case `SIGTRAP`
    case `SIGTSTP`
    case `SIGTTIN`
    case `SIGTTOU`
    case `SIGURG`
    case `SIGUSR1`
    case `SIGUSR2`
    case `SIGVTALRM`
    case `SIGWINCH`
    case `SIGXCPU`
    case `SIGXFSZ`

  object StopSignal:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given stopSignalCodec: JsonValueCodec[StopSignal] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "SIGABRT"     => "SIGABRT"
            case "SIGALRM"     => "SIGALRM"
            case "SIGBUS"      => "SIGBUS"
            case "SIGCHLD"     => "SIGCHLD"
            case "SIGCLD"      => "SIGCLD"
            case "SIGCONT"     => "SIGCONT"
            case "SIGFPE"      => "SIGFPE"
            case "SIGHUP"      => "SIGHUP"
            case "SIGILL"      => "SIGILL"
            case "SIGINT"      => "SIGINT"
            case "SIGIO"       => "SIGIO"
            case "SIGIOT"      => "SIGIOT"
            case "SIGKILL"     => "SIGKILL"
            case "SIGPIPE"     => "SIGPIPE"
            case "SIGPOLL"     => "SIGPOLL"
            case "SIGPROF"     => "SIGPROF"
            case "SIGPWR"      => "SIGPWR"
            case "SIGQUIT"     => "SIGQUIT"
            case "SIGRTMAX"    => "SIGRTMAX"
            case "SIGRTMAX-1"  => "SIGRTMAX-1"
            case "SIGRTMAX-10" => "SIGRTMAX-10"
            case "SIGRTMAX-11" => "SIGRTMAX-11"
            case "SIGRTMAX-12" => "SIGRTMAX-12"
            case "SIGRTMAX-13" => "SIGRTMAX-13"
            case "SIGRTMAX-14" => "SIGRTMAX-14"
            case "SIGRTMAX-2"  => "SIGRTMAX-2"
            case "SIGRTMAX-3"  => "SIGRTMAX-3"
            case "SIGRTMAX-4"  => "SIGRTMAX-4"
            case "SIGRTMAX-5"  => "SIGRTMAX-5"
            case "SIGRTMAX-6"  => "SIGRTMAX-6"
            case "SIGRTMAX-7"  => "SIGRTMAX-7"
            case "SIGRTMAX-8"  => "SIGRTMAX-8"
            case "SIGRTMAX-9"  => "SIGRTMAX-9"
            case "SIGRTMIN"    => "SIGRTMIN"
            case "SIGRTMIN+1"  => "SIGRTMIN+1"
            case "SIGRTMIN+10" => "SIGRTMIN+10"
            case "SIGRTMIN+11" => "SIGRTMIN+11"
            case "SIGRTMIN+12" => "SIGRTMIN+12"
            case "SIGRTMIN+13" => "SIGRTMIN+13"
            case "SIGRTMIN+14" => "SIGRTMIN+14"
            case "SIGRTMIN+15" => "SIGRTMIN+15"
            case "SIGRTMIN+2"  => "SIGRTMIN+2"
            case "SIGRTMIN+3"  => "SIGRTMIN+3"
            case "SIGRTMIN+4"  => "SIGRTMIN+4"
            case "SIGRTMIN+5"  => "SIGRTMIN+5"
            case "SIGRTMIN+6"  => "SIGRTMIN+6"
            case "SIGRTMIN+7"  => "SIGRTMIN+7"
            case "SIGRTMIN+8"  => "SIGRTMIN+8"
            case "SIGRTMIN+9"  => "SIGRTMIN+9"
            case "SIGSEGV"     => "SIGSEGV"
            case "SIGSTKFLT"   => "SIGSTKFLT"
            case "SIGSTOP"     => "SIGSTOP"
            case "SIGSYS"      => "SIGSYS"
            case "SIGTERM"     => "SIGTERM"
            case "SIGTRAP"     => "SIGTRAP"
            case "SIGTSTP"     => "SIGTSTP"
            case "SIGTTIN"     => "SIGTTIN"
            case "SIGTTOU"     => "SIGTTOU"
            case "SIGURG"      => "SIGURG"
            case "SIGUSR1"     => "SIGUSR1"
            case "SIGUSR2"     => "SIGUSR2"
            case "SIGVTALRM"   => "SIGVTALRM"
            case "SIGWINCH"    => "SIGWINCH"
            case "SIGXCPU"     => "SIGXCPU"
            case "SIGXFSZ"     => "SIGXFSZ"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end LifecycleEnums
