/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** ObjectFieldSelector selects an APIVersioned field of an object.
  */
case class ObjectFieldSelector(
    /* Path of the field to select in the specified API version. */
    @named("fieldPath") fieldPath: String,
    /* Version of the schema the FieldPath is written in terms of, defaults to \"v1\". */
    @named("apiVersion") apiVersion: Option[String] = scala.None
)
