/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** PersistentVolumeClaimVolumeSource references the user's PVC in the same
  * namespace. This volume finds the bound PV and mounts that volume for the
  * pod. A PersistentVolumeClaimVolumeSource is, essentially, a wrapper around
  * another type of volume that is owned by someone else (the system).
  */
case class PersistentVolumeClaimVolumeSource(
    /* claimName is the name of a PersistentVolumeClaim in the same namespace as the pod using this volume. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#persistentvolumeclaims */
    @named("claimName") claimName: String,
    /* readOnly Will force the ReadOnly setting in VolumeMounts. Default false. */
    @named("readOnly") readOnly: Option[Boolean] = scala.None
)
