/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** PersistentVolumeClaimTemplate is used to produce PersistentVolumeClaim
  * objects as part of an EphemeralVolumeSource.
  */
case class PersistentVolumeClaimTemplate(
    /* The specification for the PersistentVolumeClaim. The entire content is copied unchanged into the PVC that gets created from this template. The same fields as in a PersistentVolumeClaim are also valid here. */
    @named("spec") spec: PersistentVolumeClaimSpec,
    /* May contain labels and annotations that will be copied into the PVC when creating it. No other fields are allowed and will be rejected during validation. */
    @named("metadata") metadata: Option[ObjectMeta] = scala.None
)
