/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** PodFailurePolicyRule describes how a pod failure is handled when the
  * requirements are met. One of onExitCodes and onPodConditions, but not both,
  * can be used in each rule.
  */
case class PodFailurePolicyRule(
    /* Specifies the action taken on a pod failure when the requirements are satisfied. Possible values are:  - FailJob: indicates that the pod's job is marked as Failed and all   running pods are terminated. - FailIndex: indicates that the pod's index is marked as Failed and will   not be restarted. - Ignore: indicates that the counter towards the .backoffLimit is not   incremented and a replacement pod is created. - Count: indicates that the pod is handled in the default way - the   counter towards the .backoffLimit is incremented. Additional values are considered to be added in the future. Clients should react to an unknown action by skipping the rule.  Possible enum values:  - `\"Count\"` This is an action which might be taken on a pod failure - the pod failure is handled in the default way - the counter towards .backoffLimit, represented by the job's .status.failed field, is incremented.  - `\"FailIndex\"` This is an action which might be taken on a pod failure - mark the Job's index as failed to avoid restarts within this index. This action can only be used when backoffLimitPerIndex is set.  - `\"FailJob\"` This is an action which might be taken on a pod failure - mark the pod's job as Failed and terminate all running pods.  - `\"Ignore\"` This is an action which might be taken on a pod failure - the counter towards .backoffLimit, represented by the job's .status.failed field, is not incremented and a replacement pod is created. */
    @named("action") action: PodFailurePolicyRuleEnums.Action,
    /* Represents the requirement on the container exit codes. */
    @named("onExitCodes") onExitCodes: Option[
      PodFailurePolicyOnExitCodesRequirement
    ] = scala.None,
    /* Represents the requirement on the pod conditions. The requirement is represented as a list of pod condition patterns. The requirement is satisfied if at least one pattern matches an actual pod condition. At most 20 elements are allowed. */
    @named("onPodConditions") onPodConditions: Option[
      Seq[PodFailurePolicyOnPodConditionsPattern]
    ] = scala.None
)

object PodFailurePolicyRuleEnums:
  enum Action:
    case `Count`
    case `FailIndex`
    case `FailJob`
    case `Ignore`

  object Action:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given actionCodec: JsonValueCodec[Action] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "Count"     => "Count"
            case "FailIndex" => "FailIndex"
            case "FailJob"   => "FailJob"
            case "Ignore"    => "Ignore"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end PodFailurePolicyRuleEnums
