/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** PodSpec is a description of a pod.
  */
case class PodSpec(
    /* List of containers belonging to the pod. Containers cannot currently be added or removed. There must be at least one container in a Pod. Cannot be updated. */
    @named("containers") containers: Seq[Container],
    /* Optional duration in seconds the pod may be active on the node relative to StartTime before the system will actively try to mark it failed and kill associated containers. Value must be a positive integer. */
    @named("activeDeadlineSeconds") activeDeadlineSeconds: Option[Long] =
      scala.None,
    /* If specified, the pod's scheduling constraints */
    @named("affinity") affinity: Option[Affinity] = scala.None,
    /* AutomountServiceAccountToken indicates whether a service account token should be automatically mounted. */
    @named("automountServiceAccountToken") automountServiceAccountToken: Option[
      Boolean
    ] = scala.None,
    /* Specifies the DNS parameters of a pod. Parameters specified here will be merged to the generated DNS configuration based on DNSPolicy. */
    @named("dnsConfig") dnsConfig: Option[PodDNSConfig] = scala.None,
    /* Set DNS policy for the pod. Defaults to \"ClusterFirst\". Valid values are 'ClusterFirstWithHostNet', 'ClusterFirst', 'Default' or 'None'. DNS parameters given in DNSConfig will be merged with the policy selected with DNSPolicy. To have DNS options set along with hostNetwork, you have to specify DNS policy explicitly to 'ClusterFirstWithHostNet'.  Possible enum values:  - `\"ClusterFirst\"` indicates that the pod should use cluster DNS first unless hostNetwork is true, if it is available, then fall back on the default (as determined by kubelet) DNS settings.  - `\"ClusterFirstWithHostNet\"` indicates that the pod should use cluster DNS first, if it is available, then fall back on the default (as determined by kubelet) DNS settings.  - `\"Default\"` indicates that the pod should use the default (as determined by kubelet) DNS settings.  - `\"None\"` indicates that the pod should use empty DNS settings. DNS parameters such as nameservers and search paths should be defined via DNSConfig. */
    @named("dnsPolicy") dnsPolicy: Option[PodSpecEnums.DnsPolicy] = scala.None,
    /* EnableServiceLinks indicates whether information about services should be injected into pod's environment variables, matching the syntax of Docker links. Optional: Defaults to true. */
    @named("enableServiceLinks") enableServiceLinks: Option[Boolean] =
      scala.None,
    /* List of ephemeral containers run in this pod. Ephemeral containers may be run in an existing pod to perform user-initiated actions such as debugging. This list cannot be specified when creating a pod, and it cannot be modified by updating the pod spec. In order to add an ephemeral container to an existing pod, use the pod's ephemeralcontainers subresource. */
    @named("ephemeralContainers") ephemeralContainers: Option[
      Seq[EphemeralContainer]
    ] = scala.None,
    /* HostAliases is an optional list of hosts and IPs that will be injected into the pod's hosts file if specified. */
    @named("hostAliases") hostAliases: Option[Seq[HostAlias]] = scala.None,
    /* Use the host's ipc namespace. Optional: Default to false. */
    @named("hostIPC") hostIPC: Option[Boolean] = scala.None,
    /* Host networking requested for this pod. Use the host's network namespace. When using HostNetwork you should specify ports so the scheduler is aware. When `hostNetwork` is true, specified `hostPort` fields in port definitions must match `containerPort`, and unspecified `hostPort` fields in port definitions are defaulted to match `containerPort`. Default to false. */
    @named("hostNetwork") hostNetwork: Option[Boolean] = scala.None,
    /* Use the host's pid namespace. Optional: Default to false. */
    @named("hostPID") hostPID: Option[Boolean] = scala.None,
    /* Use the host's user namespace. Optional: Default to true. If set to true or not present, the pod will be run in the host user namespace, useful for when the pod needs a feature only available to the host user namespace, such as loading a kernel module with CAP_SYS_MODULE. When set to false, a new userns is created for the pod. Setting false is useful for mitigating container breakout vulnerabilities even allowing users to run their containers as root without actually having root privileges on the host. This field is alpha-level and is only honored by servers that enable the UserNamespacesSupport feature. */
    @named("hostUsers") hostUsers: Option[Boolean] = scala.None,
    /* Specifies the hostname of the Pod If not specified, the pod's hostname will be set to a system-defined value. */
    @named("hostname") hostname: Option[String] = scala.None,
    /* HostnameOverride specifies an explicit override for the pod's hostname as perceived by the pod. This field only specifies the pod's hostname and does not affect its DNS records. When this field is set to a non-empty string: - It takes precedence over the values set in `hostname` and `subdomain`. - The Pod's hostname will be set to this value. - `setHostnameAsFQDN` must be nil or set to false. - `hostNetwork` must be set to false.  This field must be a valid DNS subdomain as defined in RFC 1123 and contain at most 64 characters. Requires the HostnameOverride feature gate to be enabled. */
    @named("hostnameOverride") hostnameOverride: Option[String] = scala.None,
    /* ImagePullSecrets is an optional list of references to secrets in the same namespace to use for pulling any of the images used by this PodSpec. If specified, these secrets will be passed to individual puller implementations for them to use. More info: https://kubernetes.io/docs/concepts/containers/images#specifying-imagepullsecrets-on-a-pod */
    @named("imagePullSecrets") imagePullSecrets: Option[
      Seq[LocalObjectReference]
    ] = scala.None,
    /* List of initialization containers belonging to the pod. Init containers are executed in order prior to containers being started. If any init container fails, the pod is considered to have failed and is handled according to its restartPolicy. The name for an init container or normal container must be unique among all containers. Init containers may not have Lifecycle actions, Readiness probes, Liveness probes, or Startup probes. The resourceRequirements of an init container are taken into account during scheduling by finding the highest request/limit for each resource type, and then using the max of that value or the sum of the normal containers. Limits are applied to init containers in a similar fashion. Init containers cannot currently be added or removed. Cannot be updated. More info: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/ */
    @named("initContainers") initContainers: Option[Seq[Container]] =
      scala.None,
    /* NodeName indicates in which node this pod is scheduled. If empty, this pod is a candidate for scheduling by the scheduler defined in schedulerName. Once this field is set, the kubelet for this node becomes responsible for the lifecycle of this pod. This field should not be used to express a desire for the pod to be scheduled on a specific node. https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodename */
    @named("nodeName") nodeName: Option[String] = scala.None,
    /* NodeSelector is a selector which must be true for the pod to fit on a node. Selector which must match a node's labels for the pod to be scheduled on that node. More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/ */
    @named("nodeSelector") nodeSelector: Option[Map[String, String]] =
      scala.None,
    /* Specifies the OS of the containers in the pod. Some pod and container fields are restricted if this is set.  If the OS field is set to linux, the following fields must be unset: -securityContext.windowsOptions  If the OS field is set to windows, following fields must be unset: - spec.hostPID - spec.hostIPC - spec.hostUsers - spec.resources - spec.securityContext.appArmorProfile - spec.securityContext.seLinuxOptions - spec.securityContext.seccompProfile - spec.securityContext.fsGroup - spec.securityContext.fsGroupChangePolicy - spec.securityContext.sysctls - spec.shareProcessNamespace - spec.securityContext.runAsUser - spec.securityContext.runAsGroup - spec.securityContext.supplementalGroups - spec.securityContext.supplementalGroupsPolicy - spec.containers[*].securityContext.appArmorProfile - spec.containers[*].securityContext.seLinuxOptions - spec.containers[*].securityContext.seccompProfile - spec.containers[*].securityContext.capabilities - spec.containers[*].securityContext.readOnlyRootFilesystem - spec.containers[*].securityContext.privileged - spec.containers[*].securityContext.allowPrivilegeEscalation - spec.containers[*].securityContext.procMount - spec.containers[*].securityContext.runAsUser - spec.containers[*].securityContext.runAsGroup */
    @named("os") os: Option[PodOS] = scala.None,
    /* Overhead represents the resource overhead associated with running a pod for a given RuntimeClass. This field will be autopopulated at admission time by the RuntimeClass admission controller. If the RuntimeClass admission controller is enabled, overhead must not be set in Pod create requests. The RuntimeClass admission controller will reject Pod create requests which have the overhead already set. If RuntimeClass is configured and selected in the PodSpec, Overhead will be set to the value defined in the corresponding RuntimeClass, otherwise it will remain unset and treated as zero. More info: https://git.k8s.io/enhancements/keps/sig-node/688-pod-overhead/README.md */
    @named("overhead") overhead: Option[Map[String, Quantity]] = scala.None,
    /* PreemptionPolicy is the Policy for preempting pods with lower priority. One of Never, PreemptLowerPriority. Defaults to PreemptLowerPriority if unset.  Possible enum values:  - `\"Never\"` means that pod never preempts other pods with lower priority.  - `\"PreemptLowerPriority\"` means that pod can preempt other pods with lower priority. */
    @named("preemptionPolicy") preemptionPolicy: Option[
      PodSpecEnums.PreemptionPolicy
    ] = scala.None,
    /* The priority value. Various system components use this field to find the priority of the pod. When Priority Admission Controller is enabled, it prevents users from setting this field. The admission controller populates this field from PriorityClassName. The higher the value, the higher the priority. */
    @named("priority") priority: Option[Int] = scala.None,
    /* If specified, indicates the pod's priority. \"system-node-critical\" and \"system-cluster-critical\" are two special keywords which indicate the highest priorities with the former being the highest priority. Any other name must be defined by creating a PriorityClass object with that name. If not specified, the pod priority will be default or zero if there is no default. */
    @named("priorityClassName") priorityClassName: Option[String] = scala.None,
    /* If specified, all readiness gates will be evaluated for pod readiness. A pod is ready when all its containers are ready AND all conditions specified in the readiness gates have status equal to \"True\" More info: https://git.k8s.io/enhancements/keps/sig-network/580-pod-readiness-gates */
    @named("readinessGates") readinessGates: Option[Seq[PodReadinessGate]] =
      scala.None,
    /* ResourceClaims defines which ResourceClaims must be allocated and reserved before the Pod is allowed to start. The resources will be made available to those containers which consume them by name.  This is an alpha field and requires enabling the DynamicResourceAllocation feature gate.  This field is immutable. */
    @named("resourceClaims") resourceClaims: Option[Seq[PodResourceClaim]] =
      scala.None,
    /* Resources is the total amount of CPU and Memory resources required by all containers in the pod. It supports specifying Requests and Limits for \"cpu\", \"memory\" and \"hugepages-\" resource names only. ResourceClaims are not supported.  This field enables fine-grained control over resource allocation for the entire pod, allowing resource sharing among containers in a pod.  This is an alpha field and requires enabling the PodLevelResources feature gate. */
    @named("resources") resources: Option[ResourceRequirements] = scala.None,
    /* Restart policy for all containers within the pod. One of Always, OnFailure, Never. In some contexts, only a subset of those values may be permitted. Default to Always. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy  Possible enum values:  - `\"Always\"`  - `\"Never\"`  - `\"OnFailure\"` */
    @named("restartPolicy") restartPolicy: Option[PodSpecEnums.RestartPolicy] =
      scala.None,
    /* RuntimeClassName refers to a RuntimeClass object in the node.k8s.io group, which should be used to run this pod.  If no RuntimeClass resource matches the named class, the pod will not be run. If unset or empty, the \"legacy\" RuntimeClass will be used, which is an implicit class with an empty definition that uses the default runtime handler. More info: https://git.k8s.io/enhancements/keps/sig-node/585-runtime-class */
    @named("runtimeClassName") runtimeClassName: Option[String] = scala.None,
    /* If specified, the pod will be dispatched by specified scheduler. If not specified, the pod will be dispatched by default scheduler. */
    @named("schedulerName") schedulerName: Option[String] = scala.None,
    /* SchedulingGates is an opaque list of values that if specified will block scheduling the pod. If schedulingGates is not empty, the pod will stay in the SchedulingGated state and the scheduler will not attempt to schedule the pod.  SchedulingGates can only be set at pod creation time, and be removed only afterwards. */
    @named("schedulingGates") schedulingGates: Option[Seq[PodSchedulingGate]] =
      scala.None,
    /* SecurityContext holds pod-level security attributes and common container settings. Optional: Defaults to empty.  See type description for default values of each field. */
    @named("securityContext") securityContext: Option[PodSecurityContext] =
      scala.None,
    /* DeprecatedServiceAccount is a deprecated alias for ServiceAccountName. Deprecated: Use serviceAccountName instead. */
    @named("serviceAccount") serviceAccount: Option[String] = scala.None,
    /* ServiceAccountName is the name of the ServiceAccount to use to run this pod. More info: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/ */
    @named("serviceAccountName") serviceAccountName: Option[String] =
      scala.None,
    /* If true the pod's hostname will be configured as the pod's FQDN, rather than the leaf name (the default). In Linux containers, this means setting the FQDN in the hostname field of the kernel (the nodename field of struct utsname). In Windows containers, this means setting the registry value of hostname for the registry key HKEY_LOCAL_MACHINE\\\\SYSTEM\\\\CurrentControlSet\\\\Services\\\\Tcpip\\\\Parameters to FQDN. If a pod does not have FQDN, this has no effect. Default to false. */
    @named("setHostnameAsFQDN") setHostnameAsFQDN: Option[Boolean] = scala.None,
    /* Share a single process namespace between all of the containers in a pod. When this is set containers will be able to view and signal processes from other containers in the same pod, and the first process in each container will not be assigned PID 1. HostPID and ShareProcessNamespace cannot both be set. Optional: Default to false. */
    @named("shareProcessNamespace") shareProcessNamespace: Option[Boolean] =
      scala.None,
    /* If specified, the fully qualified Pod hostname will be \"<hostname>.<subdomain>.<pod namespace>.svc.<cluster domain>\". If not specified, the pod will not have a domainname at all. */
    @named("subdomain") subdomain: Option[String] = scala.None,
    /* Optional duration in seconds the pod needs to terminate gracefully. May be decreased in delete request. Value must be non-negative integer. The value zero indicates stop immediately via the kill signal (no opportunity to shut down). If this value is nil, the default grace period will be used instead. The grace period is the duration in seconds after the processes running in the pod are sent a termination signal and the time when the processes are forcibly halted with a kill signal. Set this value longer than the expected cleanup time for your process. Defaults to 30 seconds. */
    @named(
      "terminationGracePeriodSeconds"
    ) terminationGracePeriodSeconds: Option[Long] = scala.None,
    /* If specified, the pod's tolerations. */
    @named("tolerations") tolerations: Option[Seq[Toleration]] = scala.None,
    /* TopologySpreadConstraints describes how a group of pods ought to spread across topology domains. Scheduler will schedule pods in a way which abides by the constraints. All topologySpreadConstraints are ANDed. */
    @named("topologySpreadConstraints") topologySpreadConstraints: Option[
      Seq[TopologySpreadConstraint]
    ] = scala.None,
    /* List of volumes that can be mounted by containers belonging to the pod. More info: https://kubernetes.io/docs/concepts/storage/volumes */
    @named("volumes") volumes: Option[Seq[Volume]] = scala.None
)

object PodSpecEnums:
  enum DnsPolicy:
    case `ClusterFirst`
    case `ClusterFirstWithHostNet`
    case `Default`
    case `None`

  object DnsPolicy:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given dnsPolicyCodec: JsonValueCodec[DnsPolicy] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "ClusterFirst"            => "ClusterFirst"
            case "ClusterFirstWithHostNet" => "ClusterFirstWithHostNet"
            case "Default"                 => "Default"
            case "None"                    => "None"
        }
        .withDiscriminatorFieldName(scala.None)
    }
  enum PreemptionPolicy:
    case `Never`
    case `PreemptLowerPriority`

  object PreemptionPolicy:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given preemptionPolicyCodec: JsonValueCodec[PreemptionPolicy] =
      JsonCodecMaker.make {
        CodecMakerConfig
          .withAdtLeafClassNameMapper { x =>
            JsonCodecMaker.simpleClassName(x) match
              case "Never"                => "Never"
              case "PreemptLowerPriority" => "PreemptLowerPriority"
          }
          .withDiscriminatorFieldName(scala.None)
      }
  enum RestartPolicy:
    case `Always`
    case `Never`
    case `OnFailure`

  object RestartPolicy:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given restartPolicyCodec: JsonValueCodec[RestartPolicy] =
      JsonCodecMaker.make {
        CodecMakerConfig
          .withAdtLeafClassNameMapper { x =>
            JsonCodecMaker.simpleClassName(x) match
              case "Always"    => "Always"
              case "Never"     => "Never"
              case "OnFailure" => "OnFailure"
          }
          .withDiscriminatorFieldName(scala.None)
      }
end PodSpecEnums
