/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** An empty preferred scheduling term matches all objects with implicit weight
  * 0 (i.e. it's a no-op). A null preferred scheduling term matches no objects
  * (i.e. is also a no-op).
  */
case class PreferredSchedulingTerm(
    /* A node selector term, associated with the corresponding weight. */
    @named("preference") preference: NodeSelectorTerm,
    /* Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100. */
    @named("weight") weight: Int
)
