/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** ScaleIOVolumeSource represents a persistent ScaleIO volume
  */
case class ScaleIOVolumeSource(
    /* gateway is the host address of the ScaleIO API Gateway. */
    @named("gateway") gateway: String,
    /* secretRef references to the secret for ScaleIO user and other sensitive information. If this is not provided, Login operation will fail. */
    @named("secretRef") secretRef: LocalObjectReference,
    /* system is the name of the storage system as configured in ScaleIO. */
    @named("system") system: String,
    /* fsType is the filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Default is \"xfs\". */
    @named("fsType") fsType: Option[String] = scala.None,
    /* protectionDomain is the name of the ScaleIO Protection Domain for the configured storage. */
    @named("protectionDomain") protectionDomain: Option[String] = scala.None,
    /* readOnly Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts. */
    @named("readOnly") readOnly: Option[Boolean] = scala.None,
    /* sslEnabled Flag enable/disable SSL communication with Gateway, default false */
    @named("sslEnabled") sslEnabled: Option[Boolean] = scala.None,
    /* storageMode indicates whether the storage for a volume should be ThickProvisioned or ThinProvisioned. Default is ThinProvisioned. */
    @named("storageMode") storageMode: Option[String] = scala.None,
    /* storagePool is the ScaleIO Storage Pool associated with the protection domain. */
    @named("storagePool") storagePool: Option[String] = scala.None,
    /* volumeName is the name of a volume already created in the ScaleIO system that is associated with this volume source. */
    @named("volumeName") volumeName: Option[String] = scala.None
)
