/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** SecurityContext holds security configuration that will be applied to a
  * container. Some fields are present in both SecurityContext and
  * PodSecurityContext. When both are set, the values in SecurityContext take
  * precedence.
  */
case class SecurityContext(
    /* AllowPrivilegeEscalation controls whether a process can gain more privileges than its parent process. This bool directly controls if the no_new_privs flag will be set on the container process. AllowPrivilegeEscalation is true always when the container is: 1) run as Privileged 2) has CAP_SYS_ADMIN Note that this field cannot be set when spec.os.name is windows. */
    @named("allowPrivilegeEscalation") allowPrivilegeEscalation: Option[
      Boolean
    ] = scala.None,
    /* appArmorProfile is the AppArmor options to use by this container. If set, this profile overrides the pod's appArmorProfile. Note that this field cannot be set when spec.os.name is windows. */
    @named("appArmorProfile") appArmorProfile: Option[AppArmorProfile] =
      scala.None,
    /* The capabilities to add/drop when running containers. Defaults to the default set of capabilities granted by the container runtime. Note that this field cannot be set when spec.os.name is windows. */
    @named("capabilities") capabilities: Option[Capabilities] = scala.None,
    /* Run container in privileged mode. Processes in privileged containers are essentially equivalent to root on the host. Defaults to false. Note that this field cannot be set when spec.os.name is windows. */
    @named("privileged") privileged: Option[Boolean] = scala.None,
    /* procMount denotes the type of proc mount to use for the containers. The default value is Default which uses the container runtime defaults for readonly paths and masked paths. This requires the ProcMountType feature flag to be enabled. Note that this field cannot be set when spec.os.name is windows.  Possible enum values:  - `\"Default\"` uses the container runtime defaults for readonly and masked paths for /proc. Most container runtimes mask certain paths in /proc to avoid accidental security exposure of special devices or information.  - `\"Unmasked\"` bypasses the default masking behavior of the container runtime and ensures the newly created /proc the container stays in tact with no modifications. */
    @named("procMount") procMount: Option[SecurityContextEnums.ProcMount] =
      scala.None,
    /* Whether this container has a read-only root filesystem. Default is false. Note that this field cannot be set when spec.os.name is windows. */
    @named("readOnlyRootFilesystem") readOnlyRootFilesystem: Option[Boolean] =
      scala.None,
    /* The GID to run the entrypoint of the container process. Uses runtime default if unset. May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is windows. */
    @named("runAsGroup") runAsGroup: Option[Long] = scala.None,
    /* Indicates that the container must run as a non-root user. If true, the Kubelet will validate the image at runtime to ensure that it does not run as UID 0 (root) and fail to start the container if it does. If unset or false, no such validation will be performed. May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. */
    @named("runAsNonRoot") runAsNonRoot: Option[Boolean] = scala.None,
    /* The UID to run the entrypoint of the container process. Defaults to user specified in image metadata if unspecified. May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is windows. */
    @named("runAsUser") runAsUser: Option[Long] = scala.None,
    /* The SELinux context to be applied to the container. If unspecified, the container runtime will allocate a random SELinux context for each container.  May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is windows. */
    @named("seLinuxOptions") seLinuxOptions: Option[SELinuxOptions] =
      scala.None,
    /* The seccomp options to use by this container. If seccomp options are provided at both the pod & container level, the container options override the pod options. Note that this field cannot be set when spec.os.name is windows. */
    @named("seccompProfile") seccompProfile: Option[SeccompProfile] =
      scala.None,
    /* The Windows specific settings applied to all containers. If unspecified, the options from the PodSecurityContext will be used. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is linux. */
    @named("windowsOptions") windowsOptions: Option[
      WindowsSecurityContextOptions
    ] = scala.None
)

object SecurityContextEnums:
  enum ProcMount:
    case `Default`
    case `Unmasked`

  object ProcMount:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given procMountCodec: JsonValueCodec[ProcMount] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "Default"  => "Default"
            case "Unmasked" => "Unmasked"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end SecurityContextEnums
