/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** ServiceAccountTokenProjection represents a projected service account token
  * volume. This projection can be used to insert a service account token into
  * the pods runtime filesystem for use against APIs (Kubernetes API Server or
  * otherwise).
  */
case class ServiceAccountTokenProjection(
    /* path is the path relative to the mount point of the file to project the token into. */
    @named("path") path: String,
    /* audience is the intended audience of the token. A recipient of a token must identify itself with an identifier specified in the audience of the token, and otherwise should reject the token. The audience defaults to the identifier of the apiserver. */
    @named("audience") audience: Option[String] = scala.None,
    /* expirationSeconds is the requested duration of validity of the service account token. As the token approaches expiration, the kubelet volume plugin will proactively rotate the service account token. The kubelet will start trying to rotate the token if the token is older than 80 percent of its time to live or if the token is older than 24 hours.Defaults to 1 hour and must be at least 10 minutes. */
    @named("expirationSeconds") expirationSeconds: Option[Long] = scala.None
)
