/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** VolumeMount describes a mounting of a Volume within a container.
  */
case class VolumeMount(
    /* Path within the container at which the volume should be mounted.  Must not contain ':'. */
    @named("mountPath") mountPath: String,
    /* This must match the Name of a Volume. */
    @named("name") name: String,
    /* mountPropagation determines how mounts are propagated from the host to container and the other way around. When not set, MountPropagationNone is used. This field is beta in 1.10. When RecursiveReadOnly is set to IfPossible or to Enabled, MountPropagation must be None or unspecified (which defaults to None).  Possible enum values:  - `\"Bidirectional\"` means that the volume in a container will receive new mounts from the host or other containers, and its own mounts will be propagated from the container to the host or other containers. Note that this mode is recursively applied to all mounts in the volume (\"rshared\" in Linux terminology).  - `\"HostToContainer\"` means that the volume in a container will receive new mounts from the host or other containers, but filesystems mounted inside the container won't be propagated to the host or other containers. Note that this mode is recursively applied to all mounts in the volume (\"rslave\" in Linux terminology).  - `\"None\"` means that the volume in a container will not receive new mounts from the host or other containers, and filesystems mounted inside the container won't be propagated to the host or other containers. Note that this mode corresponds to \"private\" in Linux terminology. */
    @named("mountPropagation") mountPropagation: Option[
      VolumeMountEnums.MountPropagation
    ] = scala.None,
    /* Mounted read-only if true, read-write otherwise (false or unspecified). Defaults to false. */
    @named("readOnly") readOnly: Option[Boolean] = scala.None,
    /* RecursiveReadOnly specifies whether read-only mounts should be handled recursively.  If ReadOnly is false, this field has no meaning and must be unspecified.  If ReadOnly is true, and this field is set to Disabled, the mount is not made recursively read-only.  If this field is set to IfPossible, the mount is made recursively read-only, if it is supported by the container runtime.  If this field is set to Enabled, the mount is made recursively read-only if it is supported by the container runtime, otherwise the pod will not be started and an error will be generated to indicate the reason.  If this field is set to IfPossible or Enabled, MountPropagation must be set to None (or be unspecified, which defaults to None).  If this field is not specified, it is treated as an equivalent of Disabled. */
    @named("recursiveReadOnly") recursiveReadOnly: Option[String] = scala.None,
    /* Path within the volume from which the container's volume should be mounted. Defaults to \"\" (volume's root). */
    @named("subPath") subPath: Option[String] = scala.None,
    /* Expanded path within the volume from which the container's volume should be mounted. Behaves similarly to SubPath but environment variable references $(VAR_NAME) are expanded using the container's environment. Defaults to \"\" (volume's root). SubPathExpr and SubPath are mutually exclusive. */
    @named("subPathExpr") subPathExpr: Option[String] = scala.None
)

object VolumeMountEnums:
  enum MountPropagation:
    case `Bidirectional`
    case `HostToContainer`
    case `None`

  object MountPropagation:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given mountPropagationCodec: JsonValueCodec[MountPropagation] =
      JsonCodecMaker.make {
        CodecMakerConfig
          .withAdtLeafClassNameMapper { x =>
            JsonCodecMaker.simpleClassName(x) match
              case "Bidirectional"   => "Bidirectional"
              case "HostToContainer" => "HostToContainer"
              case "None"            => "None"
          }
          .withDiscriminatorFieldName(scala.None)
      }
end VolumeMountEnums
