/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** WindowsSecurityContextOptions contain Windows-specific options and
  * credentials.
  */
case class WindowsSecurityContextOptions(
    /* GMSACredentialSpec is where the GMSA admission webhook (https://github.com/kubernetes-sigs/windows-gmsa) inlines the contents of the GMSA credential spec named by the GMSACredentialSpecName field. */
    @named("gmsaCredentialSpec") gmsaCredentialSpec: Option[String] =
      scala.None,
    /* GMSACredentialSpecName is the name of the GMSA credential spec to use. */
    @named("gmsaCredentialSpecName") gmsaCredentialSpecName: Option[String] =
      scala.None,
    /* HostProcess determines if a container should be run as a 'Host Process' container. All of a Pod's containers must have the same effective HostProcess value (it is not allowed to have a mix of HostProcess containers and non-HostProcess containers). In addition, if HostProcess is true then HostNetwork must also be set to true. */
    @named("hostProcess") hostProcess: Option[Boolean] = scala.None,
    /* The UserName in Windows to run the entrypoint of the container process. Defaults to the user specified in image metadata if unspecified. May also be set in PodSecurityContext. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. */
    @named("runAsUserName") runAsUserName: Option[String] = scala.None
)
