/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.authorization.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** ResourceAttributes includes the authorization attributes available for
  * resource requests to the Authorizer interface
  */
case class ResourceAttributes(
    /* fieldSelector describes the limitation on access based on field.  It can only limit access, not broaden it. */
    @named("fieldSelector") fieldSelector: Option[FieldSelectorAttributes] =
      scala.None,
    /* Group is the API Group of the Resource.  \"*\" means all. */
    @named("group") group: Option[String] = scala.None,
    /* labelSelector describes the limitation on access based on labels.  It can only limit access, not broaden it. */
    @named("labelSelector") labelSelector: Option[LabelSelectorAttributes] =
      scala.None,
    /* Name is the name of the resource being requested for a \"get\" or deleted for a \"delete\". \"\" (empty) means all. */
    @named("name") name: Option[String] = scala.None,
    /* Namespace is the namespace of the action being requested.  Currently, there is no distinction between no namespace and all namespaces \"\" (empty) is defaulted for LocalSubjectAccessReviews \"\" (empty) is empty for cluster-scoped resources \"\" (empty) means \"all\" for namespace scoped resources from a SubjectAccessReview or SelfSubjectAccessReview */
    @named("namespace") namespace: Option[String] = scala.None,
    /* Resource is one of the existing resource types.  \"*\" means all. */
    @named("resource") resource: Option[String] = scala.None,
    /* Subresource is one of the existing resource types.  \"\" means none. */
    @named("subresource") subresource: Option[String] = scala.None,
    /* Verb is a kubernetes resource API verb, like: get, list, watch, create, update, delete, proxy.  \"*\" means all. */
    @named("verb") verb: Option[String] = scala.None,
    /* Version is the API Version of the Resource.  \"*\" means all. */
    @named("version") version: Option[String] = scala.None
)
