/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.authorization.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** SelfSubjectRulesReview enumerates the set of actions the current user can
  * perform within a namespace. The returned list of actions may be incomplete
  * depending on the server's authorization mode, and any errors experienced
  * during the evaluation. SelfSubjectRulesReview should be used by UIs to
  * show/hide actions, or to quickly let an end user reason about their
  * permissions. It should NOT Be used by external systems to drive
  * authorization decisions as this raises confused deputy, cache
  * lifetime/revocation, and correctness concerns. SubjectAccessReview, and
  * LocalAccessReview are the correct way to defer authorization decisions to
  * the API server.
  */
case class SelfSubjectRulesReview(
    /* Spec holds information about the request being evaluated. */
    @named("spec") spec: SelfSubjectRulesReviewSpec,
    /* APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
    @named("apiVersion") apiVersion: Option[String] = scala.None,
    /* Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    @named("kind") kind: Option[String] = scala.None,
    /* Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata */
    @named("metadata") metadata: Option[ObjectMeta] = scala.None,
    /* Status is filled in by the server and indicates the set of actions a user can perform. */
    @named("status") status: Option[SubjectRulesReviewStatus] = scala.None
)
