/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.authorization.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** SelfSubjectAccessReviewSpec is a description of the access request. Exactly
  * one of ResourceAuthorizationAttributes and
  * NonResourceAuthorizationAttributes must be set
  */
case class SelfSubjectAccessReviewSpec(
    /* NonResourceAttributes describes information for a non-resource access request */
    @named("nonResourceAttributes") nonResourceAttributes: Option[
      NonResourceAttributes
    ] = scala.None,
    /* ResourceAuthorizationAttributes describes information for a resource access request */
    @named("resourceAttributes") resourceAttributes: Option[
      ResourceAttributes
    ] = scala.None
)
