/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.authorization.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** SubjectAccessReviewSpec is a description of the access request. Exactly one
  * of ResourceAuthorizationAttributes and NonResourceAuthorizationAttributes
  * must be set
  */
case class SubjectAccessReviewSpec(
    /* Extra corresponds to the user.Info.GetExtra() method from the authenticator.  Since that is input to the authorizer it needs a reflection here. */
    @named("extra") extra: Option[Map[String, Seq[String]]] = scala.None,
    /* Groups is the groups you're testing for. */
    @named("groups") groups: Option[Seq[String]] = scala.None,
    /* NonResourceAttributes describes information for a non-resource access request */
    @named("nonResourceAttributes") nonResourceAttributes: Option[
      NonResourceAttributes
    ] = scala.None,
    /* ResourceAuthorizationAttributes describes information for a resource access request */
    @named("resourceAttributes") resourceAttributes: Option[
      ResourceAttributes
    ] = scala.None,
    /* UID information about the requesting user. */
    @named("uid") uid: Option[String] = scala.None,
    /* User is the user you're testing for. If you specify \"User\" but not \"Groups\", then is it interpreted as \"What if User were not a member of any groups */
    @named("user") user: Option[String] = scala.None
)
