/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.authorization.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** SubjectAccessReviewStatus
  */
case class SubjectAccessReviewStatus(
    /* Allowed is required. True if the action would be allowed, false otherwise. */
    @named("allowed") allowed: Boolean,
    /* Denied is optional. True if the action would be denied, otherwise false. If both allowed is false and denied is false, then the authorizer has no opinion on whether to authorize the action. Denied may not be true if Allowed is true. */
    @named("denied") denied: Option[Boolean] = scala.None,
    /* EvaluationError is an indication that some error occurred during the authorization check. It is entirely possible to get an error and be able to continue determine authorization status in spite of it. For instance, RBAC can be missing a role, but enough roles are still present and bound to reason about the request. */
    @named("evaluationError") evaluationError: Option[String] = scala.None,
    /* Reason is optional.  It indicates why a request was allowed or denied. */
    @named("reason") reason: Option[String] = scala.None
)
