/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.rbac.api

import kubescala.rbac.models.APIGroup
import kubescala.rbac.JsonSupport.{*, given}
import kubescala.rbac.FormSerializable
import kubescala.rbac.FormStyleFormat
import kubescala.rbac.HeaderSerializable
import kubescala.rbac.ApiKeyLocation
import kubescala.rbac.PathStyleFormat
import kubescala.rbac.PathSerializable
import kubescala.rbac.CookieSerializable
import kubescala.rbac.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object RbacAuthorizationApi:
  def apply(
      baseUrl: String = "http://localhost"
  ): RbacAuthorizationApi[kubescala.rbac.Authorization.NoAuthorization.type] =
    RbacAuthorizationApi(baseUrl, kubescala.rbac.Authorization.NoAuthorization)
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): RbacAuthorizationApi[kubescala.rbac.Authorization.BasicAuth] =
    RbacAuthorizationApi(
      baseUrl,
      kubescala.rbac.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): RbacAuthorizationApi[kubescala.rbac.Authorization.ApiKey] =
    RbacAuthorizationApi(baseUrl, kubescala.rbac.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): RbacAuthorizationApi[kubescala.rbac.Authorization.BearerToken] =
    RbacAuthorizationApi(
      baseUrl,
      kubescala.rbac.Authorization.BearerToken(token)
    )

case class RbacAuthorizationApi[Auth <: kubescala.rbac.Authorization] private (
    baseUrl: String,
    authConfig: kubescala.rbac.Authorization
):
  def withBasicAuth(
      username: String,
      password: String
  ): RbacAuthorizationApi[kubescala.rbac.Authorization.BasicAuth] =
    copy(authConfig =
      kubescala.rbac.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      apiKey: String
  ): RbacAuthorizationApi[kubescala.rbac.Authorization.ApiKey] =
    copy(authConfig = kubescala.rbac.Authorization.ApiKey(apiKey))

  def withNoAuth: RbacAuthorizationApi[
    kubescala.rbac.Authorization.NoAuthorization.type
  ] =
    copy(authConfig = kubescala.rbac.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): RbacAuthorizationApi[kubescala.rbac.Authorization.BearerToken] =
    copy(authConfig = kubescala.rbac.Authorization.BearerToken(token))

  /** get information of a group
    *
    * Expected answers: code 200 : APIGroup (OK) code 401 : (Unauthorized)
    */
  def getRbacAuthorizationAPIGroup
      : sttp.client4.Request[Either[ResponseException[String], APIGroup]] =
    val requestURL =
      uri"$baseUrl/apis/rbac.authorization.k8s.io/"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .response(asJson[APIGroup])

end RbacAuthorizationApi
