/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.authentication.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** TokenReviewSpec is a description of the token authentication request.
  */
case class TokenReviewSpec(
    /* Audiences is a list of the identifiers that the resource server presented with the token identifies as. Audience-aware token authenticators will verify that the token was intended for at least one of the audiences in this list. If no audiences are provided, the audience will default to the audience of the Kubernetes apiserver. */
    @named("audiences") audiences: Option[Seq[String]] = scala.None,
    /* Token is the opaque bearer token. */
    @named("token") token: Option[String] = scala.None
)
