/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.authentication.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** UserInfo holds the information about the user needed to implement the
  * user.Info interface.
  */
case class UserInfo(
    /* Any additional information provided by the authenticator. */
    @named("extra") extra: Option[Map[String, Seq[String]]] = scala.None,
    /* The names of groups this user is a part of. */
    @named("groups") groups: Option[Seq[String]] = scala.None,
    /* A unique value that identifies this user across time. If this user is deleted and another user by the same name is added, they will have different UIDs. */
    @named("uid") uid: Option[String] = scala.None,
    /* The name that uniquely identifies this user among all active users. */
    @named("username") username: Option[String] = scala.None
)
