/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.scheduling.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** PriorityClass defines mapping from a priority class name to the priority
  * integer value. The value can be any valid integer.
  */
case class PriorityClass(
    /* value represents the integer value of this priority class. This is the actual priority that pods receive when they have the name of this class in their pod spec. */
    @named("value") value: Int,
    /* APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
    @named("apiVersion") apiVersion: Option[String] = scala.None,
    /* description is an arbitrary string that usually provides guidelines on when this priority class should be used. */
    @named("description") description: Option[String] = scala.None,
    /* globalDefault specifies whether this PriorityClass should be considered as the default priority for pods that do not have any priority class. Only one PriorityClass can be marked as `globalDefault`. However, if more than one PriorityClasses exists with their `globalDefault` field set to true, the smallest value of such global default PriorityClasses will be used as the default priority. */
    @named("globalDefault") globalDefault: Option[Boolean] = scala.None,
    /* Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    @named("kind") kind: Option[String] = scala.None,
    /* Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata */
    @named("metadata") metadata: Option[ObjectMeta] = scala.None,
    /* preemptionPolicy is the Policy for preempting pods with lower priority. One of Never, PreemptLowerPriority. Defaults to PreemptLowerPriority if unset.  Possible enum values:  - `\"Never\"` means that pod never preempts other pods with lower priority.  - `\"PreemptLowerPriority\"` means that pod can preempt other pods with lower priority. */
    @named("preemptionPolicy") preemptionPolicy: Option[
      PriorityClassEnums.PreemptionPolicy
    ] = scala.None
)

object PriorityClassEnums:
  enum PreemptionPolicy:
    case `Never`
    case `PreemptLowerPriority`

  object PreemptionPolicy:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given preemptionPolicyCodec: JsonValueCodec[PreemptionPolicy] =
      JsonCodecMaker.make {
        CodecMakerConfig
          .withAdtLeafClassNameMapper { x =>
            JsonCodecMaker.simpleClassName(x) match
              case "Never"                => "Never"
              case "PreemptLowerPriority" => "PreemptLowerPriority"
          }
          .withDiscriminatorFieldName(scala.None)
      }
end PriorityClassEnums
