/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.node.api

import kubescala.node.models.APIGroup
import kubescala.node.JsonSupport.{*, given}
import kubescala.node.FormSerializable
import kubescala.node.FormStyleFormat
import kubescala.node.HeaderSerializable
import kubescala.node.ApiKeyLocation
import kubescala.node.PathStyleFormat
import kubescala.node.PathSerializable
import kubescala.node.CookieSerializable
import kubescala.node.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object NodeApi:
  def apply(
      baseUrl: String = "http://localhost"
  ): NodeApi[kubescala.node.Authorization.NoAuthorization.type] =
    NodeApi(baseUrl, kubescala.node.Authorization.NoAuthorization)
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): NodeApi[kubescala.node.Authorization.BasicAuth] =
    NodeApi(baseUrl, kubescala.node.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): NodeApi[kubescala.node.Authorization.ApiKey] =
    NodeApi(baseUrl, kubescala.node.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): NodeApi[kubescala.node.Authorization.BearerToken] =
    NodeApi(baseUrl, kubescala.node.Authorization.BearerToken(token))

case class NodeApi[Auth <: kubescala.node.Authorization] private (
    baseUrl: String,
    authConfig: kubescala.node.Authorization
):
  def withBasicAuth(
      username: String,
      password: String
  ): NodeApi[kubescala.node.Authorization.BasicAuth] =
    copy(authConfig =
      kubescala.node.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      apiKey: String
  ): NodeApi[kubescala.node.Authorization.ApiKey] =
    copy(authConfig = kubescala.node.Authorization.ApiKey(apiKey))

  def withNoAuth: NodeApi[kubescala.node.Authorization.NoAuthorization.type] =
    copy(authConfig = kubescala.node.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): NodeApi[kubescala.node.Authorization.BearerToken] =
    copy(authConfig = kubescala.node.Authorization.BearerToken(token))

  /** get information of a group
    *
    * Expected answers: code 200 : APIGroup (OK) code 401 : (Unauthorized)
    */
  def getNodeAPIGroup
      : sttp.client4.Request[Either[ResponseException[String], APIGroup]] =
    val requestURL =
      uri"$baseUrl/apis/node.k8s.io/"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .response(asJson[APIGroup])

end NodeApi
