/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.batch.api

import kubescala.batch.models.APIGroup
import kubescala.batch.JsonSupport.{*, given}
import kubescala.batch.FormSerializable
import kubescala.batch.FormStyleFormat
import kubescala.batch.HeaderSerializable
import kubescala.batch.ApiKeyLocation
import kubescala.batch.PathStyleFormat
import kubescala.batch.PathSerializable
import kubescala.batch.CookieSerializable
import kubescala.batch.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object BatchApi:
  def apply(
      baseUrl: String = "http://localhost"
  ): BatchApi[kubescala.batch.Authorization.NoAuthorization.type] =
    BatchApi(baseUrl, kubescala.batch.Authorization.NoAuthorization)
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): BatchApi[kubescala.batch.Authorization.BasicAuth] =
    BatchApi(
      baseUrl,
      kubescala.batch.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): BatchApi[kubescala.batch.Authorization.ApiKey] =
    BatchApi(baseUrl, kubescala.batch.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): BatchApi[kubescala.batch.Authorization.BearerToken] =
    BatchApi(baseUrl, kubescala.batch.Authorization.BearerToken(token))

case class BatchApi[Auth <: kubescala.batch.Authorization] private (
    baseUrl: String,
    authConfig: kubescala.batch.Authorization
):
  def withBasicAuth(
      username: String,
      password: String
  ): BatchApi[kubescala.batch.Authorization.BasicAuth] =
    copy(authConfig =
      kubescala.batch.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      apiKey: String
  ): BatchApi[kubescala.batch.Authorization.ApiKey] =
    copy(authConfig = kubescala.batch.Authorization.ApiKey(apiKey))

  def withNoAuth: BatchApi[kubescala.batch.Authorization.NoAuthorization.type] =
    copy(authConfig = kubescala.batch.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): BatchApi[kubescala.batch.Authorization.BearerToken] =
    copy(authConfig = kubescala.batch.Authorization.BearerToken(token))

  /** get information of a group
    *
    * Expected answers: code 200 : APIGroup (OK) code 401 : (Unauthorized)
    */
  def getBatchAPIGroup
      : sttp.client4.Request[Either[ResponseException[String], APIGroup]] =
    val requestURL =
      uri"$baseUrl/apis/batch/"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .response(asJson[APIGroup])

end BatchApi
