/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.authorization.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** ServerAddressByClientCIDR helps the client to determine the server address
  * that they should use, depending on the clientCIDR that they match.
  */
case class ServerAddressByClientCIDR(
    /* The CIDR with which clients can match their IP to figure out the server address that they should use. */
    @named("clientCIDR") clientCIDR: String,
    /* Address of this server, suitable for a client that matches the above CIDR. This can be a hostname, hostname:port, IP or IP:port. */
    @named("serverAddress") serverAddress: String
)
