/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.autoscaling.v2.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** HPAScalingPolicy is a single policy which must hold true for a specified
  * past interval.
  */
case class HPAScalingPolicy(
    /* periodSeconds specifies the window of time for which the policy should hold true. PeriodSeconds must be greater than zero and less than or equal to 1800 (30 min). */
    @named("periodSeconds") periodSeconds: Int,
    /* type is used to specify the scaling policy. */
    @named("type") `type`: String,
    /* value contains the amount of change which is permitted by the policy. It must be greater than zero */
    @named("value") value: Int
)
