/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.autoscaling.v2.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** MetricIdentifier defines the name and optionally selector for a metric
  */
case class MetricIdentifier(
    /* name is the name of the given metric */
    @named("name") name: String,
    /* selector is the string-encoded form of a standard kubernetes label selector for the given metric When set, it is passed as an additional parameter to the metrics server for more specific metrics scoping. When unset, just the metricName will be used to gather metrics. */
    @named("selector") selector: Option[LabelSelector] = scala.None
)
