/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.autoscaling.v2.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** MetricSpec specifies how to scale based on a single metric (only `type` and
  * one other matching field should be set at once).
  */
case class MetricSpec(
    /* type is the type of metric source.  It should be one of \"ContainerResource\", \"External\", \"Object\", \"Pods\" or \"Resource\", each mapping to a matching field in the object. */
    @named("type") `type`: String,
    /* containerResource refers to a resource metric (such as those specified in requests and limits) known to Kubernetes describing a single container in each pod of the current scale target (e.g. CPU or memory). Such metrics are built in to Kubernetes, and have special scaling options on top of those available to normal per-pod metrics using the \"pods\" source. */
    @named("containerResource") containerResource: Option[
      ContainerResourceMetricSource
    ] = scala.None,
    /* external refers to a global metric that is not associated with any Kubernetes object. It allows autoscaling based on information coming from components running outside of cluster (for example length of queue in cloud messaging service, or QPS from loadbalancer running outside of cluster). */
    @named("external") external: Option[ExternalMetricSource] = scala.None,
    /* object refers to a metric describing a single kubernetes object (for example, hits-per-second on an Ingress object). */
    @named("object") `object`: Option[ObjectMetricSource] = scala.None,
    /* pods refers to a metric describing each pod in the current scale target (for example, transactions-processed-per-second).  The values will be averaged together before being compared to the target value. */
    @named("pods") pods: Option[PodsMetricSource] = scala.None,
    /* resource refers to a resource metric (such as those specified in requests and limits) known to Kubernetes describing each pod in the current scale target (e.g. CPU or memory). Such metrics are built in to Kubernetes, and have special scaling options on top of those available to normal per-pod metrics using the \"pods\" source. */
    @named("resource") resource: Option[ResourceMetricSource] = scala.None
)
