/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.autoscaling.v2.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** MetricTarget defines the target value, average value, or average utilization
  * of a specific metric
  */
case class MetricTarget(
    /* type represents whether the metric type is Utilization, Value, or AverageValue */
    @named("type") `type`: String,
    /* averageUtilization is the target value of the average of the resource metric across all relevant pods, represented as a percentage of the requested value of the resource for the pods. Currently only valid for Resource metric source type */
    @named("averageUtilization") averageUtilization: Option[Int] = scala.None,
    /* averageValue is the target value of the average of the metric across all relevant pods (as a quantity) */
    @named("averageValue") averageValue: Option[Quantity] = scala.None,
    /* value is the target value of the metric (as a quantity). */
    @named("value") value: Option[Quantity] = scala.None
)
