/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.autoscaling.v2.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** MetricValueStatus holds the current value for a metric
  */
case class MetricValueStatus(
    /* currentAverageUtilization is the current value of the average of the resource metric across all relevant pods, represented as a percentage of the requested value of the resource for the pods. */
    @named("averageUtilization") averageUtilization: Option[Int] = scala.None,
    /* averageValue is the current value of the average of the metric across all relevant pods (as a quantity) */
    @named("averageValue") averageValue: Option[Quantity] = scala.None,
    /* value is the current value of the metric (as a quantity). */
    @named("value") value: Option[Quantity] = scala.None
)
