/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.autoscaling.v2.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** ObjectMetricStatus indicates the current value of a metric describing a
  * kubernetes object (for example, hits-per-second on an Ingress object).
  */
case class ObjectMetricStatus(
    /* current contains the current value for the given metric */
    @named("current") current: MetricValueStatus,
    /* DescribedObject specifies the descriptions of a object,such as kind,name apiVersion */
    @named("describedObject") describedObject: CrossVersionObjectReference,
    /* metric identifies the target metric by name and selector */
    @named("metric") metric: MetricIdentifier
)
