/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.autoscaling.v2.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** PodsMetricStatus indicates the current value of a metric describing each pod
  * in the current scale target (for example,
  * transactions-processed-per-second).
  */
case class PodsMetricStatus(
    /* current contains the current value for the given metric */
    @named("current") current: MetricValueStatus,
    /* metric identifies the target metric by name and selector */
    @named("metric") metric: MetricIdentifier
)
