/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.autoscaling.v2.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** PodsMetricSource indicates how to scale on a metric describing each pod in
  * the current scale target (for example, transactions-processed-per-second).
  * The values will be averaged together before being compared to the target
  * value.
  */
case class PodsMetricSource(
    /* metric identifies the target metric by name and selector */
    @named("metric") metric: MetricIdentifier,
    /* target specifies the target value for the given metric */
    @named("target") target: MetricTarget
)
