/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.authorization.v1.api

import kubescala.authorization.v1.models.APIResourceList
import kubescala.authorization.v1.models.LocalSubjectAccessReview
import kubescala.authorization.v1.models.SelfSubjectAccessReview
import kubescala.authorization.v1.models.SelfSubjectRulesReview
import kubescala.authorization.v1.models.SubjectAccessReview
import kubescala.authorization.v1.JsonSupport.{*, given}
import kubescala.authorization.v1.FormSerializable
import kubescala.authorization.v1.FormStyleFormat
import kubescala.authorization.v1.HeaderSerializable
import kubescala.authorization.v1.ApiKeyLocation
import kubescala.authorization.v1.PathStyleFormat
import kubescala.authorization.v1.PathSerializable
import kubescala.authorization.v1.CookieSerializable
import kubescala.authorization.v1.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object AuthorizationV1Api:
  def apply(baseUrl: String = "http://localhost"): AuthorizationV1Api[
    kubescala.authorization.v1.Authorization.NoAuthorization.type
  ] = AuthorizationV1Api(
    baseUrl,
    kubescala.authorization.v1.Authorization.NoAuthorization
  )
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): AuthorizationV1Api[kubescala.authorization.v1.Authorization.BasicAuth] =
    AuthorizationV1Api(
      baseUrl,
      kubescala.authorization.v1.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): AuthorizationV1Api[kubescala.authorization.v1.Authorization.ApiKey] =
    AuthorizationV1Api(
      baseUrl,
      kubescala.authorization.v1.Authorization.ApiKey(apiKey)
    )

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): AuthorizationV1Api[kubescala.authorization.v1.Authorization.BearerToken] =
    AuthorizationV1Api(
      baseUrl,
      kubescala.authorization.v1.Authorization.BearerToken(token)
    )

case class AuthorizationV1Api[
    Auth <: kubescala.authorization.v1.Authorization
] private (
    baseUrl: String,
    authConfig: kubescala.authorization.v1.Authorization
):
  def withBasicAuth(
      username: String,
      password: String
  ): AuthorizationV1Api[kubescala.authorization.v1.Authorization.BasicAuth] =
    copy(authConfig =
      kubescala.authorization.v1.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      apiKey: String
  ): AuthorizationV1Api[kubescala.authorization.v1.Authorization.ApiKey] =
    copy(authConfig = kubescala.authorization.v1.Authorization.ApiKey(apiKey))

  def withNoAuth: AuthorizationV1Api[
    kubescala.authorization.v1.Authorization.NoAuthorization.type
  ] =
    copy(authConfig = kubescala.authorization.v1.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): AuthorizationV1Api[kubescala.authorization.v1.Authorization.BearerToken] =
    copy(authConfig =
      kubescala.authorization.v1.Authorization.BearerToken(token)
    )

  /** create a LocalSubjectAccessReview
    *
    * Expected answers: code 200 : LocalSubjectAccessReview (OK) code 201 :
    * LocalSubjectAccessReview (Created) code 202 : LocalSubjectAccessReview
    * (Accepted) code 401 : (Unauthorized)
    *
    * @param namespace
    *   object name and auth scope, such as for teams and projects
    * @param localSubjectAccessReview
    * @param dryRun
    *   When present, indicates that modifications should not be persisted. An
    *   invalid or unrecognized dryRun directive will result in an error
    *   response and no further processing of the request. Valid values are: -
    *   All: all dry run stages will be processed
    * @param fieldManager
    *   fieldManager is a name associated with the actor or entity that is
    *   making these changes. The value must be less than or 128 characters
    *   long, and only contain printable characters, as defined by
    *   https://golang.org/pkg/unicode/#IsPrint.
    * @param fieldValidation
    *   fieldValidation instructs the server on how to handle objects in the
    *   request (POST/PUT/PATCH) containing unknown or duplicate fields. Valid
    *   values are: - Ignore: This will ignore any unknown fields that are
    *   silently dropped from the object, and will ignore all but the last
    *   duplicate field that the decoder encounters. This is the default
    *   behavior prior to v1.23. - Warn: This will send a warning via the
    *   standard warning response header for each unknown field that is dropped
    *   from the object, and for each duplicate field that is encountered. The
    *   request will still succeed if there are no other errors, and will only
    *   persist the last of any duplicate fields. This is the default in v1.23+ -
    *   Strict: This will fail the request with a BadRequest error if any
    *   unknown fields would be dropped from the object, or if any duplicate
    *   fields are present. The error returned from the server will contain all
    *   unknown and duplicate fields encountered.
    * @param pretty
    *   If 'true', then the output is pretty printed. Defaults to 'false' unless
    *   the user-agent indicates a browser or command-line HTTP tool (curl and
    *   wget).
    */
  def createAuthorizationV1NamespacedLocalSubjectAccessReview(
      namespace: String,
      localSubjectAccessReview: LocalSubjectAccessReview,
      dryRun: Option[String] = scala.None,
      fieldManager: Option[String] = scala.None,
      fieldValidation: Option[String] = scala.None,
      pretty: Option[String] = scala.None
  ): sttp.client4.Request[
    Either[ResponseException[String], LocalSubjectAccessReview]
  ] =
    val namespacePathParam = PathSerializable.serialize(
      "namespace",
      namespace,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/apis/authorization.k8s.io/v1/namespaces/${namespacePathParam}/localsubjectaccessreviews"
        .addParams(
          FormSerializable
            .serialize("dryRun", dryRun, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable.serialize(
            "fieldManager",
            fieldManager,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "fieldValidation",
            fieldValidation,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("pretty", pretty, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .body(asJson(localSubjectAccessReview))
      .response(asJson[LocalSubjectAccessReview])

  /** create a SelfSubjectAccessReview
    *
    * Expected answers: code 200 : SelfSubjectAccessReview (OK) code 201 :
    * SelfSubjectAccessReview (Created) code 202 : SelfSubjectAccessReview
    * (Accepted) code 401 : (Unauthorized)
    *
    * @param selfSubjectAccessReview
    * @param dryRun
    *   When present, indicates that modifications should not be persisted. An
    *   invalid or unrecognized dryRun directive will result in an error
    *   response and no further processing of the request. Valid values are: -
    *   All: all dry run stages will be processed
    * @param fieldManager
    *   fieldManager is a name associated with the actor or entity that is
    *   making these changes. The value must be less than or 128 characters
    *   long, and only contain printable characters, as defined by
    *   https://golang.org/pkg/unicode/#IsPrint.
    * @param fieldValidation
    *   fieldValidation instructs the server on how to handle objects in the
    *   request (POST/PUT/PATCH) containing unknown or duplicate fields. Valid
    *   values are: - Ignore: This will ignore any unknown fields that are
    *   silently dropped from the object, and will ignore all but the last
    *   duplicate field that the decoder encounters. This is the default
    *   behavior prior to v1.23. - Warn: This will send a warning via the
    *   standard warning response header for each unknown field that is dropped
    *   from the object, and for each duplicate field that is encountered. The
    *   request will still succeed if there are no other errors, and will only
    *   persist the last of any duplicate fields. This is the default in v1.23+ -
    *   Strict: This will fail the request with a BadRequest error if any
    *   unknown fields would be dropped from the object, or if any duplicate
    *   fields are present. The error returned from the server will contain all
    *   unknown and duplicate fields encountered.
    * @param pretty
    *   If 'true', then the output is pretty printed. Defaults to 'false' unless
    *   the user-agent indicates a browser or command-line HTTP tool (curl and
    *   wget).
    */
  def createAuthorizationV1SelfSubjectAccessReview(
      selfSubjectAccessReview: SelfSubjectAccessReview,
      dryRun: Option[String] = scala.None,
      fieldManager: Option[String] = scala.None,
      fieldValidation: Option[String] = scala.None,
      pretty: Option[String] = scala.None
  ): sttp.client4.Request[
    Either[ResponseException[String], SelfSubjectAccessReview]
  ] =
    val requestURL =
      uri"$baseUrl/apis/authorization.k8s.io/v1/selfsubjectaccessreviews"
        .addParams(
          FormSerializable
            .serialize("dryRun", dryRun, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable.serialize(
            "fieldManager",
            fieldManager,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "fieldValidation",
            fieldValidation,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("pretty", pretty, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .body(asJson(selfSubjectAccessReview))
      .response(asJson[SelfSubjectAccessReview])

  /** create a SelfSubjectRulesReview
    *
    * Expected answers: code 200 : SelfSubjectRulesReview (OK) code 201 :
    * SelfSubjectRulesReview (Created) code 202 : SelfSubjectRulesReview
    * (Accepted) code 401 : (Unauthorized)
    *
    * @param selfSubjectRulesReview
    * @param dryRun
    *   When present, indicates that modifications should not be persisted. An
    *   invalid or unrecognized dryRun directive will result in an error
    *   response and no further processing of the request. Valid values are: -
    *   All: all dry run stages will be processed
    * @param fieldManager
    *   fieldManager is a name associated with the actor or entity that is
    *   making these changes. The value must be less than or 128 characters
    *   long, and only contain printable characters, as defined by
    *   https://golang.org/pkg/unicode/#IsPrint.
    * @param fieldValidation
    *   fieldValidation instructs the server on how to handle objects in the
    *   request (POST/PUT/PATCH) containing unknown or duplicate fields. Valid
    *   values are: - Ignore: This will ignore any unknown fields that are
    *   silently dropped from the object, and will ignore all but the last
    *   duplicate field that the decoder encounters. This is the default
    *   behavior prior to v1.23. - Warn: This will send a warning via the
    *   standard warning response header for each unknown field that is dropped
    *   from the object, and for each duplicate field that is encountered. The
    *   request will still succeed if there are no other errors, and will only
    *   persist the last of any duplicate fields. This is the default in v1.23+ -
    *   Strict: This will fail the request with a BadRequest error if any
    *   unknown fields would be dropped from the object, or if any duplicate
    *   fields are present. The error returned from the server will contain all
    *   unknown and duplicate fields encountered.
    * @param pretty
    *   If 'true', then the output is pretty printed. Defaults to 'false' unless
    *   the user-agent indicates a browser or command-line HTTP tool (curl and
    *   wget).
    */
  def createAuthorizationV1SelfSubjectRulesReview(
      selfSubjectRulesReview: SelfSubjectRulesReview,
      dryRun: Option[String] = scala.None,
      fieldManager: Option[String] = scala.None,
      fieldValidation: Option[String] = scala.None,
      pretty: Option[String] = scala.None
  ): sttp.client4.Request[
    Either[ResponseException[String], SelfSubjectRulesReview]
  ] =
    val requestURL =
      uri"$baseUrl/apis/authorization.k8s.io/v1/selfsubjectrulesreviews"
        .addParams(
          FormSerializable
            .serialize("dryRun", dryRun, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable.serialize(
            "fieldManager",
            fieldManager,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "fieldValidation",
            fieldValidation,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("pretty", pretty, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .body(asJson(selfSubjectRulesReview))
      .response(asJson[SelfSubjectRulesReview])

  /** create a SubjectAccessReview
    *
    * Expected answers: code 200 : SubjectAccessReview (OK) code 201 :
    * SubjectAccessReview (Created) code 202 : SubjectAccessReview (Accepted)
    * code 401 : (Unauthorized)
    *
    * @param subjectAccessReview
    * @param dryRun
    *   When present, indicates that modifications should not be persisted. An
    *   invalid or unrecognized dryRun directive will result in an error
    *   response and no further processing of the request. Valid values are: -
    *   All: all dry run stages will be processed
    * @param fieldManager
    *   fieldManager is a name associated with the actor or entity that is
    *   making these changes. The value must be less than or 128 characters
    *   long, and only contain printable characters, as defined by
    *   https://golang.org/pkg/unicode/#IsPrint.
    * @param fieldValidation
    *   fieldValidation instructs the server on how to handle objects in the
    *   request (POST/PUT/PATCH) containing unknown or duplicate fields. Valid
    *   values are: - Ignore: This will ignore any unknown fields that are
    *   silently dropped from the object, and will ignore all but the last
    *   duplicate field that the decoder encounters. This is the default
    *   behavior prior to v1.23. - Warn: This will send a warning via the
    *   standard warning response header for each unknown field that is dropped
    *   from the object, and for each duplicate field that is encountered. The
    *   request will still succeed if there are no other errors, and will only
    *   persist the last of any duplicate fields. This is the default in v1.23+ -
    *   Strict: This will fail the request with a BadRequest error if any
    *   unknown fields would be dropped from the object, or if any duplicate
    *   fields are present. The error returned from the server will contain all
    *   unknown and duplicate fields encountered.
    * @param pretty
    *   If 'true', then the output is pretty printed. Defaults to 'false' unless
    *   the user-agent indicates a browser or command-line HTTP tool (curl and
    *   wget).
    */
  def createAuthorizationV1SubjectAccessReview(
      subjectAccessReview: SubjectAccessReview,
      dryRun: Option[String] = scala.None,
      fieldManager: Option[String] = scala.None,
      fieldValidation: Option[String] = scala.None,
      pretty: Option[String] = scala.None
  ): sttp.client4.Request[
    Either[ResponseException[String], SubjectAccessReview]
  ] =
    val requestURL =
      uri"$baseUrl/apis/authorization.k8s.io/v1/subjectaccessreviews"
        .addParams(
          FormSerializable
            .serialize("dryRun", dryRun, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable.serialize(
            "fieldManager",
            fieldManager,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "fieldValidation",
            fieldValidation,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("pretty", pretty, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .body(asJson(subjectAccessReview))
      .response(asJson[SubjectAccessReview])

  /** get available resources
    *
    * Expected answers: code 200 : APIResourceList (OK) code 401 :
    * (Unauthorized)
    */
  def getAuthorizationV1APIResources: sttp.client4.Request[
    Either[ResponseException[String], APIResourceList]
  ] =
    val requestURL =
      uri"$baseUrl/apis/authorization.k8s.io/v1/"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .response(asJson[APIResourceList])

end AuthorizationV1Api
