/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.node.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Overhead structure represents the resource overhead associated with running
  * a pod.
  */
case class Overhead(
    /* podFixed represents the fixed resource overhead associated with running a pod. */
    @named("podFixed") podFixed: Option[Map[String, Quantity]] = scala.None
)
