/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.node.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** The pod this Toleration is attached to tolerates any taint that matches the
  * triple <key,value,effect> using the matching operator <operator>.
  */
case class Toleration(
    /* Effect indicates the taint effect to match. Empty means match all taint effects. When specified, allowed values are NoSchedule, PreferNoSchedule and NoExecute.  Possible enum values:  - `\"NoExecute\"` Evict any already-running pods that do not tolerate the taint. Currently enforced by NodeController.  - `\"NoSchedule\"` Do not allow new pods to schedule onto the node unless they tolerate the taint, but allow all pods submitted to Kubelet without going through the scheduler to start, and allow all already-running pods to continue running. Enforced by the scheduler.  - `\"PreferNoSchedule\"` Like TaintEffectNoSchedule, but the scheduler tries not to schedule new pods onto the node, rather than prohibiting new pods from scheduling onto the node entirely. Enforced by the scheduler. */
    @named("effect") effect: Option[TolerationEnums.Effect] = scala.None,
    /* Key is the taint key that the toleration applies to. Empty means match all taint keys. If the key is empty, operator must be Exists; this combination means to match all values and all keys. */
    @named("key") key: Option[String] = scala.None,
    /* Operator represents a key's relationship to the value. Valid operators are Exists and Equal. Defaults to Equal. Exists is equivalent to wildcard for value, so that a pod can tolerate all taints of a particular category.  Possible enum values:  - `\"Equal\"`  - `\"Exists\"` */
    @named("operator") operator: Option[TolerationEnums.Operator] = scala.None,
    /* TolerationSeconds represents the period of time the toleration (which must be of effect NoExecute, otherwise this field is ignored) tolerates the taint. By default, it is not set, which means tolerate the taint forever (do not evict). Zero and negative values will be treated as 0 (evict immediately) by the system. */
    @named("tolerationSeconds") tolerationSeconds: Option[Long] = scala.None,
    /* Value is the taint value the toleration matches to. If the operator is Exists, the value should be empty, otherwise just a regular string. */
    @named("value") value: Option[String] = scala.None
)

object TolerationEnums:
  enum Effect:
    case `NoExecute`
    case `NoSchedule`
    case `PreferNoSchedule`

  object Effect:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given effectCodec: JsonValueCodec[Effect] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "NoExecute"        => "NoExecute"
            case "NoSchedule"       => "NoSchedule"
            case "PreferNoSchedule" => "PreferNoSchedule"
        }
        .withDiscriminatorFieldName(scala.None)
    }
  enum Operator:
    case `Equal`
    case `Exists`

  object Operator:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given operatorCodec: JsonValueCodec[Operator] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "Equal"  => "Equal"
            case "Exists" => "Exists"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end TolerationEnums
