/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.admissionregistration.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** ExpressionWarning is a warning information that targets a specific
  * expression.
  */
case class ExpressionWarning(
    /* The path to the field that refers the expression. For example, the reference to the expression of the first item of validations is \"spec.validations[0].expression\" */
    @named("fieldRef") fieldRef: String,
    /* The content of type checking information in a human-readable form. Each line of the warning contains the type that the expression is checked against, followed by the type check error from the compiler. */
    @named("warning") warning: String
)
