/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.admissionregistration.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** TypeChecking contains results of type checking the expressions in the
  * ValidatingAdmissionPolicy
  */
case class TypeChecking(
    /* The type checking warnings for each expression. */
    @named("expressionWarnings") expressionWarnings: Option[
      Seq[ExpressionWarning]
    ] = scala.None
)
