/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.admissionregistration.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** ValidatingAdmissionPolicyStatus represents the status of an admission
  * validation policy.
  */
case class ValidatingAdmissionPolicyStatus(
    /* The conditions represent the latest available observations of a policy's current state. */
    @named("conditions") conditions: Option[Seq[Condition]] = scala.None,
    /* The generation observed by the controller. */
    @named("observedGeneration") observedGeneration: Option[Long] = scala.None,
    /* The results of type checking for each expression. Presence of this field indicates the completion of the type checking. */
    @named("typeChecking") typeChecking: Option[TypeChecking] = scala.None
)
