/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.apiextensions.v1.models

import java.time.OffsetDateTime
import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** APIServiceCondition describes the state of an APIService at a particular
  * point
  */
case class APIServiceCondition(
    /* Status is the status of the condition. Can be True, False, Unknown. */
    @named("status") status: String,
    /* Type is the type of the condition. */
    @named("type") `type`: String,
    /* Last time the condition transitioned from one status to another. */
    @named("lastTransitionTime") lastTransitionTime: Option[OffsetDateTime] =
      scala.None,
    /* Human-readable message indicating details about last transition. */
    @named("message") message: Option[String] = scala.None,
    /* Unique, one-word, CamelCase reason for the condition's last transition. */
    @named("reason") reason: Option[String] = scala.None
)
