/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.jwks.api

import kubescala.jwks.JsonSupport.{*, given}
import kubescala.jwks.FormSerializable
import kubescala.jwks.FormStyleFormat
import kubescala.jwks.HeaderSerializable
import kubescala.jwks.ApiKeyLocation
import kubescala.jwks.PathStyleFormat
import kubescala.jwks.PathSerializable
import kubescala.jwks.CookieSerializable
import kubescala.jwks.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object OpenidApi:
  def apply(
      baseUrl: String = "http://localhost"
  ): OpenidApi[kubescala.jwks.Authorization.NoAuthorization.type] =
    OpenidApi(baseUrl, kubescala.jwks.Authorization.NoAuthorization)
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): OpenidApi[kubescala.jwks.Authorization.BasicAuth] =
    OpenidApi(
      baseUrl,
      kubescala.jwks.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): OpenidApi[kubescala.jwks.Authorization.ApiKey] =
    OpenidApi(baseUrl, kubescala.jwks.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): OpenidApi[kubescala.jwks.Authorization.BearerToken] =
    OpenidApi(baseUrl, kubescala.jwks.Authorization.BearerToken(token))

case class OpenidApi[Auth <: kubescala.jwks.Authorization] private (
    baseUrl: String,
    authConfig: kubescala.jwks.Authorization
):
  def withBasicAuth(
      username: String,
      password: String
  ): OpenidApi[kubescala.jwks.Authorization.BasicAuth] =
    copy(authConfig =
      kubescala.jwks.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      apiKey: String
  ): OpenidApi[kubescala.jwks.Authorization.ApiKey] =
    copy(authConfig = kubescala.jwks.Authorization.ApiKey(apiKey))

  def withNoAuth: OpenidApi[kubescala.jwks.Authorization.NoAuthorization.type] =
    copy(authConfig = kubescala.jwks.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): OpenidApi[kubescala.jwks.Authorization.BearerToken] =
    copy(authConfig = kubescala.jwks.Authorization.BearerToken(token))

  /** get service account issuer OpenID JSON Web Key Set (contains public token
    * verification keys)
    *
    * Expected answers: code 200 : String (OK) code 401 : (Unauthorized)
    */
  def getServiceAccountIssuerOpenIDKeyset
      : sttp.client4.Request[Either[ResponseException[String], String]] =
    val requestURL =
      uri"$baseUrl/openid/v1/jwks/"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .response(asJson[String])

end OpenidApi
