/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.apiserver.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** FlowDistinguisherMethod specifies the method of a flow distinguisher.
  */
case class FlowDistinguisherMethod(
    /* `type` is the type of flow distinguisher method The supported types are \"ByUser\" and \"ByNamespace\". Required. */
    @named("type") `type`: String
)
