/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.apiserver.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** NonResourcePolicyRule is a predicate that matches non-resource requests
  * according to their verb and the target non-resource URL. A
  * NonResourcePolicyRule matches a request if and only if both (a) at least one
  * member of verbs matches the request and (b) at least one member of
  * nonResourceURLs matches the request.
  */
case class NonResourcePolicyRule(
    /* `nonResourceURLs` is a set of url prefixes that a user should have access to and may not be empty. For example:   - \"/healthz\" is legal   - \"/hea*\" is illegal   - \"/hea\" is legal but matches nothing   - \"/hea/_*\" also matches nothing   - \"/healthz/_*\" matches all per-component health checks. \"*\" matches all non-resource urls. if it is present, it must be the only entry. Required. */
    @named("nonResourceURLs") nonResourceURLs: Seq[String],
    /* `verbs` is a list of matching verbs and may not be empty. \"*\" matches all verbs. If it is present, it must be the only entry. Required. */
    @named("verbs") verbs: Seq[String]
)
