/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.apiserver.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** PolicyRulesWithSubjects prescribes a test that applies to a request to an
  * apiserver. The test considers the subject making the request, the verb being
  * requested, and the resource to be acted upon. This PolicyRulesWithSubjects
  * matches a request if and only if both (a) at least one member of subjects
  * matches the request and (b) at least one member of resourceRules or
  * nonResourceRules matches the request.
  */
case class PolicyRulesWithSubjects(
    /* subjects is the list of normal user, serviceaccount, or group that this rule cares about. There must be at least one member in this slice. A slice that includes both the system:authenticated and system:unauthenticated user groups matches every request. Required. */
    @named("subjects") subjects: Seq[Subject],
    /* `nonResourceRules` is a list of NonResourcePolicyRules that identify matching requests according to their verb and the target non-resource URL. */
    @named("nonResourceRules") nonResourceRules: Option[
      Seq[NonResourcePolicyRule]
    ] = scala.None,
    /* `resourceRules` is a slice of ResourcePolicyRules that identify matching requests according to their verb and the target resource. At least one of `resourceRules` and `nonResourceRules` has to be non-empty. */
    @named("resourceRules") resourceRules: Option[Seq[ResourcePolicyRule]] =
      scala.None
)
