/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.apiserver.v1.models

import java.time.OffsetDateTime
import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** PriorityLevelConfigurationCondition defines the condition of priority level.
  */
case class PriorityLevelConfigurationCondition(
    /* `lastTransitionTime` is the last time the condition transitioned from one status to another. */
    @named("lastTransitionTime") lastTransitionTime: Option[OffsetDateTime] =
      scala.None,
    /* `message` is a human-readable message indicating details about last transition. */
    @named("message") message: Option[String] = scala.None,
    /* `reason` is a unique, one-word, CamelCase reason for the condition's last transition. */
    @named("reason") reason: Option[String] = scala.None,
    /* `status` is the status of the condition. Can be True, False, Unknown. Required. */
    @named("status") status: Option[String] = scala.None,
    /* `type` is the type of the condition. Required. */
    @named("type") `type`: Option[String] = scala.None
)
