/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.apiserver.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** UserSubject holds detailed information for user-kind subject.
  */
case class UserSubject(
    /* `name` is the username that matches, or \"*\" to match all usernames. Required. */
    @named("name") name: String
)
