/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.admissionregistration.api

import kubescala.admissionregistration.models.APIGroup
import kubescala.admissionregistration.JsonSupport.{*, given}
import kubescala.admissionregistration.FormSerializable
import kubescala.admissionregistration.FormStyleFormat
import kubescala.admissionregistration.HeaderSerializable
import kubescala.admissionregistration.ApiKeyLocation
import kubescala.admissionregistration.PathStyleFormat
import kubescala.admissionregistration.PathSerializable
import kubescala.admissionregistration.CookieSerializable
import kubescala.admissionregistration.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object AdmissionregistrationApi:
  def apply(baseUrl: String = "http://localhost"): AdmissionregistrationApi[
    kubescala.admissionregistration.Authorization.NoAuthorization.type
  ] = AdmissionregistrationApi(
    baseUrl,
    kubescala.admissionregistration.Authorization.NoAuthorization
  )
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): AdmissionregistrationApi[
    kubescala.admissionregistration.Authorization.BasicAuth
  ] =
    AdmissionregistrationApi(
      baseUrl,
      kubescala.admissionregistration.Authorization
        .BasicAuth(username, password)
    )

  def withApiKeyAuth(baseUrl: String, apiKey: String): AdmissionregistrationApi[
    kubescala.admissionregistration.Authorization.ApiKey
  ] =
    AdmissionregistrationApi(
      baseUrl,
      kubescala.admissionregistration.Authorization.ApiKey(apiKey)
    )

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): AdmissionregistrationApi[
    kubescala.admissionregistration.Authorization.BearerToken
  ] =
    AdmissionregistrationApi(
      baseUrl,
      kubescala.admissionregistration.Authorization.BearerToken(token)
    )

case class AdmissionregistrationApi[
    Auth <: kubescala.admissionregistration.Authorization
] private (
    baseUrl: String,
    authConfig: kubescala.admissionregistration.Authorization
):
  def withBasicAuth(
      username: String,
      password: String
  ): AdmissionregistrationApi[
    kubescala.admissionregistration.Authorization.BasicAuth
  ] =
    copy(authConfig =
      kubescala.admissionregistration.Authorization
        .BasicAuth(username, password)
    )

  def withApiKeyAuth(apiKey: String): AdmissionregistrationApi[
    kubescala.admissionregistration.Authorization.ApiKey
  ] =
    copy(authConfig =
      kubescala.admissionregistration.Authorization.ApiKey(apiKey)
    )

  def withNoAuth: AdmissionregistrationApi[
    kubescala.admissionregistration.Authorization.NoAuthorization.type
  ] =
    copy(authConfig =
      kubescala.admissionregistration.Authorization.NoAuthorization
    )

  def withBearerTokenAuth(token: String): AdmissionregistrationApi[
    kubescala.admissionregistration.Authorization.BearerToken
  ] =
    copy(authConfig =
      kubescala.admissionregistration.Authorization.BearerToken(token)
    )

  /** get information of a group
    *
    * Expected answers: code 200 : APIGroup (OK) code 401 : (Unauthorized)
    */
  def getAdmissionregistrationAPIGroup
      : sttp.client4.Request[Either[ResponseException[String], APIGroup]] =
    val requestURL =
      uri"$baseUrl/apis/admissionregistration.k8s.io/"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .response(asJson[APIGroup])

end AdmissionregistrationApi
