/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.discovery.api

import kubescala.discovery.models.APIGroup
import kubescala.discovery.JsonSupport.{*, given}
import kubescala.discovery.FormSerializable
import kubescala.discovery.FormStyleFormat
import kubescala.discovery.HeaderSerializable
import kubescala.discovery.ApiKeyLocation
import kubescala.discovery.PathStyleFormat
import kubescala.discovery.PathSerializable
import kubescala.discovery.CookieSerializable
import kubescala.discovery.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object DiscoveryApi:
  def apply(
      baseUrl: String = "http://localhost"
  ): DiscoveryApi[kubescala.discovery.Authorization.NoAuthorization.type] =
    DiscoveryApi(baseUrl, kubescala.discovery.Authorization.NoAuthorization)
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): DiscoveryApi[kubescala.discovery.Authorization.BasicAuth] =
    DiscoveryApi(
      baseUrl,
      kubescala.discovery.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): DiscoveryApi[kubescala.discovery.Authorization.ApiKey] =
    DiscoveryApi(baseUrl, kubescala.discovery.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): DiscoveryApi[kubescala.discovery.Authorization.BearerToken] =
    DiscoveryApi(baseUrl, kubescala.discovery.Authorization.BearerToken(token))

case class DiscoveryApi[Auth <: kubescala.discovery.Authorization] private (
    baseUrl: String,
    authConfig: kubescala.discovery.Authorization
):
  def withBasicAuth(
      username: String,
      password: String
  ): DiscoveryApi[kubescala.discovery.Authorization.BasicAuth] =
    copy(authConfig =
      kubescala.discovery.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      apiKey: String
  ): DiscoveryApi[kubescala.discovery.Authorization.ApiKey] =
    copy(authConfig = kubescala.discovery.Authorization.ApiKey(apiKey))

  def withNoAuth
      : DiscoveryApi[kubescala.discovery.Authorization.NoAuthorization.type] =
    copy(authConfig = kubescala.discovery.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): DiscoveryApi[kubescala.discovery.Authorization.BearerToken] =
    copy(authConfig = kubescala.discovery.Authorization.BearerToken(token))

  /** get information of a group
    *
    * Expected answers: code 200 : APIGroup (OK) code 401 : (Unauthorized)
    */
  def getDiscoveryAPIGroup
      : sttp.client4.Request[Either[ResponseException[String], APIGroup]] =
    val requestURL =
      uri"$baseUrl/apis/discovery.k8s.io/"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .response(asJson[APIGroup])

end DiscoveryApi
