/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.policy.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** PodDisruptionBudgetSpec is a description of a PodDisruptionBudget.
  */
case class PodDisruptionBudgetSpec(
    /* An eviction is allowed if at most \"maxUnavailable\" pods selected by \"selector\" are unavailable after the eviction, i.e. even in absence of the evicted pod. For example, one can prevent all voluntary evictions by specifying 0. This is a mutually exclusive setting with \"minAvailable\". */
    @named("maxUnavailable") maxUnavailable: Option[IntOrString] = scala.None,
    /* An eviction is allowed if at least \"minAvailable\" pods selected by \"selector\" will still be available after the eviction, i.e. even in the absence of the evicted pod.  So for example you can prevent all voluntary evictions by specifying \"100%\". */
    @named("minAvailable") minAvailable: Option[IntOrString] = scala.None,
    /* Label query over pods whose evictions are managed by the disruption budget. A null selector will match no pods, while an empty ({}) selector will select all pods within the namespace. */
    @named("selector") selector: Option[LabelSelector] = scala.None,
    /* UnhealthyPodEvictionPolicy defines the criteria for when unhealthy pods should be considered for eviction. Current implementation considers healthy pods, as pods that have status.conditions item with type=\"Ready\",status=\"True\".  Valid policies are IfHealthyBudget and AlwaysAllow. If no policy is specified, the default behavior will be used, which corresponds to the IfHealthyBudget policy.  IfHealthyBudget policy means that running pods (status.phase=\"Running\"), but not yet healthy can be evicted only if the guarded application is not disrupted (status.currentHealthy is at least equal to status.desiredHealthy). Healthy pods will be subject to the PDB for eviction.  AlwaysAllow policy means that all running pods (status.phase=\"Running\"), but not yet healthy are considered disrupted and can be evicted regardless of whether the criteria in a PDB is met. This means perspective running pods of a disrupted application might not get a chance to become healthy. Healthy pods will be subject to the PDB for eviction.  Additional policies may be added in the future. Clients making eviction decisions should disallow eviction of unhealthy pods if they encounter an unrecognized policy in this field.  Possible enum values:  - `\"AlwaysAllow\"` policy means that all running pods (status.phase=\"Running\"), but not yet healthy are considered disrupted and can be evicted regardless of whether the criteria in a PDB is met. This means perspective running pods of a disrupted application might not get a chance to become healthy. Healthy pods will be subject to the PDB for eviction.  - `\"IfHealthyBudget\"` policy means that running pods (status.phase=\"Running\"), but not yet healthy can be evicted only if the guarded application is not disrupted (status.currentHealthy is at least equal to status.desiredHealthy). Healthy pods will be subject to the PDB for eviction. */
    @named("unhealthyPodEvictionPolicy") unhealthyPodEvictionPolicy: Option[
      PodDisruptionBudgetSpecEnums.UnhealthyPodEvictionPolicy
    ] = scala.None
)

object PodDisruptionBudgetSpecEnums:
  enum UnhealthyPodEvictionPolicy:
    case `AlwaysAllow`
    case `IfHealthyBudget`

  object UnhealthyPodEvictionPolicy:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given unhealthyPodEvictionPolicyCodec
        : JsonValueCodec[UnhealthyPodEvictionPolicy] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "AlwaysAllow"     => "AlwaysAllow"
            case "IfHealthyBudget" => "IfHealthyBudget"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end PodDisruptionBudgetSpecEnums
