/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.events.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** APIResource specifies the name of a resource and whether it is namespaced.
  */
case class APIResource(
    /* kind is the kind for the resource (e.g. 'Foo' is the kind for a resource 'foo') */
    @named("kind") kind: String,
    /* name is the plural name of the resource. */
    @named("name") name: String,
    /* namespaced indicates if a resource is namespaced or not. */
    @named("namespaced") namespaced: Boolean,
    /* singularName is the singular name of the resource.  This allows clients to handle plural and singular opaquely. The singularName is more correct for reporting status on a single item and both singular and plural are allowed from the kubectl CLI interface. */
    @named("singularName") singularName: String,
    /* verbs is a list of supported kube verbs (this includes get, list, watch, create, update, patch, delete, deletecollection, and proxy) */
    @named("verbs") verbs: Seq[String],
    /* categories is a list of the grouped resources this resource belongs to (e.g. 'all') */
    @named("categories") categories: Option[Seq[String]] = scala.None,
    /* group is the preferred group of the resource.  Empty implies the group of the containing resource list. For subresources, this may have a different value, for example: Scale\". */
    @named("group") group: Option[String] = scala.None,
    /* shortNames is a list of suggested short names of the resource. */
    @named("shortNames") shortNames: Option[Seq[String]] = scala.None,
    /* The hash value of the storage version, the version this resource is converted to when written to the data store. Value must be treated as opaque by clients. Only equality comparison on the value is valid. This is an alpha feature and may change or be removed in the future. The field is populated by the apiserver only if the StorageVersionHash feature gate is enabled. This field will remain optional even if it graduates. */
    @named("storageVersionHash") storageVersionHash: Option[String] =
      scala.None,
    /* version is the preferred version of the resource.  Empty implies the version of the containing resource list For subresources, this may have a different value, for example: v1 (while inside a v1beta1 version of the core resource's group)\". */
    @named("version") version: Option[String] = scala.None
)
