/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.events.v1.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** EventSource contains information for an event.
  */
case class EventSource(
    /* Component from which the event is generated. */
    @named("component") component: Option[String] = scala.None,
    /* Node name on which the event is generated. */
    @named("host") host: Option[String] = scala.None
)
