/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.events.v1.models

import java.time.OffsetDateTime
import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Event is a report of an event somewhere in the cluster. It generally denotes
  * some state change in the system. Events have a limited retention time and
  * triggers and messages may evolve with time. Event consumers should not rely
  * on the timing of an event with a given Reason reflecting a consistent
  * underlying trigger, or the continued existence of events with that Reason.
  * Events should be treated as informative, best-effort, supplemental data.
  */
case class Event(
    /* eventTime is the time when this Event was first observed. It is required. */
    @named("eventTime") eventTime: OffsetDateTime,
    /* action is what action was taken/failed regarding to the regarding object. It is machine-readable. This field cannot be empty for new Events and it can have at most 128 characters. */
    @named("action") action: Option[String] = scala.None,
    /* APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
    @named("apiVersion") apiVersion: Option[String] = scala.None,
    /* deprecatedCount is the deprecated field assuring backward compatibility with core.v1 Event type. */
    @named("deprecatedCount") deprecatedCount: Option[Int] = scala.None,
    /* deprecatedFirstTimestamp is the deprecated field assuring backward compatibility with core.v1 Event type. */
    @named("deprecatedFirstTimestamp") deprecatedFirstTimestamp: Option[
      OffsetDateTime
    ] = scala.None,
    /* deprecatedLastTimestamp is the deprecated field assuring backward compatibility with core.v1 Event type. */
    @named("deprecatedLastTimestamp") deprecatedLastTimestamp: Option[
      OffsetDateTime
    ] = scala.None,
    /* deprecatedSource is the deprecated field assuring backward compatibility with core.v1 Event type. */
    @named("deprecatedSource") deprecatedSource: Option[EventSource] =
      scala.None,
    /* Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    @named("kind") kind: Option[String] = scala.None,
    /* Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata */
    @named("metadata") metadata: Option[ObjectMeta] = scala.None,
    /* note is a human-readable description of the status of this operation. Maximal length of the note is 1kB, but libraries should be prepared to handle values up to 64kB. */
    @named("note") note: Option[String] = scala.None,
    /* reason is why the action was taken. It is human-readable. This field cannot be empty for new Events and it can have at most 128 characters. */
    @named("reason") reason: Option[String] = scala.None,
    /* regarding contains the object this Event is about. In most cases it's an Object reporting controller implements, e.g. ReplicaSetController implements ReplicaSets and this event is emitted because it acts on some changes in a ReplicaSet object. */
    @named("regarding") regarding: Option[ObjectReference] = scala.None,
    /* related is the optional secondary object for more complex actions. E.g. when regarding object triggers a creation or deletion of related object. */
    @named("related") related: Option[ObjectReference] = scala.None,
    /* reportingController is the name of the controller that emitted this Event, e.g. `kubernetes.io/kubelet`. This field cannot be empty for new Events. */
    @named("reportingController") reportingController: Option[String] =
      scala.None,
    /* reportingInstance is the ID of the controller instance, e.g. `kubelet-xyzf`. This field cannot be empty for new Events and it can have at most 128 characters. */
    @named("reportingInstance") reportingInstance: Option[String] = scala.None,
    /* series is data about the Event series this event represents or nil if it's a singleton Event. */
    @named("series") series: Option[EventSeries] = scala.None,
    /* type is the type of this event (Normal, Warning), new types could be added in the future. It is machine-readable. This field cannot be empty for new Events. */
    @named("type") `type`: Option[String] = scala.None
)
