/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.networking.api

import kubescala.networking.models.APIGroup
import kubescala.networking.JsonSupport.{*, given}
import kubescala.networking.FormSerializable
import kubescala.networking.FormStyleFormat
import kubescala.networking.HeaderSerializable
import kubescala.networking.ApiKeyLocation
import kubescala.networking.PathStyleFormat
import kubescala.networking.PathSerializable
import kubescala.networking.CookieSerializable
import kubescala.networking.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object NetworkingApi:
  def apply(
      baseUrl: String = "http://localhost"
  ): NetworkingApi[kubescala.networking.Authorization.NoAuthorization.type] =
    NetworkingApi(baseUrl, kubescala.networking.Authorization.NoAuthorization)
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): NetworkingApi[kubescala.networking.Authorization.BasicAuth] =
    NetworkingApi(
      baseUrl,
      kubescala.networking.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): NetworkingApi[kubescala.networking.Authorization.ApiKey] =
    NetworkingApi(baseUrl, kubescala.networking.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): NetworkingApi[kubescala.networking.Authorization.BearerToken] =
    NetworkingApi(
      baseUrl,
      kubescala.networking.Authorization.BearerToken(token)
    )

case class NetworkingApi[Auth <: kubescala.networking.Authorization] private (
    baseUrl: String,
    authConfig: kubescala.networking.Authorization
):
  def withBasicAuth(
      username: String,
      password: String
  ): NetworkingApi[kubescala.networking.Authorization.BasicAuth] =
    copy(authConfig =
      kubescala.networking.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      apiKey: String
  ): NetworkingApi[kubescala.networking.Authorization.ApiKey] =
    copy(authConfig = kubescala.networking.Authorization.ApiKey(apiKey))

  def withNoAuth
      : NetworkingApi[kubescala.networking.Authorization.NoAuthorization.type] =
    copy(authConfig = kubescala.networking.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): NetworkingApi[kubescala.networking.Authorization.BearerToken] =
    copy(authConfig = kubescala.networking.Authorization.BearerToken(token))

  /** get information of a group
    *
    * Expected answers: code 200 : APIGroup (OK) code 401 : (Unauthorized)
    */
  def getNetworkingAPIGroup
      : sttp.client4.Request[Either[ResponseException[String], APIGroup]] =
    val requestURL =
      uri"$baseUrl/apis/networking.k8s.io/"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .response(asJson[APIGroup])

end NetworkingApi
