/** Kubernetes No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.34
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package kubescala.apiserver.api

import kubescala.apiserver.models.APIGroup
import kubescala.apiserver.JsonSupport.{*, given}
import kubescala.apiserver.FormSerializable
import kubescala.apiserver.FormStyleFormat
import kubescala.apiserver.HeaderSerializable
import kubescala.apiserver.ApiKeyLocation
import kubescala.apiserver.PathStyleFormat
import kubescala.apiserver.PathSerializable
import kubescala.apiserver.CookieSerializable
import kubescala.apiserver.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object FlowcontrolApiserverApi:
  def apply(baseUrl: String = "http://localhost"): FlowcontrolApiserverApi[
    kubescala.apiserver.Authorization.NoAuthorization.type
  ] = FlowcontrolApiserverApi(
    baseUrl,
    kubescala.apiserver.Authorization.NoAuthorization
  )
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): FlowcontrolApiserverApi[kubescala.apiserver.Authorization.BasicAuth] =
    FlowcontrolApiserverApi(
      baseUrl,
      kubescala.apiserver.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): FlowcontrolApiserverApi[kubescala.apiserver.Authorization.ApiKey] =
    FlowcontrolApiserverApi(
      baseUrl,
      kubescala.apiserver.Authorization.ApiKey(apiKey)
    )

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): FlowcontrolApiserverApi[kubescala.apiserver.Authorization.BearerToken] =
    FlowcontrolApiserverApi(
      baseUrl,
      kubescala.apiserver.Authorization.BearerToken(token)
    )

case class FlowcontrolApiserverApi[
    Auth <: kubescala.apiserver.Authorization
] private (baseUrl: String, authConfig: kubescala.apiserver.Authorization):
  def withBasicAuth(
      username: String,
      password: String
  ): FlowcontrolApiserverApi[kubescala.apiserver.Authorization.BasicAuth] =
    copy(authConfig =
      kubescala.apiserver.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      apiKey: String
  ): FlowcontrolApiserverApi[kubescala.apiserver.Authorization.ApiKey] =
    copy(authConfig = kubescala.apiserver.Authorization.ApiKey(apiKey))

  def withNoAuth: FlowcontrolApiserverApi[
    kubescala.apiserver.Authorization.NoAuthorization.type
  ] =
    copy(authConfig = kubescala.apiserver.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): FlowcontrolApiserverApi[kubescala.apiserver.Authorization.BearerToken] =
    copy(authConfig = kubescala.apiserver.Authorization.BearerToken(token))

  /** get information of a group
    *
    * Expected answers: code 200 : APIGroup (OK) code 401 : (Unauthorized)
    */
  def getFlowcontrolApiserverAPIGroup
      : sttp.client4.Request[Either[ResponseException[String], APIGroup]] =
    val requestURL =
      uri"$baseUrl/apis/flowcontrol.apiserver.k8s.io/"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .response(asJson[APIGroup])

end FlowcontrolApiserverApi
